rspamd/rspamd

- src/client/rspamc.c
- src/lua/lua_task.c
- the struct dirent d_type is not available on SunOS
- tm_gmtoff is not a POSIX field
> Fix build on SunOS

- debian/changelog
- debian/control
- debian/rules
- Use lua 5.1 if luajit is not available
- Drop workaround for old libhiredis-dev package
> Updates for 0.9.2 Debian release

- docker/Dockerfile
- docker/rspamd.conf
- docker/rspamd.list
This is tested and working in Debian Jessie (8) and I expect it'll also work fine in other versions of Debian, as the init system is irrelevant in a Docker.
> Dockerfile, for running in Docker container

- centos/rspamd.spec
libmagic included in file-devel package
> Fix centos spec

- contrib/exim/local_scan.c
A suggestion to compile entire statements and expressions, as suggested by code style guidelines from the Linux Kernel and practitioners.
https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/tree/Documentation/CodingStyle#n892
https://www.cqse.eu/en/blog/living-in-the-ifdef-hell/
It might improve code understanding, maintainability and error-proneness.
> Refactoring conditional directives that break parts of statements.

- conf/modules.d/rbl.conf
- doc/markdown/modules/rbl.md
- src/plugins/lua/rbl.lua
It's a breaking change only if one decided to edit `private_ips` instead of using `local_exclude_ip_map` as one is supposed to. ;)
> RBL module: remove `private_ips` setting in favour of `local_addrs`

- rules/regexp/headers.lua
Thunderbird version 46 and later is using new securely random Message-ID to avoid fingerprinting.
https://bugzilla.mozilla.org/show_bug.cgi?id=902580
SeaMonkey (at least current nightly build 2.42a1) is not affected by this change.
> Add new Message-ID regexp for Thunderbird

- src/libstat/backends/sqlite3_backend.c
This seems to fix language learn count- I'm not sure about user learn count as I didn't manage to work per-user stats.
```
sqlite> select * from users;
0|default|0
1||0
```
> Fix user/language learn count in sqlite statistics (#496)

- src/plugins/lua/once_received.lua
~~~
2016-02-17 13:00:50 #58424(normal) <a41bdc>; task; lua_metric_symbol_callback: call to (ONCE_RECEIVED) failed: /usr/local/share/rspamd/lua/once_received.lua:82: bad argument #1 to 'lower' (string expected, got nil); trace: [1]:{[C]:-1 - lower [C]}; [2]:{/usr/local/share/rspamd/lua/once_received.lua:82 - <unknown> [Lua]};
~~~
> Skip good hostname check for undefined hostnames

- src/plugins/lua/mime_types.lua
- this change allows to configure several mime types for an extension like
```txt = [ "message/disposition-notification", "text/plain", "text/rfc822-headers" ];```
- `type` variable replaced with `mtype` as `type` is lua reserved word
> [Feature] Add list support to `mime types` module configuration

- conf/modules.d/mime_types.conf
I'm not sure if it should be changed  in mime_types.lua ```local settings = {  extension_map = { },}``` as well.
> [Fix] `MIME_BAD_ATTACHMENT` false positives for MDN

- src/libserver/dkim.c
Add test for LibreSSL to use "old" methods when OPENSSL_VERSION_NUMBER is 0x20000000L
> Fix build with unmodified LibreSSL opensslv.h

- interface/css/rspamd.css
- interface/index.html
- interface/js/rspamd.js
The `Throughput` button is disabled. To enable it uncomment corresponding line in the `index.html`.
The reasons:
1. The widget is highly experimental and requires some improvements. In particular data representation is not pretty good, especially on long time intervals.
2. There are issues with the RRD backend: https://github.com/vstakhov/rspamd/issues/615#issuecomment-220404928, https://github.com/vstakhov/rspamd/issues/405#issuecomment-188132960
I have an idea to enable the button conditionally (if RRD is enabled in rspamd configuration) when 1 and 2 will be resolved.
> [Feature] Add throughput graph for RRD backend to WebUI

- conf/modules.d/mime_types.conf
The `application/octet-stream` mime type is commonly used  for `pdf` files by variety of automated mailing systems.
> [Minor] Add `application/octet-stream` mime type for `pdf` extension

- conf/statistic.conf
to avoid redefining everything in the classifier configuration.
> [Minor] Add includes for `classifier "bayes"`

- doc/rspamadm.1.md
- src/libstat/backends/redis_backend.c
- src/rspamadm/rspamadm.c
[Minor] Correct rspamadm -v to display actual version intead of help
> [Doc] Accent about `command options` help

- conf/modules.d/fuzzy_check.conf
This fixes #672 and fixes #563.
1. I am not quite sure if I did this right.
2. I think includes in configuration files for other modules should be relocated the same way.
> [Conf] Fix fuzzy_check.conf includes order

- doc/markdown/modules/dmarc.md
- src/plugins/lua/dmarc.lua
If global Redis configuration is present, DMARC module may start storing reporting information where it otherwise wouldn't have -& it's unlikely that anyone really wants this at this time. This patch adds a toggle to enable it & makes it disabled by default.
Ratelimit module suffers a similar issue BTW.
Also changed:
- Added DMARC disposition to reporting information
- Store reports for all messages, not just failures
- Update & rework documentation
> Allow for disabling DMARC reporting when Redis is configured globally

- conf/mime_types.inc
`text/x-vcard` is deprecated as of vCard version 4.0 specification but still used for previous versions.
> [Minor] Add text/x-vcard MIME type

- src/plugins/lua/asn.lua
- src/plugins/lua/ip_score.lua
- src/plugins/lua/multimap.lua
- test/functional/cases/102_multimap.robot
- test/functional/configs/multimap.conf
- Also strip this functionality from ip_score
- Also added simple matching of ASNs and countries in multimap. ASN module is a prefilter, so didn't worry about dependencies. Filters are probably not useful here. Figured multimap prefilter mode would likely not work here but seems it does (or I'm lucky).
> [Feature] Dedicated module for getting ASN information (Fixes #197)

- src/libserver/cfg_file.h
- src/libserver/cfg_rcl.c
- src/plugins/dkim_check.c
- src/plugins/lua/dmarc.lua
- src/plugins/lua/hfilter.lua
- src/plugins/lua/ip_score.lua
- src/plugins/lua/once_received.lua
- src/plugins/spf.c
`2016-09-29 20:43:52	Stealth	there's no way to prevent rspamd from skipping dkim/spf checks for emails forwarded mby local users?
2016-09-29 20:45:08	Stealth	I have a very special setup, when a portion of email traffic comes from mpop which fetches emails from some pop3 servers and submits them to exim`
So in case mail is injected to Exim by some system user - rspamd treats this as mail from an authenticated user. This is obviously not a recommendable way to use rspamd but I suppose we should support it as best we can.
> [Minor] Allow for re-enabling default-disabled checks

- conf/redirectors.inc
Rambler Webmail: all links are replaced to https://mail.rambler.ru/m/redirect?url=...
> Add rambler redirector

- interface/js/rspamd.js
Some error handlers are missing 'data' parameter.
> WebUI: Add missing parameter to error handlers

- conf/surbl-whitelist.inc
> ham domains added

- src/plugins/lua/greylist.lua
It could be fixed but should probably be removed I suppose.
> [Minor] Remove default message_func from greylist plugin

- rules/regexp/headers.lua
First part of this header is supposed to be a UID and I don't think it's possible to see some UID beginning with zero that is not just zero (on spam however I am seeing this).
> [Feature] Rule to detect some obvious X-PHP-Originating-Script forgeries

- src/plugins/lua/greylist.lua
@AlexeySa I don't understand why strict check`do_greylisting_required ~= "1"` is necessary. More over, I think this [condition](https://github.com/vstakhov/rspamd/blob/4cfb22716f09aa901aaa046fffa5d8c202edf9c1/src/plugins/lua/greylist.lua#L279) will never match. Did I miss something?
So this code
```lua
if action == 'reject' then return end
if do_greylisting_required and do_greylisting_required ~= "1" then
return
else
if action == 'no action' then return end
end
```
could be repaced with
```lua
if action == 'reject' then return end
if not do_greylisting_required and action == 'no action' then return end
```
or
```lua
if action == 'reject' or
not do_greylisting_required and action == 'no action' then
return
end
```
> [Minor] Further simplify conditionals

- conf/metrics.conf
@vstakhov , is `one_shot` possible for a group? I think it would be useful in the "surbl"  case.
> [Minor] Limit "surbl" group's max score

- src/plugins/lua/greylist.lua
- src/plugins/lua/ratelimit.lua
Ratelimit potentially requires information from ASN module.
> [Minor] Reduce priority for greylist/ratelimit modules

- contrib/aho-corasick/CMakeLists.txt
- contrib/aho-corasick/acism.c
This library uses g_ascii_tolower()
> acism: Add missing glib dependency

- interface/js/rspamd.js
With nginx proxy you can't use absolute /savesymbols due to rspamd being proxies as /rspamd/
> [WebUI] fix savesymbols absolute url to relative

- utils/rspamd_stats.pl
The parser should exit from the `while` loop when `--end` is reached instead of skipping lines, but I have no idea how to close the file handle properly in that case.
> [Minor] rspamd_stats: add time selectors

- interface/js/rspamd.js
I believe this code in not necessary. It doesn't work anyway: `e` != `event`
> [WebUI] Remove unused code

- src/libutil/http.c
Rspamd tried to call shm_open(3) with a path in the root filesystem
(e.g. /rhm.3f0fd440d46fac91e1b4). But DragonFly uses regular files
for shm. Obviously, this fails, because rspamd has no permissions
to create files in the root (/).
Lots of lines like the following were found in
/var/log/rspamd/rspamd.log before this patch:
rspamd_shmem_mkstemp: /usr/obj/dports/mail/rspamd/rspamd-1.4.1/src
/libutil/util.c:1970: failed to create temp shmem
/rhm.3f0fd440d46fac91e1b4: Permission denied
Also, rspamd made the receiving of mail very slow, when used
in the pre-accept rmilter setting, due to these errors. Even
worse, it just didn't filter emails at all.
This patch fixes the problem by creating the shm files in /tmp
for DragonFly. With this patch applied, these lines are gone from
the log and …
> Fix shm on DragonFly

- src/plugins/lua/force_actions.lua
```
force_actions {
actions {
reject = ["DATE_IN_PAST"];
}
messages {
DATE_IN_PAST = "smells like spam";
}
}
```
Old idea I had forgotten about, maybe it makes life easier.
> [Feature] Plugin to force actions on selected symbols

- interface/js/rspamd.js
Minor changes to make `Probable Spam` and `Temporary rejected` legend entries and chart sectors more visible on `Throughput` summary. It affects `Status` tab chart as well.
> [WebUI] Make legend entry colours more contrast

- src/plugins/lua/multimap.lua
I am not sure, why did I think there might be gaps here- I'm not able to reproduce that.
It might be useful to have empty entries in place of headers that couldn't be parsed for positioning purposes.
> Multimap: don't try handle gaps in Received headers

- src/plugins/lua/metadata_exporter.lua
- Allow for custom backends (pushers)
- Allow for backend-specific formatters & selectors to be used
Example configuration (send e-mail alert and post message over HTTP):
```
metadata_exporter {
selector = "is_spam";
pusher_enabled = ["http", "send_mail"];
pusher_format {
send_mail = "email_alert";
} 
url = "http://127.0.0.1:13376/foo";
smtp = "127.0.0.1";
mail_to = "foo@example.org";
}
```
> [Minor] More new features/rework for metadata exporter

- src/plugins/lua/rbl.lua
Setting `disabled = true` is supported but this is not consistent with everything else.
> [Minor] Support setting `enabled = false` on RBLs

- src/plugins/lua/url_redirector.lua
`fb.me` wants to see a user-agent to serve a redirect to the correct location. OTOH, it seems redirected URLs will always be under .facebook.com so it is not particularly useful to check it.
> [Minor] Use fake User-Agent in URL redirector plugin

- interface/js/app/history.js
as `.values` is unsupported in many browsers
> [WebUI] Replace `.values` method with `.map`

- rules/headers_checks.lua
- rules/misc.lua
- rules/regexp/misc.lua
- Add RCVD_NO_TLS_LAST symbol, for scoring all messages delivered without TLS (disabled by default, requested by last1 on IRC).
- Fix HTML_META_HTTP_REFRESH to match then spaces/tabs are used (reported by last1)
- Add CTYPE_MISSING_DISPOSITION
> Rules updates

- src/plugins/lua/antivirus.lua
The savdid daemon, tested under Debian jessie, acknowledges commands with 'ACC xyz' and the protocol version with 'OK SSSPx/y'. This patch makes a new read callback if such a message arrives.
> Handle for ACC and OK messages from sophos

- conf/modules.d/ratelimit.conf
I don't think these should feature in default configuration as we can't very well suggest reasonable values for them and they're likely to take users by surprise.
> [Conf] Remove ratelimits from default configuration

- utils/rspamd_stats.pl
and synopsis inconsistency with option description
> [Minor] rspamd_stats: fix `--alpha-score` option name

- rules/regexp/headers.lua
Do not trigger on messages with empty payload body as Content-Type header is not mandatory (RFC7231).
> [Minor] Fix R_MISSING_CHARSET rule

- rules/headers_checks.lua
Fixes #1655 by checking if there are at least 2 MIME parts (required by the RFC) and checking if the attachment has the .asc file extension.
> [Minor] Do not punish OpenPGP/MIME attachments

- rules/misc.lua
A displayname of the form `<something>@<name>` might have been mistaken
for an email address.
Example: `From: "Bugzilla@Mozilla" <bugzilla-daemon@mozilla.org>`
> [Minor] Validate assumed spoofed display name domains to contain a dot

- src/lua/lua_util.c
When compiled against libicu < 51 the list of allowed characters was
set to none, so all strings were flagged as spoofed.
Fixes #1689.
I didn't do exhaustive testing, but with this patch OMOGRAPH_URL doesn't flag 'google.com' and does flag 'googlе.com', while the unpatched version flags both.
> Fix lua_util_is_utf_spoofed logic

- src/plugins/lua/multimap.lua
[Multimap](https://rspamd.com/doc/modules/multimap.html)s of type `ip` currently only support IP addresses (e.g. 192.0.2.1) and not IP networks in CIDR notation (e.g. 192.0.2.0/24). Other places, like [user settings](https://www.rspamd.com/doc/configuration/settings.html), do support networks.
For consistency and to make it possible to specify a range of hosts without needing to create dozens of individual entries, this pull request adds support for networks to the multimap module. As one cannot search Redis for keys by matching a CIDR specification, this means we need to loop over all possible network masks.
Originally reported in https://github.com/mailcow/mailcow-dockerized/issues/412.
> IP netmask support for Redis multimap

- src/plugins/lua/greylist.lua
- src/plugins/lua/whitelist.lua
In whitelist & greylist module, the domain files (like spf_dkim_whitelist.inc, etc) were read as regexp map.
This caused the following false whitelists:
WHITELIST_SPF_DKIM(-3)[onmicrosoft.com]
this while only 'microsoft.com' was in the list!
Reading the maps as 'map'/'hash' instead of 'regexp' fixes the issue.
> [Fix] Don't use whitelist/greylist maps as regexp, but as map

- src/lua/lua_common.c
My compiled rspamd-1.6.2 crashes on launch, unable to expose its (embedded) lpeg to the config scripts.
2017-07-20 02:24:42 #35995(main) <5fw8hp>; cfg; rspamd_config_read: rcl parse error: cannot init lua file /usr/local/rspamd-1.6.2/share/rspamd/rules/rspamd.lua: /usr/local/rspamd-1.6.2/share/rspamd/lib/lua_util.lua:2: module 'lpeg' not found:
no field package.preload['lpeg']
no file '/usr/local/rspamd-1.6.2/share/rspamd/lua/lpeg.lua'
no file '/usr/local/rspamd-1.6.2/etc/rspamd/lua/lpeg.lua'
no file '/usr/local/rspamd-1.6.2/share/rspamd/rules/lpeg.lua'
no file '/usr/local/rspamd-1.6.2/share/rspamd/lib/lpeg.lua'
no file '/usr/local/rspamd-1.6.2/share/rspamd/lib/lpeg.so'
no file '/usr/local/share/lua/5.3/lpeg.lua'
no file '/usr/local/share/lua/5.3/lpeg/init.lua'
no file …
> [Fix] Lua: lpeg to be loaded with rspamd_lua_add_preload

- src/plugins/lua/multimap.lua
This is a cherry-pick of #1753 to the stable 1.6 version so that the fix can be included in an upcoming 1.6.3 release.
The original pull request fixed inconsistent behavior of multimaps of type `ip`: they did not support netmasks when they were stored in Redis.
> Backport "IP netmask support for Redis multimap" to 1.6

- src/libserver/url.c
```
Program terminated with signal 11, Segmentation fault.
#0  rspamd_url_task_subject_callback (url=0x7fe5c6308408, start_offset=Unhandled dwarf expression opcode 0xf3
) at /usr/src/debug/rspamd-1.6.2.7/src/libserver/url.c:2555
2555						existing->count ++;
Missing separate debuginfos, use: debuginfo-install file-libs-5.14-15.4.x86_64 glibc-2.12-1.209.el6_9.2.x86_64 keyutils-libs-1.4-5.el6.x86_64 krb5-libs-1.10.3-65.el6.x86_64 libcom_err-1.41.12-23.el6.x86_64 libevent-1.4.13-4.el6.x86_64 libgcc-4.4.7-18.el6.x86_64 libicu-4.2.1-14.el6.x86_64 libselinux-2.0.94-7.el6.x86_64 libstdc++-4.4.7-18.el6.x86_64 openssl-1.0.1e-57.el6.x86_64 sqlite-3.6.20-1.el6_7.2.x86_64 zlib-1.2.3-29.el6.x86_64
(gdb) p existing
$1 = (struct rspamd_url *) 0x0
(gdb) bt
#0  rspamd_url_task_subject_callback …
```
> [Fix] Crash in URL processing

- src/plugins/fuzzy_check.c
Currently if you have for example the following config:
`        local {
servers = "localhost:11335";
symbol = "LOCAL_FUZZY_UNKNOWN";
mime_types [
"application/*",
]
max_score = 20.0;
read_only = false;
skip_unknown = true;
algorithm = "mumhash";
fuzzy_map {
LOCAL_FUZZY_DENIED {
max_score = 20.0;
flag = 11;
}
LOCAL_FUZZY_PROB {
max_score = 10.0;
flag = 12;
}
LOCAL_FUZZY_WHITE {
max_score = 2.0;
flag = 13;
}
}
}
`
Then rspamd will use the global max_score (which is 20). For calculation of the score.
This while it should use the defined max_score in the fuzzy_map entries.
> [Fix] Use weight from map for fuzzy scoring

- src/rspamadm/control.c
Help output isn't showing all options. Add them :)
> [Fix] Add missing rspamadm control options to help

- centos/rspamd.spec
Update License to be the same as repo (ASL 2.0)
Remove hardcoded user and group
Add %{rspamd_pluginsdir}/lib/*.lua
> Various changes to CentOS RPM

- src/plugins/lua/settings.lua
This adds a `header` rule type to the [user settings](https://www.rspamd.com/doc/configuration/settings.html) to match MIME headers of the message being checked. It works analogous to the `request_header` rule type, which matches rspamd's internal request headers. So for example, to match all messages that have a subject containing a certain word, you would use
```
settings {
some_subject {
id = "some_subject";
header = {
"Subject" = "/something/i";
}
apply "default" {
something_found = 10.0;
}
symbols [
"something_found"
]
}
}
```
Of course, this can be used for any header present in an incoming message.
> User settings: add header rules

- lualib/auth_results.lua
RFC5451 stands that policy is reserved ptype and needs to have property. Without this some parsers starting to crash or omit completely authres header. 
To avoid confusion and still leave it for informational purposes we can move it simply as a "comment".
> lua auth_results: authres header needs property for "policy". Make it as a comment for dmarc. Fixes some parsers.

- interface/js/app/history.js
The EscapeHTML function called with undefined value return "undefined" as string. This PR avoid giving undefined value to sym.name
> Fix undefined symbol name in webui.

- src/plugins/lua/mime_types.lua
when next-to-last extension is a number, e.g. 23.10.2017.scr
> [Fix] Fix bad extension check

- src/plugins/lua/ratelimit.lua
Support adding a symbol in addition to setting pre-result; intention is to make it easier for `metadata exporter` to identify ratelimited mail.
> [Minor] Ratelimit: support adding informational symbol

- src/plugins/lua/multimap.lua
`flags` specifies one or more flags which *must* be present
`nflags` specifies one or more flags which must *not* be present
> [Minor] Multimap: support matching Received header flags

- rules/regexp/upstream_spam_filters.lua
This header is present for most outgoing messages from United Internet which
includes "web.de" and GMX (freemailers which are very popular in Germany) as
well as messages sent from 1and1 webhosting packages.
> add check for spam flag from United Internet

- src/libserver/milter.c
Hi,
in my postfix setup I have two different methods of authenticating users: sasl with passwords and client certificates.
rspamd only recognizes sasl authentication by evaluating the `{auth_authen}` macro. This tiny little PR also checks for `{cert_subject}`.
I've tested it against rspamd 1.6.5, works fine for me.
Any thoughts?
Kind regards
Phil
> get authenticated user from client certificate subject

- src/log_helper.c
It seems that someone used the wrong boolean operator here. The current condition means `if (True)`, while the new version makes perfect sense.
Thanks for your time,
Mike
> [Fix] Use the right boolean operator on error check

- src/libserver/url.c
[sample message](https://aluminium.tinfoilcat.org/ww-ex.exml) - some extracted URLs have trailing %5D - this patch fixes that.
> [Fix] Deal with URLs wrapped in [] in text parts

- src/plugins/lua/antivirus.lua
Recently I installed an f-prot-daemon to my mailserver and tested with an eicar attachment.
The f-prot-daemon's result line was
```
1 <infected: EICAR_Test_File> 1FFCE262AA->eicar.com
```
thus, rspamd's reject message was
```
554 5.7.1 fprot: virus found: \"EICAR_Test_File> 1FFCE262AA-\"
```
I checked with `fpscan --virlist | grep '>'` and there's no virus name containing a *greater than*, so a non-greedy match should be used here.
> f-prot: match virus name non-greedily

- src/plugins/lua/antivirus.lua
Fixes the error `(rspamd_proxy) ; lua; antivirus.lua:396: Unhandled response: 1 <contains infected objects: VIRUSNAME>` and therefore no handled detection
--
F-PROT Antivirus response if an infected file was found is
`1 <contains infected objects: VIRUSNAME>` for me, while rspamd only checks for `1 <infected: ...>`.
Unfortunately lua patterns don't allow optional unmatched groups and I don't know if the string differs in older installations or older/other setups which is why I tried to mark contains and objects as optional strings (and infected surrounded by optional whitespace).
System this was tried on: CentOS 7.2; rspamd 1.6.5 and F-PROT Antivirus fpscand version 6.0.3 (latest version from 2012/2013 with the latest signatures from 2018).
> [Fix] Virus infection string for F-PROT Antivirus

- config.h.in
- src/lua/lua_util.c
While most recent Illumos platforms may have both endian.h and flock support (e.g. SmartOS in joyent_20171212T175708Z), more traditional ones do not (e.g. SmartOS in joyent_20141030T081701Z). These two commits allow rspamd to build there (similar fcntl workaround already exists in src/libutil/util.c).
> Fix endian and flock support on (some) SunOS platforms

- lualib/dkim_sign_tools.lua
ARC should be done on incoming mails using the key for the original recipient domain.
Use together with the following config in _local.d/arc.conf_
> sign_local = false;
> sign_inbound = true;
> allow_hdrfrom_mismatch = true;
> use_domain = recipient;
> Allow signing incoming mails with recipient domain-key for ARC

- src/lua/lua_http.c
I discovered I have reason to send a given HTTP header multiple times in lua_http. This seems to work.
~~~lua
local rspamd_http = require 'rspamd_http'
rspamd_config.POINTLESS_HTTP = {
callback = function (task)
local function http_callback(err_message, code, body, headers)
return
end
rspamd_http.request({
task=task,
url='http://127.0.0.1:56789/hello',
body='hi',
callback=http_callback,
headers={
One='10',
Two='66',
Multiple={'AHOY','HI','HELLO'},
},
})
end
}
~~~
> [Feature] Support sending given header multiple times in lua_http

- contrib/DEPENDENCY_INFO.md
I've made this list to make it easier to trace bundled libraries, their versions and their licenses.
However, it is not complete, yet.
If you have any of the missing information, like versions of bundled libs, or a short description of patches applied to them in this repo (or a short Patched: _yes_/_no_), that would be very much appreciated.
Thank you!
Edit: The list also does not yet cover JS dependencies, which should/could be included as well.
> Add contrib/DEPENDENCY_INFO.md

- interface/README.md
Corrected headings by implementing proper markdown in `interface/readme.md`
> corrected headings in interface readme

- src/plugins/lua/multimap.lua
I'm writing a multimap set that relies on different headers with similar values set by different MTAs. This would allow you, for example, to merge the freemail_envfrom and freemail_envrcpt multimaps to use one symbol if you wished, or to check both To and Cc headers for an address without writing two maps.
You may already have nixed this idea for good reasons! If not, I have found it a useful option.
> Allow the multimap header type to be a list of headers as well as a single header

- lualib/rspamadm/configwizard.lua
- Fix prompt
- Remove the trailing slash of a pathname, if present
> [Minor] configwizard: minor fixes

- conf/modules.d/history_redis.conf
- src/plugins/lua/history_redis.lua
I added an option for "Subject privacy" in the webUI, as the subject may include personal information, which I don't want to see. This is only relevant when redis is used as storage for the history.
It just hashes the subject, so you can still see that a lot of spam-mails have the same subject.
I chose md5 as default, because it results in a shorter string.
> Subject privacy for webUI

- interface/js/app/stats.js
Use a `title` attribute on the stats widgets to show full specific values in addition to the `Humanize.compactInteger()` values when hovering over the compact values.
> Web UI - Add specific numbers to stats values

- lualib/lua_auth_results.lua
Take the hostname for the `AuthservID` property of the AR-header directly from a built-in utility function. This should be more reliable than getting it from `Received` headers, because in milter mode `task:get_received_headers()` returns `nil` if the incoming mail has no previous `Received` headers.
> [Minor] Improve AuthservID generation in AR-header

- src/plugins/lua/milter_headers.lua
When trying to configure the virustest extension of dovecot's sieve implementation (pidgeonhole), the x-virus milter header routine turned out to be incompatible with the limited configuration possibilities of the sieve plugin. In its simplest form, it requires a fixed header value (prefix) that can be matched against. 
This change adds two options to the X-Virus milter header routine that prefix the header value with a configured string when a virus was found (or not).
An alternative solution adding a new header routine has been implemented in #2206
I personally prefer this solution, since it requires less code changes and does not require duplicate configuration (of virus symbols).
Given the following configuration:
```groovy
use = ['x-virus'];
routines {
x-virus {
status_clean = …
```
> Add optional status prefix to X-Virus header

- lualib/lua_auth_results.lua
milter{daemon_name} contains MTA hostname by default.
> [Fix] Fix AuthservId

- contrib/libucl/lua_ucl.c
- contrib/libucl/ucl_emitter_utils.c
- contrib/libucl/ucl_util.c
626c7a1 attempted to fix vertical tab handling, but '\v' is not a valid JSON escape so most parsers will reject it.
libucl has two places that escape strings, 626c7a1 didn't modify the one that occurs during parsing, so I have done so.
As far as I can tell there's no reason for lua_ucl to use UCL_STRING_ESCAPE; strings are escaped again during JSON/UCL generation, producing excessively escaped output. Example:
```
"description": "To header display name is \\\"Recipients\\\""
```
> Small libucl fixes

- conf/modules.d/ratelimit.conf
- src/plugins/lua/ratelimit.lua
#symbol = "R_RATELIMIT";
Setting the symbol was not considered in the Plugin Code.
> Ratelimit - fix set symbol only

- interface/js/app/symbols.js
It is a bit misleading to mark "neutral" symbols (with a weight of exactly zero) with a red css background.
In my optinion, just remove the css class if that's the case.
> Don't mark "neutral" symbol weights as negative in the web ui

- utils/rspamd_stats.pl
This patch enables rspamd_stats.pl to parse RFC5424-style syslog timestamps.
> rspamd_stats.pl: Parse RFC5424 style timestamps

- rules/regexp/headers.lua
Some health insurance and payback spam is sent via a rogue MTA called "strongmail". Since it is relayed via Gmail (mostly), greylisting won't help.
Added a rule to catch this and add some extra points on it.
> add rule for rogue "strongmail" MTA

- lualib/lua_redis.lua
We should use local variables in this check because result['xxx'] are assigned later.
> Fix redis read_only was incorrectly set to true.

- src/libmime/email_addr.c
Without this patch an address like `Name (comment ) <email>` won't be parsed correctly. E.g. postfix bounce messages.
> fix email address parsing: ebraces should increase till equals obraces

- src/plugins/lua/phishing.lua
Hi there,
We have a Phishing URL validate service called CaUMa developed to represent local phishing frauds in Brazil, that service is maintained by 'Cert.Bahia'[1] and RNP[2].
We create a "generic service" in phishing module to integrate CaUMa feed without disabling any of the supported services by phishing module (PhishTank and Openphish). That allows someone to use a custom feed without remove already supported feeds.
We are using it now and is working fine! If this merge is cool to the project, We will be glad to update the documentation in 'rspamd.com' repository and fixing any issue in that patch.
[1] https://certbahia.pop-ba.rnp.br
[2] https://www.rnp.br/en
[3] https://cauma.pop-ba.rnp.br
Best Regard.
> Add generic service feed to phishing module

- src/libserver/dns.c
priority goes first and then the value
> [Minor] Fixed parsing of faked mx-record:

- conf/modules.d/rbl.conf
This changes the RBL group name from `spamhaus_xbl` to `spamhaus_received` which describes better what the group actually does.
Just some cleanup... :-)
> adjust Spamhaus group name for received IPs

- src/controller.c
- src/fuzzy_storage.c
- src/libserver/worker_util.c
- src/libutil/logger.c
- src/libutil/logger.h
- src/log_helper.c
- src/lua_worker.c
- src/rspamadm/rspamadm.c
- src/rspamd.c
- src/rspamd_proxy.c
- src/worker.c
When config is being closed, some destructors could be called, and that dtors could write into log. Hence, it is better to terminate config and only then close log. And log should not refer disposed config
> [Minor] Log should not depend on config

- .eslintrc.json
as `u` flag is not supported in ES5
> [Test] Disable warning

- conf/scores.d/rbl_group.conf
Add forgotten `one_shot = true;`  line for blocklist.de-rule which looks at `Received` addresses.
Sorry about that.
> make sure blocklist.de-rule for Received IPs only triggers once

- test/rspamd_lua_test.c
- test/rspamd_test_suite.c
example:
$ ./test/rspamd-test -p /rspamd/lua -t selectors.lua
no way to run two test suites atm
> [Test] Added key to run specific lua-test

- src/plugins/lua/dmarc.lua
Added the ability to set a custom from name instead of the static "Rspamd".
> [dmarc report] custom from address name

- contrib/hiredis/net.c
Otherwise, in the case of error, socket may become invalid
and we will get an incorrect error, i.e. "setsockopt(TCP_NODELAY): Invalid argument"
instead of "Connection refused"
> [Minor] Make socket non-blocking before connect()

- conf/modules.d/antivirus.conf
- conf/modules.d/dcc.conf
- src/plugins/lua/antivirus.lua
- src/plugins/lua/dcc.lua
- Antivirus: Next upstream should be tried on any error. Current Upstream should be set to fail in that case
- Antivirus: While scanning mime_parts only is great for caching scanned attachment digests, sometimes it's useful to scan the textparts (e.g. ClamAV Unofficial Sanesecurity ...).
- DCC: separate socket and server configuration to make use of the upstreams feature.
> Change dcc / antivirus plugins

- src/plugins/lua/ip_score.lua
check_authed  and check_local wasn't overwritten by options set in the config file.
> [Fix] ip_score - respect check_authed and check_local settings

- src/lua/lua_http.c
ev_base should be passed into lua_http.request(). It comes either from task or explicitly
> [Minor] Fixed argument check

- interface/js/app/history.js
when the total number of rows is less than number of rows per page
> [WebUI] Fix symbol description tooltips display

- .drone.yml
Note: exit code > 128 doesn't indicate that core dump was actually written, but anyway if rspamd-test was terminated by a signal script can fail - there is no need to gather coverage.
> Run gdb on core dump

- test/functional/lib/rspamd.py
Fix 'NoSuchProcess: psutil.NoSuchProcess process no longer exists' exception in functional tests.
> Tests kill race fix

- src/plugins/lua/antivirus.lua
When tables are concatenated with 0, virus names like SecuriteInfo.com.Spam-4701.UNOFFICIAL are processed as tables in cached results. Changed separator to |.
> [Fix] Antivirus - virus names with 0 were recognized as tables

- src/client/rspamc.c
It'll set the return code to EXIT_FAILURE if one of the parties (rspamd side or sub process) or both are failing.
> fix return code of rspamc

- .drone.yml
Run rspamd-test (unit test) with selected set of clang sanitizers. Don't fail test if UB detected, because there are too many of them for now.
> Run unit test with clang sanitizers

- src/libutil/mem_pool.h
due to a syntax error in preprocessor directives I'm unable to compile 1.8.2:
```
BUILDSTDERR: In file included from /builddir/build/BUILD/rspamd-1.8.2/contrib/lc-btrie/btrie.c:311:0:
BUILDSTDERR: /builddir/build/BUILD/rspamd-1.8.2/src/libutil/mem_pool.h:28:6: error: invalid preprocessing directive ##
BUILDSTDERR:  #    #define RSPAMD_ATTR_ALLOC_SIZE(pos)
BUILDSTDERR:       ^
BUILDSTDERR: /builddir/build/BUILD/rspamd-1.8.2/src/libutil/mem_pool.h:34:6: error: invalid preprocessing directive ##
BUILDSTDERR:  #    #define RSPAMD_ATTR_ALLOC_ALIGN(al)
BUILDSTDERR:       ^
BUILDSTDERR: /builddir/build/BUILD/rspamd-1.8.2/src/libutil/mem_pool.h:39:6: error: invalid preprocessing directive ##
BUILDSTDERR:  #    #define RSPAMD_ATTR_RETURNS_NONNUL
```
This PR removes the extra pound sign.
> fix preprocessor syntax as 1.8.2 fails to compile

- conf/mime_types.inc
message/rfc822 is the mimetype if you forward an email as attachment (.eml)
> Added message/rfc822 to mime_types.inc

- interface/js/app/upload.js
The successful upload of a text in the learning section is answered with HTTP status code 204, that is:
_The server has successfully processed the request and does not return any content_.
For this reason `json[0].status` must be used.
> Closes: #2684

- conf/modules.d/antivirus.conf
- lualib/lua_scanners/clamav.lua
- lualib/lua_scanners/common.lua
- lualib/lua_scanners/dcc.lua
- lualib/lua_scanners/fprot.lua
- lualib/lua_scanners/icap.lua
- lualib/lua_scanners/kaspersky_av.lua
- lualib/lua_scanners/oletools.lua
- lualib/lua_scanners/savapi.lua
- lualib/lua_scanners/sophos.lua
- src/plugins/lua/antivirus.lua
- src/plugins/lua/external_services.lua
With using patterns also for SYMBOL_FAIL it is possible to handle some error messages with composites or force actions or set a weight.
Maybe to soft reject mails not scanned by a specific virus scanner or reject encrypted attachments.
> [Minor] lua_scanners - use pattern for FAIL symbol

- src/plugins/lua/dmarc.lua
We are using CRLF everywhere but not in template itself, this PR should fix it. See https://cr.yp.to/docs/smtplf.html
> Produce DMARC report email body with CRLF

- conf/modules.d/dkim_signing.conf
- lualib/lua_dkim_tools.lua
- src/client/rspamc.c
- src/libcryptobox/ed25519/ed25519.c
- src/libcryptobox/ed25519/ed25519.h
- src/libcryptobox/ed25519/ref.c
- src/libserver/dkim.c
- src/libserver/dkim.h
- src/libserver/milter.c
- src/libserver/protocol.c
- src/plugins/dkim_check.c
- src/plugins/lua/arc.lua
- src/plugins/lua/dkim_signing.lua
- test/functional/cases/131_dkim_signing/003_eddsa.robot
- test/functional/cases/131_dkim_signing/004_invalidate_key.robot
- test/functional/cases/131_dkim_signing/005_multiple.robot
- test/functional/cases/131_dkim_signing/006_milter.robot
- test/functional/configs/dkim-eddsa.key
- test/functional/configs/dkim_signing/eddsa.conf
- test/functional/configs/dkim_signing/invalidate.conf
- test/functional/configs/dkim_signing/milter.conf
- test/functional/configs/dkim_signing/multiple.conf
- test/functional/configs/plugins.conf
- test/functional/lua/miltertest/data_dkim.lua
- test/functional/lua/miltertest/dkim_many.lua
- test/functional/lua/miltertest/dkim_one.lua
- test/functional/lua/miltertest/lib.lua
This resolves issue #2147
This set of patches adds support for ed25519 signatures, multiple signatures on a single message, and adds some tests for the new functionality. I don't expect it to get merged without more changes, but I'm opening this request to start the conversation.
Limitations:
* multiple signatures only supported when using keys from files
* multiple signatures only supported using rspamc/http, not milter
Flaws:
* configuration still a bit ugly
* exposes a low-level ed25519 primative
* end-users need to expect a scalar or array from dkim-signature in the json
> Add ed25519 and multiple signature support

- src/plugins/lua/mime_types.lua
as it is not potentially harmful
Just a note: M$ Office documents are archives and some of them may contain *.tmp files
(as well as other actually potentially dangerous extensions).
> [Minor] mime_types: remove .tmp from bad_extensions

- lualib/lua_dkim_tools.lua
ARC draft places no requirements on the domains used for the AMS header field signatures, so we can use any domain whose keys we have. 
Because I use ARC to seal incomming external emails, the `use_domain_sign_inbound="recipient"` should be sufficient. In case the server manage multiple domains, some of which do not use DKIM, I need to set static domain name (and key) to be able to seal emails for them with static domain `use_domain_sign_inbound="domain.tld"`.
> Allow setting static domain for ARC signatures

- src/libserver/html.c
- src/libserver/url.h
- src/lua/lua_url.c
Hello everyone!
I crafted some code allowing me to export visible part of each link to lua modules for further processing. I have no idea if there is other way to get such information there.
I added also new flag for url structure which inform whether visible part is something looking similar to url address. Difference between my flag and PHISHED is that, my flag does not require visible url to be in different domain.
I'll be very happy to see Your comments.
Regards!
> [Feature] Export url visible part to lua and add new url flag

- conf/modules.d/surbl.conf
- conf/scores.d/surbl_group.conf
Currently, resolved IP addresses of a domain are "only" checked against Spamhaus SBL. Since it might be useful to know if an IP address is listed in PBL, XBL, or even DROP, these are added here.
To gather full results, `zen.spamhaus.org` must be used instead of `sbl.spamhaus.org`.
> also query resolved IPs against Spamhaus ZEN

- src/lua/lua_util.c
- test/lua/unit/rspamd_util.lua
Last time I encounter some troubles with using `util.is_utf_spoofed` with only one string because behavior varies between different versions of libicu. Seems that between version 57 and 58 of ICU support for `USPOOF_MIXED_SCRIPT_CONFUSABLE` in single string context was removed. According to [ICU-12823](https://unicode-org.atlassian.net/browse/ICU-12823) and [BUG 12594](http://bugs.icu-project.org/trac/ticket/12549) and [this MR](https://codereview.appspot.com/307020043/diff/1/i18n/uspoof_impl.cpp?context=10&column_width=80)
I personally find this option very useful, especially for processing part of my messages in lua, therefore I implement something similar as a PoC. If You think that it might be useful, I'll create additional tests or maybe we should think about adding this to …
> [Minor] Add util.if_utf_mixed_script to lua

- src/plugins/lua/elastic.lua
Since version 6.7.0 of ElasticSearch, the ingest-geoip plugin is a module integrated into the solution.
Instead of detecting the version of ElasticSearch I added the configuration parameter ingest_module which is false by default for ElasticSearch versions < 6.7.0 and true for versions >= 6.7.0
> add support ES>=6.7 for elasctic module

- conf/composites.conf
Adding another reference to the [composite symbols](https://rspamd.com/doc/configuration/composites.html) in the `conf/composites.conf`.
> Add composite symbols reference to conf/composites.conf

- src/plugins/lua/mime_types.lua
Hackers sometimes try to hide the filename of an attachment by encoding some characters in HEX (e.g. "attached%2E%62at"). The most e-mail clients would decode this characters and the final filename would be "attached.bat". The mime_types plugin now decodes those characters before determining the file extension.
Additionally, the plugin now uses the higher weighted MIME type, if the detected type differs from the one specified in the Content-Type header, so we are always on the safe side.
> [Minor] Improve mime_types plugin

- src/libutil/addr.c
Dropping of leading colon must be performed after the "IPv6:" prefix
is stripped.
Also fixed a couple of wrong comments.
> libutil: Fix parsing of address "IPv6:::1"

- interface/index.html
- interface/js/app/config.js
- interface/js/app/rspamd.js
as it is unnecessary for a `form` element.
> [Minor] Remove `form` role

- src/plugins/lua/clickhouse.lua
- test/functional/cases/210_clickhouse/001_migration.robot
Log more data to ClickHouse.
Unfortunately it is not easy to migrate from storing only first recipient to storing all recipients in an array without loosing current data, so for some time we probably have to log first recipient twice - in an array and in RcptUser/RcptDomain columns.
> Clickhouse

- lualib/lua_util.lua
1. Return empty string as is (to save space).
2. Don't add ':' if prefix is empty.
> More usable maybe_obfuscate_string

- lualib/rspamadm/rescore.lua
This minor fix resolves a deprecation warning which appears when running
```shell
$ rspamadm pw
cannot execute lua script /usr/local/share/rspamd/lualib/rspamadm//rescore.lua: /usr/local/share/rspamd/lualib/rspamadm//rescore.lua:301: nesting
of [[...]] is deprecated near '['
Enter passphrase:
```
> [Minor] fix lua [[...]] is deprecated near '['

- conf/modules.d/p0f.conf
- lualib/lua_scanners/p0f.lua
- src/plugins/lua/p0f.lua
- test/functional/cases/161_p0f.robot
- test/functional/util/dummy_p0f.py
This PR fixes a couple of problems with p0f plugin, that I've noticed during it's usage in small-scale production environment.
Major one being typo on [line 159](https://github.com/denpaforks/rspamd/blob/master/lualib/lua_scanners/p0f.lua#L159) of `./lualib/lua_scanners/p0f.lua` (redis_prams instead of redis_params) which prevented redis cache from ever being used. I've included test cases for cached results to make sure that everything works correctly now.
I've also changed default socket location to `/var/run/p0f.sock` as per @moisseev recommendation in #3037.
> [Minor] Fix typos in p0f plugin

- src/lua/lua_ip.c
rspamd_inet_address_compare() seems to return a <0 / =0 / >0 valua à la strcmp(). Or am I mistaken?
> [Fix] Fix lua_ip_equal logic

- conf/modules.d/arc.conf
The original commit:
198dca66a ARC signing instead of DKIM signing.
was unintended "reverted" in:
3288513eb [Config] Reasonable default settings for ARC
> ARC signing instead of DKIM signing.

- src/plugins/lua/maillist.lua
Mails from Google Groups don't have the List-Subscribe header. As a result their score from check_generic_list_headers will be reduced to 0.625 and additional tests (check_ml_googlegroup) need a score of > 1 to process.
```
maillist; maillist.lua:209: has header List-Id, score = 0
maillist; maillist.lua:215: has header Precedence: list, score = 0.75
maillist; maillist.lua:222: has header List-Archive, score = 1
maillist; maillist.lua:232: has header List-Help, score = 1.125
maillist; maillist.lua:245: has header List-Unsubscribe, score = 1.25
maillist; maillist.lua:263: final maillist score 0.625
```
As a result of the change lists will still be penalized for not having List-Subscribe, but not as harshly. Google Groups will now qualify with a score of 1.125.
```
maillist; …
```
> Fix maillist checks to catch Google Groups.

- src/plugins/lua/dmarc.lua
This pull request fixes a few issues with the sending of DMARC reports.
Processing the email template was causing a parse error (#3054). This was caused by the use of `{% ... %}` statements instead of `{= ... =}` output expressions.
Once the template was fixed, the generated message was failing to be sent over SMTP. The socket was being closing after reading the response to the `DATA` command. The following errors were being logged:
> lua_tcp_arg_toiovec: bad argument at position -1
> lua_tcp_add_write: tcp request has bad data argument at pos 3
This was caused by the number of substitutions made by `gsub` being added to the message table.
Finally, sending would stop after processing the first message. This was caused by the sendmail callback function missing a call to …
> Fix issues sending DMARC reports

- lualib/lua_scanners/p0f.lua
- src/plugins/lua/milter_headers.lua
- Skip cache when p0f failed with error or missing record (was causing error message `wrong number of arguments for 'setex' command` in the log)
- Fixed incorrect parameter for `add_header()` function in x-os-fingerprint header routine. Routine name should've been passed instead of full header name.
- _(in the same commit as above)_ Use `double` instead of `int` when unpacking integers from mempool in x-os-fingerprint routine.
> [Minor] Fixes for p0f plugin

- src/plugins/lua/dmarc.lua
When sending DMARC reports, the reporting addresses are not being included in the logs. For example:
> <>; lua; dmarc.lua:977: sending report for googlemail.com <>
`table.concat` is being used to build a string containing the email addresses. However,  `reporting_addr` uses the email addresses as keys, so `table.concat` won't produce any output.
This pull request adds a temporary table to use for concatenating the email addresses into the log message.
> Fix not logging DMARC reporting addresses

- interface/js/app/config.js
1. Function is triggered by click on close button **and** by clicking anywhere outside the modal to close it.
2. Form is being removed instead of hidden.
> Remove prev form when clicking outside the modal

- src/plugins/lua/clickhouse.lua
Fix log message, which was broken in c9e6e26319c08a0e440a9e27b9bf3743e32ad70b
nrows is 0 when clickhouse_send_data is called.
> [Minor] Clickhouse: fix log

- rules/regexp/headers.lua
The old regexp is susceptible to exponential backtracking.
pcretest benchmark:
```
PCRE version 8.43 2019-02-23
/^<mailman\.\d+\.\d+\.\d+\..+\@\S+>$/
<mailman.0.1037840296.16399.mailman-developers@example.org>
Execute time 0.0006 milliseconds
0: <mailman.0.1037840296.16399.mailman-developers@example.org>
<mailman.0.0.0.@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ …
```
> [Minor] Optimize mailman_msgid regexp

- src/plugins/lua/multimap.lua
Looking into multimap code I found this feature was projected (type `user` defined in `value_types`), but not implemented.
I hope my small PR is good enough to be merged.
Closes: #3155
> [Minor] Multimap: implemented matching authorized user

- src/lua/lua_config.c
You are able to re-register the interval for the periodic function by returning a numerical value. This updates the documentation to include this.
> Add undocumented interval change on add_periodic to documentation

- CMakeLists.txt
- cmake/Openblas.cmake
Remove `ENABLE_OPENBLAS` option because it is not used to check if the openblas should be used currently, but `ENABLE_BLAS` from `CMakeLists.txt` is.
Hopefully, I didn't missed anything. I believe this commit may avoid future confusion in configuration phase.
> cmake: remove unused ENABLE_OPENBLAS

- lualib/rspamadm/vault.lua
I noticed this while building a dummy Vault-like backend.
> Send Content-Type header in Vault create request

- src/libutil/regexp.c
This is fixing a configtest crash of rspamd on Gentoo Linux.
> fix NULL pointer use when JIT compiling a regular expression.

- test/lua/unit/url.lua
Currently it fails because fragment is not extracted correctly.
> [Test] Add a test case for URL parsing

- lualib/lua_dkim_tools.lua
If any of "sign_networks", "auth_only", or "sign_local" are disabled,
then it should not automatically proceed with signing if the enabled
conditions all fail. For example, if only the auth_only setting is
enabled, and is_authed is false, then signing should be skipped.
An earlier check luckily prevents this correctness issue from being
exploitable ("ignoring unauthenticated mail"), but fix the logic anyway.
> [Minor] Dkim_signing: correct is_skip_sign logic

- src/libstat/backends/redis_backend.c
In the case of `per_user` model, redis `SMEMBER` may block the redis server for a long time if there are many users.
So to use `SSCAN` instead.
> Eliminate redis SMEMBERS usage

- src/rspamadm/lua_repl.c
../src/rspamadm/lua_repl.c: In function ‘rspamadm_lua_run_repl’:
../src/rspamadm/lua_repl.c:615:8: warning: unused variable ‘i’ [-Wunused-variable]
615 |  gsize i;
|        ^
../src/rspamadm/lua_repl.c:614:11: warning: unused variable ‘tb’ [-Wunused-variable]
614 |  GString *tb = NULL;
|           ^~
../src/rspamadm/lua_repl.c:613:11: warning: unused variable ‘is_multiline’ [-Wunused-variable]
613 |  gboolean is_multiline = FALSE;
|           ^~~~~~~~~~~~
../src/rspamadm/lua_repl.c: In function ‘rspamadm_lua’:
../src/rspamadm/lua_repl.c:1007:3: warning: implicit declaration of function ‘replxx_set_max_history_size’ [-Wimplicit-function-declaration]
1007 |   replxx_set_max_history_size (rx_instance, max_history);
|   ^~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/rspamadm/lua_repl.c:1007:32: error: …
> [Minor] fix compilation without replxx

- src/plugins/lua/dmarc.lua
- src/plugins/lua/force_actions.lua
Dear maintainers
Today I have found two minor issues, one in the force_actions and another in the dmarc plugin.
**force_actions**
The plugin registers a symbol for every configured rule with its name prefixed with 'FORCE_ACTION_'.
The issue is that the prefix is not printed in the log messages which is misleading.
**dmarc**
It appears that the symbol DMARC_BAD_POLICY has been forgotten to register. This causes rspamd to warn about it if someone creates a forced action based on this symbol:
_cannot find dependency on symbol DMARC_BAD_POLICY for symbol FORCE_ACTION_DMARC_BAD_POLICY_
> Two minor bugfixes

- src/libmime/mime_expressions.c
According to the documentation R flag is for regexp which applied for
all headers (unencoded):
https://rspamd.com/doc/modules/regexp.html#regular-expressions
> [Fix] 'R' flag is for all headers regexp

- src/plugins/lua/dmarc.lua
According to a post on dmarc.org [Link](https://dmarc.org/2016/07/common-problems-with-dmarc-records/),  the string “DMARC” is the only portion of the DMARC policy record that is case-sensitive, but it is not uncommon for people reading the specification to miss this fact.
It seems that this happened when the DMARC plugin was developed and I hereby fixed this issue.
> [Minor] Fix parsing DMARC records containing upper-case letters

- centos/rspamd.spec
- debian/changelog
- debian/control
- debian/source/format
- set-version.sh
Two more changes to reduce the patching necessary in rspamd_build.sh, and to ensure that `dpkg-buildpackage -b -us -uc` produces a package with a recent version number to make upgrading easier.
CC @sbadia (the current Debian maintainer)
___
[Minor] Update Debian and RPM package versions
* Add script that can be used after tagging to update versions.
* Example (for this commit): `./set-version.sh 2.4`
* Clear Debian changelog, this information is not updated anyway.
[Minor] debian/control: Update Vcs-Git URL and maintainer
* Let Vcs-Git point to a secure transport.
* Use Vsevolod's email address as maintainer to avoid having to patch
this file in rspamd_build.sh. Mikhail is not the current maintainer of
the Debian package anyway.
[Minor] use quilt for debian/source/format
* Match the build …
> Update packaging versions

- src/libserver/cfg_utils.c
- src/rspamd.c
* Add support for looking up sockets by the systemd socket name, e.g.
`systemd:rspamd-proxy.socket` or the name from `FileDescriptorName`.
https://www.freedesktop.org/software/systemd/man/sd_listen_fds.html
* Replace EOVERFLOW error code to avoid confusing error messages.
Fixes: #2035
___
Tested with various combinations (and with ASAN/UBSAN):
- `systemd:control`
- `systemd:0`, `systemd:control`
- `systemd:-1` (bad)
- `systemd:1` (bad)
- `systemd:invalid` (bad)
- `systemd:control`, `systemd:proxy`
> [Fix] Support listening on systemd sockets by name

- src/rspamd.c
We can add varaibels on the command line after argument or using --var parameter.
When --var is used, an assertion is triggered:
```
./rspamd.install/bin/rspamd --var LOGDIR=/tmp/
(rspamd:7171): GLib-CRITICAL **: g_hash_table_insert_internal: assertion 'hash_table != NULL' failed
```
The hash table is not initialized, because the table is initialized after
the argument parser.
This patch initialize the hash table on demand.
**Note**: the patch is tested on 1.9 version and not on master, because I can't compile the master branch. The code is easy, I guess the right behavior.
**Note**: I suggest to backport the patch on 1.9 version
> [Minor] --var doesn't work

- config.h.in
GCC recommands to add alternative to __has_attribute operator:
https://gcc.gnu.org/onlinedocs/cpp/_005f_005fhas_005fattribute.html
Without this alternative, the project doesn't build with some GCC version.
In other way, the alternative is written i other part of rspamd like mem_pool.h
> [Minor] Compilation error with __has_attribuute operator

- src/rspamd.c
When the configuration file contains only these two lines, rspamd
try to send log which announce that it can bind the soket, but
"bind_conf" is NULL and it is dereferenced, so we have a segfault.
worker "normal" {
}
This patch fix the segfault.
> [Minor] Segfault for some configuration.

- rules/headers_checks.lua
Previous condition have a complex condition which prevented adding the
symbol for some MIME messages without MIME-Version header.
> [Minor] Improve MISSING_MIME_VERSION rule

- contrib/replxx/src/io.cxx
723d9c84869511dfb5e63f5c3d3372ac38114713 in replxx's git.
Building rspamd with gcc10 errors out with "'runtime_error' is not a
member of 'std'" otherwise.
> [Minor] Cherry-pick a fix for replxx to build with gcc10

- src/plugins/lua/rbl.lua
check_helo is missing return true. The check is skipped always.
> [Fix] rbl.lua: Helo Check always skipped

- lualib/lua_selectors/extractors.lua
- lualib/lua_selectors/transforms.lua
- src/plugins/lua/force_actions.lua
Allow variables with the following prefixes in the smtp return message for force_actions rules:
- 'selector::\<selector-expression\>' => fill with value extracted by a selector
(selectors are powerful and allow for a lot of different information)
- 'symbol::\<symbol-name\>'   => fill with matching symbol option string(s)
(e.g. custom lua plugin to filter attachments adds unwanted files as symbol option string)
- 'task::\<task-attribute\>'     => fill with matching task attribute (ONLY 'queue_id' and 'uid' ALLOWED!)
(this prefix is needed for queue_id and uid which cannot be extracted by a selector) 
See https://github.com/rspamd/rspamd/issues/3335 for details.
> [Feature] allow variables in force_actions messages

- lualib/lua_scanners/common.lua
- src/lua/lua_task.c
If the antivirus module says "Reject this mail", this shouldn't be overruled later on.
fixes #3279
> [Fix] Do not flag pre-result of virus scanners as least if action is reject

- contrib/hiredis/async.c
- contrib/hiredis/async.h
- src/libserver/redis_pool.c
This reverts commit b05b9bf904edce75c17e63982d5e0a82dd3e9064.
Async hiredis allows to pass user specific data to the callback function via `data` element of `struct redisAsyncContext` (see https://github.com/rspamd/rspamd/blob/192c6b791d1c2b42861df6526c663f1d0814ee84/contrib/hiredis/async.h#L69-L70). I would suggest to use it as intended and revert your changes. This change makes the rspamd compatible with upstream hiredis.
> Revert "[Fix] Fix hiredis stupidity" and use the hiredis api as intended

- src/plugins/lua/elastic.lua
Since version 7.x of ElasticSearch, logs type is not supported.
Close #3324
> [fix] add support ElasticSearch>=7 for elastic module

- contrib/lua-lpeg/lptypes.h
This disables a workaround only intended for aarch64 if the target
architecture is powerpc.
Issue: #3365
> [Fix] Segmentation fault in contrib/lua-lpeg/lpvm.c on ppc64el

- src/plugins/lua/rbl.lua
email_tbl.addr was not used in add_dns_request.
> [Fix] lowercase for emails checked on RBLs

- test/functional/cases/108_settings.robot
- test/functional/configs/settings.conf
Is it worth fixing I wonder? This works in legacy settings (when contents of `apply` block is wrapped in `default`) but not otherwise. However not clear if it particularly should work; there are other ways to solve the problems which may cause people to reach for this -& maybe no-one really does.
> [Test] Settings: empty symbols_enabled / groups_enabled

- conf/scores.d/mime_types_group.conf
- src/plugins/lua/mime_types.lua
that have generic split file extensions (e.g. .001)
> [Minor] Penalize EXE files in RAR archives

- rules/controller/selectors.lua
We should treat invalid selector as a negative result of the check.
> [Minor] Fix HTTP status code

- src/plugins/lua/replies.lua
Skip messages with an empty or too short Message-ID (e. g. <>)
in replies module.
> [Minor] Don't save empty Message-ID in replies module

- test/functional/cases/120_fuzzy/lib.robot
- test/functional/cases/121_json/lib.robot
- test/functional/cases/140_proxy.robot
- test/functional/cases/210_clickhouse/001_migration.robot
- test/functional/lib/rspamd.robot
With the contemporary version of Robot Framework it's printing a lot of warnings:
```
[ WARN ] Accessing variable items using '&{kwargs}[CONFIG]' syntax is deprecated. Use '${kwargs}[CONFIG]' instead.
[ WARN ] Accessing variable items using '@{result}[0]' syntax is deprecated. Use '${result}[0]' instead.
```
This patch makes the warnings go away.
> [Test] Don't use deprecated RobotFramework syntax

- lualib/lua_fuzzy.lua
Fix typo: `skip_imagess` -> `skip_images`
> [Minor] Fix typo in lua_fuzzy options

- src/plugins/fuzzy_check.c
Message:
```
<8337fe>; task; fuzzy_insert_result: found exact fuzzy hash(txt) *** with weight: 1.00, probability 1.00, in list: SYMBOL_NAME:1; added on 18.00.2020 15:41:25 GMT
```
doesn't look right.
> [Minor] Fix off-by-one error in log message

- interface/js/app/stats.js
response on legacy servers.
Namely "config_id", "version" and "uptime".
> [WebUI] Use /auth to get data missing in /stat

- lualib/lua_magic/heuristics.lua
Types which are used for html (xhtml) attachments:
text/html
application/html
application/xhtml+xml
Type which cannot be found in the wild: application/htm
> [Minor] Improve lua_magic HTML content type check

- src/plugins/lua/neural.lua
Modified the neural network to use ceb_neg loss function. 
For neural network with tanh output, ceb_neg works better than ceb or mse.
> [Fix] Change neural plugin's loss function

- src/plugins/lua/clickhouse.lua
While performing the Clickhouse SQL migrations this error line occurs: 
`2020-09-29 14:54:45 #72388(controller) <6oiiuq>; lua; clickhouse.lua:1109: cannot apply migration 4: 'ALTER TABLE rspamd\0a      MODIFY COLUMN Action Enum8('reject' = 0, 'rewrite subject' = 1, 'add header' = 2, 'greylist' = 3, 'no action' = 4, 'soft reject' = 5, 'custom' = 6) DEFAULT 'no action',\0a      ADD IF NOT EXISTS COLUMN CustomAction String AFTER Action\0a    ' on clickhouse server [***]:8123: Code: 62, e.displayText() = DB::Exception: Syntax error: failed at position 205 ('IF') (line 3, col 11): IF NOT EXISTS COLUMN CustomAction String AFTER Action\0a    . Expected one of: INDEX, CONSTRAINT, COLUMN (version 20.8.3.18 (official build))\0a`
This is caused by a [Clickhouse SQL Syntax …
> [FIX] Clickhouse Migrations SQL Syntax Error

- src/plugins/dkim_check.c
According to https://tools.ietf.org/html/rfc8058#section-4 list-unsubscribe-post and list-unsubscribe must be part of dkim sign headers for a working "One-Click Unsubscribe"
> [Minor] dkim_signing - add list-unsubscribe-post to sign_headers

- rules/mid.lua
Hi,
I observed that on emails coming from gmail the symbol "MID_RHS_MATCH_FROM" was triggered. Gmail uses the hostname "@mail.gmail.com" in MID.
I therefore suggest you add a symbol "MID_RHS_MATCH_FROMTLD",  to compare the TLD of hostnames in FROM and MID.
Thanks.
> [MID] check TLD hostname

- src/plugins/lua/forged_recipients.lua
If RFC5321.MailFrom has an address with uppercase domain following error
happens:
/usr/share/rspamd/plugins/forged_recipients.lua:129: attempt to index a nil value; trace: [1]:{/usr/share/rspamd/plugins/forged_recipients.lua:129 - <unknown> [Lua]};
Lowercase a domain.
> [Minor] forged_recipients: fix for uppercase RFC5321.MailFrom domain

- lualib/lua_clickhouse.lua
If the last column in the table is a string and the last character of that string is the carriage return then the write will fail without escaping.
> [Fix] Clickhouse: escape carriage return

- lualib/lua_scanners/icap.lua
The ICAP User Agent is more useful when it is providing version information. 
Furthermore this will accidentially resolve issue #3495.
> [Minor] Add Rspamd version to ICAP User Agent

- rules/headers_checks.lua
- rules/regexp/headers.lua
- rules/regexp/upstream_spam_filters.lua
Mail from AOL not longer have X-AOL-Global-Disposition header and this
rule no longer works.  AOL messages now have X-YMail-OSG header (like
yahoo.com), but it is encrypted/obfuscated and cannot be used here.
> [Minor] Remove AOL_SPAM rule

- docker/Dockerfile
The host has a 301 redirect to HTTPS anyway
> [Minor] Docker: use apt-transport-https

- src/plugins/lua/force_actions.lua
When the current action is the same as the configured action processing of the force_action rule ist bypassed.
But subject or message should be set as configured.
> force_actions - maybe disable current action bypass

- src/libserver/http/http_message.c
```
/builds/cgzones/rspamd/debian/output/source_dir/src/libserver/http/http_message.c: In function 'rspamd_http_message_set_body':
/builds/cgzones/rspamd/debian/output/source_dir/src/libserver/http/http_message.c:201:23: warning: comparison is always true due to limited range of data type [-Wtype-limits]
201 |   if (len != 0 && len != ULLONG_MAX) {
|                       ^~
/builds/cgzones/rspamd/debian/output/source_dir/src/libserver/http/http_message.c:230:23: warning: comparison is always true due to limited range of data type [-Wtype-limits]
230 |   if (len != 0 && len != ULLONG_MAX) {
|                       ^~
```
There is another interesting warning:
```
/builds/cgzones/rspamd/debian/output/source_dir/src/plugins/fuzzy_check.c: In function 'fuzzy_lua_gen_hashes_handler': …
```
> Check gsize against G_MAXSIZE not ULLONG_MAX

- src/plugins/lua/milter_headers.lua
This commit fixes the inverted logic of skip_wanted/match_extended_headers_rcpt to allow a user to enable extended headers selectively for only a specific set of recipients.
> [Fix] #3400 milter_headers: fix inverted logic for extended_headers_rcpt

- src/plugins/lua/milter_headers.lua
This PR introduces the new configuration option "skip_all" for milter_headers.
This config option will skip the addition of extended spam headers for every mail, except those with recipients listed in the extended_headers_rcpt map.
Documentation is updated in https://github.com/rspamd/rspamd.com/pull/487
This solution was proposed by @moisseev in https://github.com/rspamd/rspamd/pull/3607#issuecomment-762319736. 
It works well, is backward-compatible with previous configurations and enables the new usage of only adding extended headers to a specific list of recipients.
> [Minor] milter_headers: new option skip_all

- rules/regexp/headers.lua
The left part of the Mozilla Message-ID is a hexadecimal timestamp. The regexp was mistakenly limited to 2021-01-14.
> [Fix] Fix Mozilla Message-ID detection

- lualib/lua_cfg_transform.lua
Fix "unknown element in actions section: discard" message for quarantine and discard actions.
This warning would be also present for other custom actions.
> [Minor] cfg_transform - fix actions sanity check

- docker/Dockerfile
Small change to ensure that the signing key is used for the fetching the debian package.
> [Minor] Dockerfile: Set signing-key

- src/controller.c
- src/libserver/worker_util.c
- src/libserver/worker_util.h
This is a first attempt to have OpenMetrics / Prometheus formatted metrics natively included in rspamd.
If the /stat endpoint is requested with a parameter format=openmetrics,
it will respond in OpenMetrics format instead of JSON.
Currently this is a WIP to get early feedback on the approach, as I'm using horrible string concatenation to get a formatted output.
Linking discussion: https://github.com/rspamd/rspamd/discussions/3484
> Implement an endpoint for OpenMetrics / Prometheus

- rules/regexp/headers.lua
Add more regexps to `FORGED_X_MAILER` and `OLD_X_MAILER`.  While here increase score for `FORGED_X_MAILER` a bit.
> Minor updates to X-Mailer regexps

- src/controller.c
Otherwise the endpoint will output:
`pools_freed 53d`
instead of
`pools_freed 53`
> src/controller.c: Replace formatter

- conf/modules.d/external_relay.conf
- src/plugins/lua/external_relay.lua
- test/functional/cases/001_merged/__init__.robot
- test/functional/cases/380_external_relay.robot
- test/functional/configs/maps/external_relay.hostname_map
- test/functional/configs/maps/external_relay.user_map
- test/functional/configs/merged-local.conf
- test/functional/configs/merged.conf
- test/functional/lua/external_relay.lua
- test/functional/messages/received5.eml
- test/functional/messages/received6.eml
Thoughts about having such a plugin / how that should work?
It'd be better that people would do filtering on the MX rather than somewhere beyond it - but if they can't/won't do that a plugin like this might be useful (people seem to ask after something like this periodically & I've been referring them to [this old mailing post](https://groups.google.com/g/rspamd/c/_JusHAeeG74/m/xpsSyXdyDwAJ)).
Currently four different strategies are supported:
`local`: use first non-local IP, or last header
`authenticated`: use first unauthenticated hop
`hostname_map`: look for direct/indirect relays by hostname
`count`: use Received header at some set position (without condition but one might use `rspamd_config:add_condition()`)
> [Feature] external_relay plugin

- src/plugins/lua/asn.lua
In case of an dns timeout or error in common, the DNS callback function does not return. 
It then still tries to process the results. This interrupts the further processing of the mail.
Example:
> [Fix]: Lua ASN - CB func should also return in case of an error

- src/lua/lua_mimepart.c
Previous method description appeared to be confusing.
> [Minor] rewrite doc of text_part:get_fuzzy_hashes method

- docker/Dockerfile
The SKS keyserver infrastructure has been under attack for some time, and at the moment is unreachable.  The keys.openpgp.org keyserver has the rspamd key, and is resistant to the sort of attack that is hurting the SKS keyservers.  This change switches to that keyserver.
gpg won't load new keys from keys.openpgp.org unless the owner consented to publish the uids (see https://keys.openpgp.org/about/faq#older-gnupg).  This means you need the key imported first with the uid attached.  Here, we include the essential part of the key (the master key, uid, and its self-signature) in the Dockerfile.  We still poll keys.openpgp.org for updates, such as expiration extensions and revocations.
See https://gist.github.com/rjhansen/67ab921ffb4084c865b3618d6955275f for background.
> Switch PGP keyserver to hkps://keys.openpgp.org

- lualib/lua_scanners/pyzor.lua
Based on https://github.com/rspamd/rspamd/commit/d159074e35b6dd8d3fd2a27f106aa3e12fe92445
Module
* Install `pyzor` e.g. on CentOS/Rocky Linux `yum install pyzor`
* Enable the module in `/etc/rspamd/local.d/external_services.conf`
```
...
pyzor {
servers = "127.0.0.1:5953"
}
```
* Restart rspamd  `systemctl restart rspamd`
Socket
* Create `pyzor.socket` in `/usr/lib/systemd/system`
```
[Unit]
Description=Pyzor socket
[Socket]
ListenStream=127.0.0.1:5953
Accept=yes
[Install]
WantedBy=sockets.target
```
* Create `pyzor@.service` in `/usr/lib/systemd/system`
```
[Unit]
Description=Pyzor Socket Service
Requires=pyzor.socket
[Service]
Type=simple
ExecStart=-/usr/bin/pyzor check -
StandardInput=socket
StandardError=journal
TimeoutStopSec=10
User=_rspamd
NoNewPrivileges=true
PrivateDevices=true …
```
> [Feature] Re-add pyzor support

- src/controller.c
- src/libserver/cfg_file.h
These endpoints allow an orchestrator like kubernetes to verify the
status of rspamd (https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/)
Currently, implementation for both is minimal. 
The health endpoint should allow to verify rspamd internally. It could check for internal configuration and ensure that rspamd itself is healthy and available.
The ready endpoint signals that rspamd is ready to receive and process traffic and thus ensures that configured external components are available. The readiness check could for example test if configured redis servers or at least one rspamd upstreams is available. 
If desired, I can try to figure out how to improve the checks on both endpoints, I was hoping for some feedback on what to check or …
> Add health and readiness checks

- src/plugins/lua/asn.lua
Fix error:
lua_dns_resolver_callback: call to dns callback failed: /usr/share/rspamd/plugins/asn.lua:74: attempt to concatenate field 'symbol' (a boolean value); trace: [1]:{/usr/share/rspamd/plugins/asn.lua:74 - <unknown> [Lua]};
Which happen when the main asn symbol is disabled in asn.conf using
symbol = false;
> [Fix] ASN: fix _FAIL symbol for when main symbol is disabled

- rules/regexp/compromised_hosts.lua
Remove /i flag from regexp string "eval()'d code" is always in
lower case. While here use long string format for readability.
> [Rules] Micro-optimize X_PHP_EVAL

- src/plugins/lua/multimap.lua
**Describe the bug**
redis+selector maps are not recognized as valid map types.
**Steps to Reproduce**
```
cat /etc/rspamd/local.d/multimap.conf
test_map {
type = "from"
filter = "email"
map = "redis+selector://id('blacklist:');rcpts:addr.take_n(5).lower";
description = "Test map";
symbol = "TEST_MAP"
score = 5.0;
}
```
**Expected behavior**
The map should be read at startup. Redis keys should be processed accordingly.
**Versions**
Both 2.7 and master
**Additional Information**
I believe multimap.lua should have the "redis+selector" pattern escaped as "redis%+selector". This would make it easier for string.find to match the documented map string.
> Escape redis+selector

- lualib/lua_scanners/init.lua
Just upgraded to **rspamd-2.8-53.gitd04d85307** and noticed that pyzor was no longer loading:
```
2021-08-10 11:34:40 #3667(main) <t595kk>; lua; external_services.lua:124: unknown external scanner type: pyzor
2021-08-10 11:34:40 #3667(main) <t595kk>; lua; external_services.lua:212: cannot add rule: "pyzor"
```
Suppose i forgot a file in #3816, my bad...
> [Minor] Init pyzor

- CMakeLists.txt
This gives packagers option to use system version of fmt rather than bundled one. It is disabled by default.
I would like to point out that it is very unpleasant to maintain rspamd package in Gentoo with this huge amount of bundled libraries, especially for libraries usually present in the system. I believe other maintainers would appreciate possibility to choose between system or bundled version as well. https://wiki.gentoo.org/wiki/Why_not_bundle_dependencies
> Add SYSTEM_FMT cmake option

- rules/regexp/upstream_spam_filters.lua
In addition to `X-UI-Out-Filterresults` the header `X-UI-Filterresults` is also in use.
> Regexp: Extend UNITEDINTERNET_SPAM upstream spam filter regexp

- contrib/lua-lpeg/lptree.c
- contrib/lua-lpeg/lptypes.h
- contrib/lua-lpeg/lpvm.c
Removes the 64bit LUD workaround since 64bit LUD natively supported in LuaJIT for a while. This fixes the issues described in #3563, please see this issue for details.
> [Fix] Remove aarch64 GC64 workaround

- src/lua/lua_mimepart.c
The fix can be tested e.g. on the sample _test/functional/messages/dmarc/good_dkim_spam.eml_
Before the fix:
> Results for file: test/functional/messages/dmarc/good_dkim_rspamd.eml (0.959 seconds)
> IO read error: unexpected EOF
After the fix:
> Results for file: test/functional/messages/dmarc/good_dkim_rspamd.eml (1.100 seconds)
> [Metric: default]
> Action: no action
> Spam: false
> Score: 0.80 / 10.00
> Symbol: ASN (0.00)[asn:24940, ipnet:88.99.0.0/16, country:DE]
> Symbol: BL_VFRBL_HWL (-1.00)[88.99.142.95:from]
> Symbol: DATE_IN_PAST (1.00)[25560]
> Symbol: DKIM_TRACE (0.00)[rspamd.com:+]
> Symbol: DMARC_NA (0.00)[rspamd.com]
> Symbol: FREEMAIL_ENVRCPT (0.00)[gmail.com]
> Symbol: FREEMAIL_TO (0.00)[gmail.com]
> Symbol: FROM_EQ_ENVFROM (0.00)
> Symbol: FROM_HAS_DN (0.00)
> Symbol: …
> [Fix] src/lua/lua_mimepart.c: fix null dereference

- src/controller.c
_Let me preface this PR by saying that I don't write C, so reviewers may wish to handle with care._
Per discussion in #3754 this PR makes the following changes:
- All metrics have `HELP` and `TYPE` defined (with varying usefulness of HELP, since some of the stats are non-obvious to me)
- Metrics are now successfully parsed as the specified `openmetrics-text` content-type (spurious spaces between labels were causing Prometheus to barf)
- Metrics are no longer interleaved for `statfiles_*`
- rspamd-specific metrics are prefixed with `rspamd_`
Some possibly contentious decisions:
1. Metrics that appear to me to be monotonically increasing values have been marked as `counter` type, and consequently have `_total` appended to their metric names. If these values are not in fact monotonically …
> [Fix] Namespace and add metadata for OpenMetrics, fix interleaving

- contrib/DEPENDENCY_INFO.md
This just bumps the version number of currently bundled doctest library in dependency info table.
> Reflect recent doctest version bump in dependency info table

- rules/bitcoin.lua
Exclude very long words (which can be extracted e. g. from some text
attachments) from bitcoin address check to avoid excessive resource
usage.
> [Minor]  Skip bitcoin address check for very long words

- src/client/rspamc.c
If request to `/counters` returns no symbols then `max_len` would have
a negative value which would cause a buffer overflow in `memset`:
```
Results for command: counters (0.003 seconds)
=================================================================
==22096==ERROR: AddressSanitizer: negative-size-param: (size=-2147483604)
#0 0x33ff13 in __asan_memset (/usr/bin/rspamc+0x33ff13)
#1 0x383432 in rspamc_counters_output /usr/src/debug/rspamd/src/client/rspamc.c:1064:2
#2 0x388c49 in rspamc_client_cb /usr/src/debug/rspamd/src/client/rspamc.c:1600:6
...
```
> [Fix] buffer overflow in rspamc counters

- lualib/lua_cfg_transform.lua
Defined actions without score are deactivated in sanity check (#3693)
> [Fix] lua_cfg_transform - actions without score (discard)

- lualib/lua_scanners/icap.lua
More complete ICAP implementation:
- Support REQ and HTTP encapsulated headers
- Support TLS
- Follow Connection header directives
- Analyse HTTP Return Headers (if no ICAP header was found)
Add Support for:
- McAfee Web Gateway 11
- Kaspersky Scan Engine 2.0 (you really should use http mode)
- Trend Micro Web Gateway
> lua_scanners/icap

- conf/modules.d/aws_s3.conf
- src/plugins/lua/aws_s3.lua
Allow for configurable s3 hosts.  Helpful for when users need to point to an s3 not associated with s3.amazon.com.  As an example, using tools such as [LocalStack](https://github.com/localstack/localstack), users can point to a mocked instance of s3 locally for testing without having to interact with a cloud service.
> [Config] Allow configurable s3 urls

- CMakeLists.txt
There are 2 major versions of the PCRE library, PCRE and PCRE2. Rspamd supports both and current default is the former. But according to the web page of PCRE library it has reached its end of life. So change the default to the latter.
> Enable PCRE2 by default.

- conf/maps.d/mime_types.inc
When I send PGP-signed mails with Roundcube and attach my PGP key the mail gets -0,1 spam points from rspamd because it is an unknown MIME type. 
I hope I found the code correctly so that the MIME type is known then. If not, I am happy if someone could correct my pr.
> Add application/pgp-keys to known mime types

- src/libserver/cfg_rcl.c
If enabled = false, then we should set RSPAMD_SYMBOL_FLAG_DISABLED.
Now setting enabled = true sets RSPAMD_SYMBOL_FLAG_DISABLED. Which is
incorrect.
> Fix disabling symbols

- conf/modules.d/rbl.conf
- conf/scores.d/surbl_group.conf
Fix the Spamhaus URIBL and uncomment but disable it.
This way it can be easily enabled in local.d without the need to copy
the whole block.
Symbols are also ignored as this will generate a warning otherwise.
> Uncomment but disable SpamHaus URIBL

- src/plugins/lua/clickhouse.lua
Fixes collect_garbadge table key usage as collect_garbage.
> Fix Typo at Settings Key

- .eslintrc.json
as Object.hasOwn(…) is not implemented in Pale Moon.
> [Test]  Disable prefer-object-has-own ESLint rule

- conf/scores.d/rbl_group.conf
Assign a weight to the MAILSPIKE whitelist RBL symbols.
Use the same but negative weight as its blacklist counterparts.
Also fix some indents in the file
> Assign weights to Mailspike Whitelists

- conf/modules.d/mime_types.conf
Some mails were marked as
MIME_BAD_ATTACHMENT (4) [pdf:application/x-pdf]
application/x-pdf might be obsolete but still used.
> Map application/x-pdf to pdf

- lualib/lua_dkim_tools.lua
- src/plugins/lua/arc.lua
The whitelisted_signers_map defined [here](https://github.com/rspamd/rspamd/blob/master/src/plugins/lua/arc.lua#L418) is getting overwritten by [`dkim_sign_tools.process_signing_settings(N, settings, opts)`](https://github.com/rspamd/rspamd/blob/master/src/plugins/lua/arc.lua#L418). As a result the `trusted_allow` symbol is never inserted. Rspamd logs the following error:
```
2021-12-23 21:49:17 #16197(normal) <c9818c>; task; dkim_module_lua_push_verify_result: call to verify callback failed: /usr/share/rspamd/plugins/arc.lua:236: attempt to index field 'whitelisted_signers_map' (a nil value)
```
I suggest that we move the `map_add` to the [`process_signing_settings` function in lua_dkim_tools.lua](https://github.com/rspamd/rspamd/blob/e2c9ea10a36bd2f48d4570123062d8af6dffc513/lualib/lua_dk …
> [Fix] Avoid overwriting whitelisted_signers_map

- src/plugins/lua/metadata_exporter.lua
I think its quite common to not export soft rejects via the metadata
exporter. Because when its not spam, the sender will most likely try to
redeliver it again anyway.
> [Minor] Add no soft reject selector for metadata exporter

- contrib/librdns/compression.c
- contrib/librdns/compression.h
- contrib/librdns/dns_private.h
- contrib/librdns/rdns.h
- contrib/librdns/rdns_ev.h
- contrib/librdns/rdns_event.h
- contrib/librdns/resolver.c
- contrib/librdns/util.c
- contrib/librdns/util.h
This is a rework of RDNS library that allows to re-send truncated UDP requests over TCP channels. TCP channels are maintained in a way described in [RFC7766](https://datatracker.ietf.org/doc/html/rfc7766), meaning that RDNS will re-use TCP connections for as many requests as it can but it will reap idle connections out. Rspamd will also create a single TCP connection to a DNS server per process. This change allows to parse very large replies from brain-damaged domain owners, see #4012 for more details.
> Rdns tcp rework

- src/hs_helper.c
- src/libserver/cfg_utils.c
- src/libserver/maps/map_helpers.c
Tested in alpine ci: https://gitlab.alpinelinux.org/a16bitsysop/aports/-/jobs/605308
With tests passing.
> [Feature] Allow hyperscan for ppc64, as vectorscan now suports it.

- src/libserver/cfg_utils.c
- src/libserver/rspamd_symcache.c
- src/libserver/rspamd_symcache.h
- src/lua/lua_config.c
- src/rspamadm/configdump.c
Details of changes included in this pull request:
- symbol score defined in a conf file, but no description provided in the conf file (as is done in `scores.d/headers_group.conf`)
For example, symbols where scores are defined or one_shot is changed in `local.d/headers_groups.conf,` and no description is provided, use the description from lua. If the description is provided in both, the one from the config file is used.  This eliminates the need to replicate a description between config file and lua.
See changes in `src/lua/lua_config.c`
* Properly group symbols that start out “ungrouped” when another group is later defined.
If a symbol is scored separately in a conf file and that conf file does not include a group definition, the symbol starts out ungrouped.  When the regex config, for …
> rspamadm configdump: parsing fixes and output enhancements

- conf/modules.d/rbl.conf
On https://www.spamhaus.org/dbl/, Spamhaus explicitly recommends doing so:
> It is effective for filtering email during the SMTP session for all header domain checks - rDNS, HELO, MAIL FROM, From, Reply-To, and Message-ID domains - as well as URLs in messages.
In several productive environments, this was found to pose a small, but noticeable improvement to spam detection rates. Therefore, it makes sense to bring this change upstream IMHO.
> [Enhancement] Query HELOs, PTRs, and Reply-To's against Spamhaus DBL as well

- conf/composites.conf
There is no R_DKIM_DNSFAIL symbol (in default config), but there is R_DKIM_TEMPFAIL.
> [Rules] Fix symbol for DKIM temporary failure

- lualib/lua_util.lua
- test/lua/unit/lua_util.misc.lua
Use find to check string suffix instead of sub (which involves string
interning of a returned string).  Benchmarks with LuaJIT 2.1.0 shows
that an option with find is significantly faster.
While here added a unit test for this function.
Was tested using LuaJIT 2.1.0-beta3 and a following code snippet:
```
local util = require 'rspamd_util'
local lua_util = require 'lua_util'
local suffix = 'beef'
local c = 0
for i=1, 1e8 do
local str = util.random_hex(16)
if lua_util.str_endswith_sub(str, suffix) then
c = c + 1
end
end
```
Results (CPU time for the code above):
```
x sub
+ find
+------------------------------------------------------------------------------+
|         +                                                         x     xx   |
|+   + +  +++++ + …
```
> [Minor] Microoptimize lua_util.str_endswith

- src/libutil/cxx/local_shared_ptr.hxx
gcc 8.5 doesn't compile this file without template parameters for ptr_and_refcnt constructor.
> make gcc 8.5 happy

- test/rspamd_test_suite.c
The dangling comment is result of commit bfe48b659baf - `[Fix] Fix logging for rspamadm`, where the same comment was removed from `rspamadm` but this one stayed. It should be removed as well.
> Remove dangling comment

- src/libserver/cfg_utils.c
`ZSTD_reset{C,D}Stream` functions are deprecated since 1.4.0 version. This change migrates them to new equivalents as described in documentation.
> Migrate ZSTD_reset{C,D}Stream to a new API

- conf/modules.d/rbl.conf
While `blocklist.de`'s web site shows hits for IPv6 addresses, their RBL server network does not seem to serve IPv6 queries. To avoid unnecessary DNS lookups, IPv6 can be disabled for `blocklist.de` for now without losing any information.
> [Fix] Disable IPv6 lookups for Blocklist.de RBL

- conf/modules.d/rbl.conf
Due to [this line](https://github.com/rspamd/rspamd/blob/master/conf/modules.d/rbl.conf#L16) in the RBL module default configuration file, mails from authenticated users are not subject to any DNSBL lookups. This certainly makes sense for RBLs (i. e. IP-based DNSBLs), but in order to improve detection on outbound spam, URIBLs should be enabled for authenticated users too, so `rspamd` will notice if a compromised account starts emitting mails containing known bad FQDNs.
Therefore, this patch enables URIBL lookups against SURBL, URIBL, Spamhaus DBL and `rspamd.com`'s DBL for authenticated users. Hopefully it helps reducing the amount of spam sent out though cracked accounts a bit. :-)
> [Fix] Do not exclude authenticated users from URIBL lookups

- conf/scores.d/rbl_group.conf
While I assume most `rspamd` users will take advantage of [force actions](https://rspamd.com/doc/modules/force_actions.html) for symbols like this to make the rejection behaviour of their infrastructure deterministic and enforce their AUPs, I found the score of 2.0 points to be too low in environments not using force actions.
Besides, according to its [homepage](https://www.spamhaus.org/sbl/), the SBL is described as "a database of IP addresses from which Spamhaus does not recommend the acceptance of electronic mail". `rspamd` already features the XBL with 4.0 points (3.0 for deep header parsing), so I guess there is no sense in scoring the SBL lower than the XBL.
> [Enhancement] Adjust scores of Spamhaus SBL hits

- conf/modules.d/rbl.conf
In several environments, querying HELOs, PTRs, and Reply-To's against SURBL and URIBL as well was found to increase the spam detection rates notably, particularly if spam or phishing messages were directly sent from compromised webservers (SURBL seems to have a good coverage of these). No false positives were detected related to this over the period of several weeks.
Also, this will increase the number of DNS queries made per message by 6 at the most (contrary to checks like URL and DKIM, which might pile up to tenths of lookups), so I guess it is not an inappropriate suggestion for `rspamd`s default configuration.
(See also: https://github.com/rspamd/rspamd/pull/4052)
> [Enhancement] Query HELOs, PTRs, and Reply-To's against SURBL and URIBL as well

- conf/modules.d/rbl.conf
Giving these a closer look, I think it makes sense to conduct EBL queries for mails submitted by authenticated users as well:
- Might catch some BEC, e. g. if a user fell for a previously accepted phish mail, and is now replying to the phisher
- Might catch spam/phishing from a compromised account, where the `Reply-To` address is already known to be bad
> [Minor] Query EBLs for authenticated users as well

- lualib/lua_selectors/transforms.lua
- test/lua/unit/selectors.lua
Now, lower transformation uses default lower function and doesn't work with utf symbols as expected. Test case:
multimap.conf:
```
bl_test_subj {
map = "${CONFDIR}/maps/bl-test.map";
type = "selector";
selector = "header('Subject').lower";
score = 0.0;
symbol = "BL_TEST";
}
```
/etc/rspamd/maps/bl-test.map
```
тест
```
```bash
$ echo test | mail -s "Тест" XXX@XXX:
multimap.lua:437: check value Тест for multimap BL_TEST
multimap.lua:476: found return "false" for multimap BL_TEST
$ echo test | mail -s "тест" XXX@XXX:
multimap.lua:437: check value тест for multimap BL_TEST
multimap.lua:476: found return "" for multimap BL_TEST
```
But there is rspamd_text:lower method that works with utf symbols. With this patch, it works as expected:
```bash
$ echo test | mail -s "Тест" XXX@XXX: …
```
> [Minor] fix lower transformation for utf symbols

- centos/rspamd.spec
The build on Fedora 36 is failing due to [a bug in ld.gold](https://bugzilla.redhat.com/show_bug.cgi?id=2043178) that prevents successful linking.
The recommended work around is to use ld.bfd instead.
I've also tried [ld.mold](https://github.com/rui314/mold) which works as well, but I was unsure of the stance on adding another build time dependency.
With this I was able to build and run test rspamd on el7, el8, el9 as well as Fedora 34, 35 and 36.
> Update rspamd.spec to fix Fedora 36 build

- src/client/rspamc.cxx
Lists and dictionaries can be added to the protocol response inside `messages`, e.g.
```
task:append_message({foo = 'bar'}, 'yolo')
task:append_message({'bar','foo'}, 'swag')
```
Currently this is causing a crash in `rspamc`.
```
(gdb) p ucl_object_tostring(cmesg)
$3 = 0x0
```
This doesn't look quite as I might have imagined it but it's better than crashing:
```
Message - yolo: object
Message - swag: array
```
> [Minor] rspamc: fix crash on non-string element in `messages`

- lualib/lua_mime.lua
Populated envelopes are objects, but empty envelopes are arrays. This greatly complicates decoding in strictly typed languages as we are no longer able to map onto a typed schema. Examples below are in json, but this also affects messagepack.
```
{
"parts": [
{
"content": "Very simple, ok, lovely\r\n",
"size": 25,
"type": "text/plain",
"detected_type": "text/plain",
"headers": []
}
],
"newlines": "crlf",
"digest": "18e1406d9bb715b849d8339718d6475f",
"envelope": [],
```
```
{
"parts": [
{
"content": "Very simple, ok, lovely\r\n",
"size": 25,
"type": "text/plain",
"detected_type": "text/plain",
"headers": []
}
],
"newlines": "crlf",
"digest": "18e1406d9bb715b849d8339718d6475f",
...
```
```
{
"newlines": "crlf",
"digest": "b0cf8c13097e67c53a7c7bf1e4e5f720",
"envelope": {
"from_smtp": { …
```
> [Fix] Empty envelopes should not be emitted as arrays, drop from schema instead

- lualib/rspamadm/mime.lua
Add the ability to write to a specified directory instead of stdout
Add the ability to split contents out into files, when output directory is specified (-o) and formatting is performed (--json/--messagepack etc)
This is a rework of https://github.com/rspamd/rspamd/pull/4203
```
rspamadm mime dump ./samples/very_simple.eml
```
```
rspamadm mime dump ./samples/very_simple.eml ./samples/Zipfile_test.eml
```
```
rspamadm mime dump --json ./samples/very_simple.eml ./samples/Zipfile_test.eml
rspamadm mime dump --messagepack ./samples/very_simple.eml ./samples/Zipfile_test.eml
```
```
rspamadm mime dump -o /tmp --json ./samples/very_simple.eml ./samples/Zipfile_test.eml
rspamadm mime dump -o /tmp/ --messagepack ./samples/very_simple.eml ./samples/Zipfile_test.eml
```
```
rspamadm mime dump -o …
```
> [Minor] Mimedump improvements

- lualib/rspamadm/dmarc_report.lua
Skip sending DMARC reports if the `-n` / `--no-opt` option is set
fixes https://github.com/rspamd/rspamd/issues/4241
> [Fix] Skip sending dmarc reports in no-opt mode

- conf/composites.conf
When a message is classified as spam by the bayes classifier, the ```BAD_REP_POLICIES``` symbol does not trigger, even though it says in its description that it should. This is because the expression for the symbol contains a reference to a non-existing group "bayes", while the actual group is called "statistics". Proposing a change to fix this.
> Fix: BAD_REP_POLICIES does not trigger for Bayes

- lualib/lua_mime.lua
- src/libserver/milter.c
- src/plugins/lua/milter_headers.lua
* `lualib/lua_mime.lua`: `modify_headers()` did not handle header altration properly.
* `libserver/milter.c`: `rspamd_milter_extract_single_header()` inserted the headers with the `order` _less than_ `-1` at unintuitive position.
* `plugins/lua/milter_headers.lua`: `default_headers_order` was not always used as default order; local function `add_header()` could be simplified.
Test cases are attached (note that the results of some test cases are fluctuating):
[rspamd.tests.tar.gz](https://github.com/rspamd/rspamd/files/9475300/rspamd.tests.tar.gz)
> milter_headers: Header fields may be inserted at wrong position.

- contrib/elastic/rspamd_template.json
- src/plugins/lua/elastic.lua
This PR provides a fix for:
1. Not override IP with a user-supplied header
2. DoS in writing logs to Elastic which external sender can exploit. IP validation in Elastic is stricter than in Rspamd, so the user can supply data that looks for Rspamd as valid IP, f.e.: `.23.24.1`, but fail to pass validation on Elastic side. Now basic string is used which should not result in such errors
> [Fix] Avoid overriding IP with Sender IP

- src/fuzzy_storage.c
- src/libutil/addr.c
This aims to fix https://github.com/rspamd/rspamd/issues/4278
The first action is to bind a DGRAM unix client-socket to an anonymous abstract socket.
This is a special case, as documented on man 7 unix: If the address length is sizeof(sa_family_t), it will automatically assign an abstract free for use address for the socket.
Thus, the server has some address to reply to.
This uncovered a few further issues:
rspamd_inet_address_from_sa was not prepared for such addresses.
For one, they can be very short, so the default length check failed.
Then they do contain a null byte in the string, so any strlen/cpy functions will fail. Instead just memcpy the whole struct with the given slen.
Additionally, the allow_update check in the fuzzy worker makes no sense for unix sockets, since there isn't …
> Allow fuzzy worker to listen on AF_UNIX sockets successfully

- src/plugins/lua/metadata_exporter.lua
Hello and many thanks for this great software :)
This commit fix sending mail alert with backend "send_mail" and many recipients.
Config I use :
```
rules {
SEND_ALERT_ON_SPAM {
selector = "is_spam";  
backend = "send_mail";  
smtp = "smtp.example.org";  
smtp_port = 25;  
helo = "localhost.example.intra";  
mail_to = ["recipent1@example.org","recipient2@example.org"];  
mail_from = "rspamd@example.org";  
formatter = "email_alert";  
}  
```
Without this fix, mail is never sent, sendmail_cb is never called.
> Fix metadata_exporter with many recipients

- src/plugins/lua/metadata_exporter.lua
Hello,
I found that specifying credentials in "url" key in metadata_exporter rule definition seems not supported :
```
url = http://upload:upload123@server.example.intra:8080/upload;
```
Although this method is working well in http map declarations.
So this commit add basic authentication, with new "user" and "password" keys in rule definition :
```
LOG_SPAM_TO_HTTP {
backend = "http";
selector = "is_spam";
url = http://server.example.intra:8080/upload;
user = "upload";
password = "upload123";
meta_headers = true;
}
```
> Add basic auth to metadata_exporter http pusher

- conf/composites.conf
This composite rule has been in use for quite a while in various rspamd setups. Since messages originating from freemail providers tend to have more signs of positive reputation, thanks to IP-/DKIM-/FQDN-reputation tracking, I found the existing symbols, such as `R_UNDISC_RCPT` insufficient to push advance free fraud (AFF) messages "over the edge".
Therefore, this composite rule puts additional weight on messages exhibiting strong AFF patterns, and involve freemail addresses, such as the plethora of such mails emitted by GMail, in the hope to gain better catch rates on these.
> [Enhancement] Add composite rule against AFF involving freemailers

- conf/composites.conf
This PR includes two changes.
1. It suggests a default rule to include a penalty for bounce messages with AUTH_NA to protect against fake bounce messages (bounce spam).
2. It adds AUTH_NA_OR_FAIL, because when e.g. R_DKIM_PERMFAIL is included R_DKIM_NA does apply anymore and AUTH_NA is not added. This creates an opportunity to willingly create a R_DKIM_PERMFAIL by a spammer.
> Penalize bounce spam

- test/lua/unit/lua_util.extract_specific_urls.lua
Removed test case does not work with luajit-2.1 anymore as it depends on internal behavior of lujait-2.0.
The order of URL list returned by `extract_specific_urls` function from `lualib/lua_util` depends on order of keys in table of TLDs.  The test case incorrectly expects "net" and "com" being in front of the table, however, "org" can appear there as well.
---
I have found this issue when I was trying rspamd `3.4`, however, it affects older versions as well. The error output looks like this:
```
------------------------------------------------------------------------
Lua util - extract_specific_urls plain:                              
extract_specific_urls, backward compatibility case #1                [F]
extract_specific_urls 1                                              [F] …
```
> [Test] Remove test case with non-deterministic result

- src/plugins/lua/antivirus.lua
Hi, I hope it could be useful to have mime_parts_filter_regex mime_parts_filter_ext filters as in the _External services_ module.
> [Feature] Enable Mime part filters on antivirus module

- src/libutil/cxx/file_util.cxx
- test/lua/unit/sqlite3.lua
Couple of tests were designed to use hardcoded `/tmp` directory, which could be problematic in some cases. For example, in case of sqlite3 related tests, multiple users cannot run it in parallel. Additionally some leftovers remain in `/tmp` directory after this test, `*.sqlite-shm` and `*.sqlite-wal` files, which was actually main motivation for me to create this PR.
From perspective of Gentoo packager `$TMPDIR` is set for the package to a safe place controlled by a package manager, which is automatically cleaned when something remains there. Moreover, I can run tests for multiple versions in parallel without risk of file collision.
> [Test] Use TMPDIR if available

- lualib/lua_maps.lua
- src/libserver/http/http_connection.c
- src/libserver/http/http_message.c
- src/libserver/http/http_message.h
- src/libserver/hyperscan_tools.cxx
- src/libserver/url.c
- test/functional/cases/001_merged/101_lua.robot
- test/functional/cases/001_merged/__init__.robot
- test/functional/cases/230_tcp.robot
- test/functional/lua/maps_kv.lua
- test/functional/util/dummy_http.py
The idea is to extend the existing maps functionality by allowing them to query external resources via HTTP(s).
Here is a sample configuration:
```
map = {
external = true;
backend = "https://example.com/${domain}";
method = "form"; # or header, or body, or query
encode = "json"; # or message-pack, or form-encode
}
```
So when a module requires some key from a map, it can pass some additional callback to be called upon query. This allows to do an async call and return back at some point.
TODO list:
> Support external maps in Rspamd

- src/lua/lua_task.c
`has_urls(true)` returns false if only email addresses are present in an email. It should instead return true and this is a fix for it.
> [Fix] Return true from has_urls(true) if only emails are present

- src/plugins/lua/phishing.lua
The syntax of the strict_domains is broken since parsing for it was removed in commit ce21f8fe16a45a5a409d3c9f8217eba2de1fbe14 As this can be done with the exception mapping, we can safely remove it.
> [Fix] Replace broken strict_domains with phishing_exceptions

- src/libserver/css/css_tokeniser.hxx
- src/libserver/html/html_tag.hxx
Like other versions before, gcc 13 moved some includes around and as a result <cstdint> is no longer transitively included. Explicitly include it for uint8_t.
> Fix build with gcc 13 by including <cstdint>

- src/client/rspamc.cxx
"is string long enough?" check is not required because "reached EOL?" condition takes care of that too.
> rspamc: optimize indentation condition

- src/client/rspamc.cxx
In human report (rspamc -R option) when message is detected as SPAM, it means that message score is greater than or equal to the **add header** threshold but it may not  be greater than or equal to **reject score**.
For example we get output like this in human report:
Content analysis details:   (6.62 points, 15.00 required)
This creates a confusion that message score was low (6.62 is less than 15) and yet it was detected as SPAM. But actually message was detected as SPAM because its score was more than 6 (the add header score).
So this PR fixes this in human report. i.e. it prints add header score as required score instead of reject score as required score.
New output will be like this:
Content analysis details:   (6.62 points, 6.00 required)
Additionally, after a new "thresholds" object …
> Set required_score = reject score and minor change to the report

- conf/modules.d/arc.conf
rename symbol_sign -> sign_symbol
> conf/modules.d/arc.conf: fix parameter name

- lualib/lua_maps.lua
- rules/rspamd.lua
- src/plugins/lua/settings.lua
The support for the global maps in user settings is currently broken.
With the proposed patches the following sample configuration now works perfectly:
```
lua_maps {
trusted_networks {
type = "radix";
url = "/path/to/trusted_networks"
}
}
```
```
already_processed {
id = "skip_checks";
ip = "map:trusted_networks";
#header = {
#}
want_spam = yes;
}
```
See also [#1802](https://github.com/rspamd/rspamd/issues/1802).
> Fixes to support global lua maps in user settings

- rules/regexp/headers.lua
Both rules frequently trigger in spam messages, and seem to do their job quite well, without causing any harm to legitimate mails. Therefore, this patch suggests to raise their score to 1.0 each, and retag them to the `url` group rather than `experimental`.
While the `googleusercontent.com` rule is complete, the `HAS_GOOGLE_REDIR` one could be bypassed by using a different Google domain, e.g. google.at - is there an easy way to write a rule triggering on any `google.[TLD]` FQDN? If so, that might be a potential enhancement as well.
> [Enhancement] Make Google URL redirection rules productive

- rules/regexp/headers.lua
See <https://github.com/Betterbird/thunderbird-patches/issues/125> for reference.
This way, Rspamd will not add `FORGED_MUA_MOZILLA_MAIL_MSGID_UNKNOWN` to mails sent perfectly fine with Betterbird.
_Betterbird_ (<https://www.betterbird.eu/>) is an adjusted version of Thunderbird, fixing many bugs and adding long-wanted features. It is a common and well-known alternative to Thunderbird, so I think the addition is justified.
> addition: add Betterbird to `user_agent_thunderbird`

- conf/modules.d/bimi.conf
Looks like bimi.conf was copied from asn.conf. This fixes those references.
> fix incorrect asn references in bimi.conf

- src/plugins/lua/milter_headers.lua
When metric action is not defined, it reads a score causing a type error where the value should be a string and the actual action.
As a side note, the documentation for this module seems fairly out of date.
> Fix for x-rspamd-action in Milter headers module

- lualib/redis_scripts/ratelimit_check.lua
Before this commit, rspamd would consider the number of recipients of the current message twice when calculating the ratelimit condition.
> fix: avoid double-dip of nrcpt when calculating ratelimit condition

- conf/composites.conf
This composite rule is an attempt to improve detection rates on some recently observed spearphishing e-mails, which only contained a redirector URL, presumably to thwart Bayes and Fuzzy checks.
> [Enhancement] Add composite rule for messages only containing a redirector URL

- src/plugins/lua/mime_types.lua
These are as follows:
- `hta` (Windows HTML program)
- `asx` (Windows Advanced Stream Redirector)
- `sfx` (self-extracting Zip archive)
- `vst` (Visio Template)
- `vss` (Visio Stencil)
> [Minor] Add additional bad extensions

- conf/composites.conf
This merge request introduces a new composite rule for catching malspam disseminated by Qakbot, SquirrelWaffle and alike threat actors. Recent campaigns often involved compromised account at legitimate mailservers, through which e-mails were sent to potential victims, quoting previous conversation to improve credibility.
Such fake replies, in combination with an authenticated SMTP hand-off, and an IP address in the `Received` headers that is either not a dial-up one (i.e. no PBL listing, as the injector systems are predominantly located in datacenters), or already known for being compromised (XBL listing) or having an otherwise ill reputation (SBL listing), are now additionally scored by `THREAD_HIJACKING_FROM_INJECTOR`.
In addition, `RCVD_UNAUTH_PBL` was dependent on a symbol no longer …
> [Rules] Add thread hijacking composite rule

- rules/regexp/misc.lua
Having not seen this rule causing any false-positives during a long time, I think it is time to move it to the regular "url" group.
> [Minor] Move HAS_ONION_URI from "experimental" to "url" group

- rules/regexp/headers.lua
Having seen a slew of malspam and phishing e-mails leveraging Google Firebase recently (particularly in combination with AppSpot URLs), turning this rule productive strikes me as sensible.
> [Enhancement] Make Google Firebase rule productive

- lualib/lua_magic/types.lua
Before this change:
```
jst@localhost:~/source/repos/rspamd-mta-src$ sudo docker exec -it 9a /bin/sh
/etc/rspamd # rspamadm mime dump --json /eml/4Qf5RZ5LF5z2DJl-wr967dushxqxsexgn4ksu85zyd.eml | grep x-7z-compressed
"detected_type": "x-7z-compressed/",
/etc/rspamd # 
```
After the change:
```
jst@localhost:~/source/repos/rspamd-mta-src$ sudo docker exec -it d4 /bin/sh
/etc/rspamd # rspamadm mime dump --json /eml/4Qf5RZ5LF5z2DJl-wr967dushxqxsexgn4ksu85zyd.eml | grep x-7z-compressed
"detected_type": "application/x-7z-compressed",
/etc/rspamd # 
```
As per https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types I believe the previous behavior was wrong.
> Use the correct mime format for 7z

- rules/regexp/headers.lua
The list is derived from Firefox' static HPKP entires, retrieved from [this location](https://searchfox.org/mozilla-central/source/security/manager/ssl/StaticHPKPins.h). While the regular expression is rather complex to read, I lack ideas on how to improve its readability - suggestions welcome!
> [Enhancement] Improve detection of Google redirection URLs

- conf/composites.conf
- rules/regexp/headers.lua
Both Apple Mail and Apple iOS Mail always use `Mime-Version` instead of `MIME-Version` leading to `MV_CASE`, so it need to be excluded for them. Specifically Apple iOS Mail not add `plain-text` version of email leading to `MIME_MA_MISSING_TEXT` which need to be excluded as well. 
Note about `plain-text`: it will be added by Apple iOS Mail __only__ on replies, in the case when the email to which the reply is made has `plain-text` part. As such behavior can't be captured, we just can drop  `MIME_MA_MISSING_TEXT` generally for Apple iOS Mail
> [Feature] Detect Apple Mail and remove scores for their known common behavior

- src/libcryptobox/cryptobox.c
There's no need to use ECDSA_sign_setup/ECDSA_sign_ex separately, a single call to ECDSA_sign will handle everything that's needed here.
Avoids breakage with a soon-to-be-committed change to LibreSSL to remove ECDSA_sign_setup/ex from libcrypto.
Diff from @botovq
> replace ECDSA_sign_setup/ECDSA_sign_ex with ECDSA_sign

- lualib/plugins/dmarc.lua
The ABNF in https://www.rfc-editor.org/rfc/rfc7489#section-6.4 define that its allowed to have spaces before ";".
Normaly "v=DMARC1; ..." is used but we found an example with "v=DMARC1 ; ..."
> [Fix] dmarc gramar - allow spaces before ";"

- rules/regexp/headers.lua
Rationale: https://cofense.com/blog/google-amp-the-newest-of-evasive-phishing-tactic/
> [Minor] Tweak HAS_GOOGLE_REDIR to detect Google AMP URLs as well

- lualib/lua_redis.lua
- lualib/lua_util.lua
- src/plugins/lua/bimi.lua
- src/plugins/lua/history_redis.lua
- src/plugins/lua/reputation.lua
Attempt to fix https://github.com/rspamd/rspamd/issues/4318
This issue is still not fixed, at least for us (@ajs124 and me) so he asked me if i could look into it.
I think the problem is a misuse of the tableshape library, also see https://github.com/leafo/tableshape/issues/17
The rewritten code now merges tables rather than using on `extra_fileds` because looking at this source code all remaining keys, which includes `read_server`, `write_server` and `password` e.g. need to have the correct type specified in `extra_fields`, also see https://github.com/leafo/tableshape/blob/master/tableshape/init.lua#L1509-L1515
`password` being a string will then result in what ajs124 saw here: https://github.com/rspamd/rspamd/issues/4318#issuecomment-1453502529
There are two possible options on solving …
> fix: redis schema parsing

- interface/index.html
- interface/js/app/config.js
- interface/js/app/rspamd.js
> [WebUI] Restore contrasting foreground color

- src/plugins/lua/metadata_exporter.lua
This is for example useful with Graylog.
Although Graylog has various HTTP inputs, they are for GELF and others, which would need additional formatters on the `rspamd` side.
Using the raw input results in IO timeouts from the `rspamd` side, because Graylog's raw input doesn't "speak" HTTP.
This resolves the issue.  Combined with an appropriate Graylog pipeline to split into fields, this works well.
Example Graylog pipeline:
```
rule "JSON to fields"
when
starts_with(to_string($message.message), "{") && ends_with(to_string($message.message), "}")
then
let json = parse_json(to_string($message.message));
let map = to_map(json);
set_fields(map, "rspamd_");
set_field("rspamd_score", to_double(map.score));
end
```
> Add new exporter to push JSON to a raw TCP socket

- conf/modules.d/phishing.conf
- conf/scores.d/phishing_group.conf
- src/plugins/lua/phishing.lua
Currently, if you use `openfish`, `phishtank` or `generic_service` lists for checking URLs existing `exceptions` or `phishing_exceptions` not applied for them. This lists cover only logic for checking if URL just looks as phishing, but not excluding them from datafeed checks in mentioned services. This PR created a separate exclusion list for this case.
To economy compute units (and DNS requests in case of  `phishtank`) hosts from the exclusion list will be not checked, excluded symbol will be added even it not appear in  `openfish`, `phishtank` or `generic_service`.
> [Feature] Support feed exclusions in phishing module

- src/libserver/re_cache.c
Triggered by -DCMAKE_CXX_COMPILER=/usr/bin/clang++ -DENABLE_CLANG_PLUGIN=ON -DENABLE_HYPERSCAN=ON.
> [Fix] Correct format pattern for RE tree tempfile name

- src/libutil/mem_pool.c
- src/rspamadm/pw.c
- test/rspamd_mem_pool_test.c
- test/rspamd_radix_test.c
Reported by clang `-Wunused-variable`, ignoring contrib/*.
> [Minor] Remove unused variables

- src/libserver/worker_util.c
On x86_64 unw_word_t is uint64_t.
NOTE: Possibly incorrect for !x86_64.
Triggered by -DCMAKE_C_COMPILER=/usr/bin/clang -DCMAKE_CXX_COMPILER=/usr/bin/clang++ -DENABLE_CLANG_PLUGIN=ON -DENABLE_LIBUNWIND=ON.
> [Fix] Correct format string for unw_word_t

- lualib/rspamadm/mime.lua
Makes `rspamadm mime ex test.eml` work
> [Fix] rspamadm mime: arguments beginning with letter `t`

- lualib/lua_scanners/icap.lua
- src/plugins/lua/external_services.lua
It turns out, that external_services plugin is not submitting maybe_part parameter at all when calling icap services check method. In order to avoid expensive operations in icap.lua scanner, I am just getting the filename and content-type/subtype in the external_services plugin and submitting that as maybe_part parameter. Of course, a new parameter can be introduced should maybe_part is used, but I wasn't able to find any usage of it at least related to the ICAP functionality.
> [Feature] Add ICAP Content-Type and Filename from TODO List

- lualib/lua_scanners/icap.lua
Re-arrange the Date: header to be in appropriate order and conform to RFC. Otherwise, the functionality for populating filename, client_ip, content type and sub_type is not working as expected.
> [Fix] Change Date: header location to conform with RFC

- src/plugins/lua/mime_types.lua
Rationale: https://arstechnica.com/information-technology/2023/10/one-click-remote-code-exploit-in-cd-cue-files-affects-most-gnome-based-linux-distros/
> [Minor] Treat *.cue attachments as harmful

- src/libmime/mime_string.hxx
- src/libstat/backends/http_backend.cxx
This commit addresses a compilation issue when using GCC 14. According to [GCC 14's porting guide](https://gcc.gnu.org/gcc-14/porting_to.html), some C++ Standard Library headers no longer include other headers they used to use internally. Specifically, <algorithm> must now be explicitly included.
The issue was first reported in [Gentoo Bug 916438](https://bugs.gentoo.org/916438)
> [Minor] Add missing <algorithm> include for gcc 14

- rules/regexp/headers.lua
The absence of both headers is neither good nor bad, but having a dedicated symbol for that might aid neural network training.
> [Minor] Add rule for messages missing both X-Mailer and User-Agent header

- conf/composites.conf
This rule aims at improving rspamd's catch rates for messages already exhibiting indicators of spam, containing often abused services such as redirectors. With regards to the latter, it's presence currently (and, IMO, rightly) receives +/- 0 points, but in conjunction with a message that is likely spam, redirector usage is suspicions.
> [Enhancement] Add composite rule for suspicious URLs in suspicious messages

- src/libserver/logger/logger.c
The logging code contains one place where the apparent size of the logging structure is defined and then it's actually utilized in another place. Re-writes and refactoring this code ended up with these values to not co-relate what was previously there resulting in a stack overwrite in last version or currently in log truncation.
Move assignment of logging structure to the place where it's actually used, reducing future logic de-sync dangers. Also move the g_assert() to the end as it should be a development aid only.
> [CritFix] - Fix reported length of logging structure

- lualib/plugins/rbl.lua
#4741
Try harder to identify unambiguous Lua patterns (maybe there's no need to worry so much about ambiguity in fact).
Also shout louder about auto-correction: user may have intended regex or just have no idea about the matter on hand.
> [Minor] rbl: try harder to identify lua patterns

- src/plugins/lua/ratelimit.lua
I suppose probably it should be so; this needs documentation
> [Minor] ratelimit: make per-bucket symbol behave like global symbol

- src/plugins/lua/dmarc.lua
Existing possibility could be to disable DMARC completely for some particular recipients.
Suggested by @plinss in [#4515](https://github.com/rspamd/rspamd/issues/4515)
> [Feature] Support suppressing DMARC reporting for particular recipients

- src/plugins/lua/multimap.lua
Adjust behaviour of `rawtext` filter inline with documentation.
Reported by `George B` on Telegram.
> [Fix] multimap: rawtext: use decoded parts

- lualib/lua_maps.lua
Rspamd fails to start with lua 5-1 without this change.
Bug: https://bugs.gentoo.org/922522
Fixes: b189c9fea633 ("[Minor] lua_maps docs: apply formatting")
Fixes: https://github.com/rspamd/rspamd/issues/4784
> [Fix] Replace comment types

- src/plugins/lua/multimap.lua
Attribute name: `extract_from`. Possible values:
* `default` - try smtp, if not exists try mime
* `mime` - check mime only
* `smtp` - check smtp only
* `both` - try to match both
> [Feature] Add extraction type for `from` maps

- lualib/lua_verdict.lua
- src/plugins/lua/history_redis.lua
in the /history response since we have the `passthrough_module` key for that purpose.
While that might be handy in some situations,
mixing actions and module names is confusing in general.
> [Rework] Breaking: Do not report module as action

- conf/modules.d/history_redis.conf
- src/plugins/lua/history_redis.lua
We allow two things for now - `HOSTNAME` and `COMPRESS`. Hence, the default prefix will be the same, but the configuration default is now different to match the existing behaviour: `rs_history{{HOSTNAME}}{{COMPRESS}}`.
Issue: #4793
Closes: #4793
> [Feature] Allow to add templates to redis history prefix

- lualib/lua_bayes_redis.lua
- src/libstat/backends/redis_backend.cxx
`rspamadm mime stat` tries to init backends here and fails due to lack of the event loop. This fix set `ev_base` to `nil` and prevent periodics to be added.
> [Fix] Resolve issue with bayes stat in `rspamadm` mode

- CMakeLists.txt
- src/libmime/archives.c
Rspamd historically tried not to use heavy external dependencies and used some own code. Unfortunately, archives formats are now so complicated and it is much easier to use a robust library when the internal support is not enough. Libarchive seems to be a good option for that task, as it supports just files reading without decompression of everything.
> Support libarchive

- rules/regexp/headers.lua
These are frequently abused for distributing malware via non-HTTP protocols, such as public Samba servers. file:// URLs may also be abused for including files from the victims' machine in a message. Either way, a legitimate usecase is unlikely.
Unfortunately, I was not able to figure out how to include the URL(s) matched in rspamd's results. This applies to other rules in this file as well, such as `HAS_GOOGLE_REDIR` and `HAS_GOOGLE_FIREBASE_URL`: For forensic reasons, it might be useful to log the URLs these were triggering on.
Is this something that can be achieved easily?
> [Minor] Add HAS_FILE_URL rule for messages containing a file:// URL

- src/rspamd_proxy.c
Rspamd proxy worker does not update `nconns` variable so it fails to follow the general safe shutdown protocol, nor to report the number of the active connections. Issue: #4831
> Update `nconns` in proxy

- contrib/libucl/ucl_parser.c
- src/client/rspamdclient.c
- src/controller.c
- src/libserver/protocol.c
- src/libserver/protocol.h
- src/lua/lua_common.c
- src/rspamd_proxy.c
Rspamd currently sends reply in JSON format. However, message pack seems to be a better choice for a compatible client. It is faster and does not need escaping or even UTF8 validation. This is a surface for further updates.
> [Feature] Support reply in message pack format

- .github/workflows/ci_rspamd.yml
- src/libmime/lang_detection.c
- src/libmime/message.c
- src/libmime/mime_parser.c
- src/libserver/url.c
- src/libutil/multipattern.c
- src/libutil/multipattern.h
- src/lua/lua_trie.c
- src/lua/lua_util.c
- src/rspamadm/lua_repl.c
- test/functional/cases/150_rspamadm.robot
- test/functional/lib/rspamd.robot
- test/functional/lib/vars.py
There are some cases where we don't need to save Hyperscan patterns (e.g. for small patterns or when the configuration is not loaded). This fix should fix flaky tests eventually.
> Do not save multipatterns to FS in certain cases

- src/libmime/scan_result.c
- src/libmime/scan_result.h
- src/libserver/protocol.c
- src/libserver/task.c
Currently, `grow_factor` setting is totally bogus:
* It is increased with every symbol with positive score being added
* As symbols are added in undefined order, the weight of symbol X might be different depending if there were different amount of **other** symbols being inserted before
* Symbols with low score (like 0.01) are as significant in grow factor calculations as symbols with high scores
This PR fixes all the issues above. `grow_factor` is just a value that will be used to multiply weights of **all** positive score symbols after the postfilters phase. This factor will be calculated by checking each individual symbol contribution to the final result, so symbols with 1/2 of rejection (or any other highest score metric threshold) score will multiply grow_factor by `1.0 + …
> Rework grow factor

- src/plugins/lua/mime_types.lua
If we detected extension of the file and this extension is equal to the real extension then we should not pass second extension to check function as it will trigger false positive for MIME_DOUBLE_BAD_EXTENSION.
> [Enhancement] Exclude false positives of MIME_DOUBLE_BAD_EXTENSION

- lualib/lua_selectors/extractors.lua
Instead of extending the clickhouse `rspamd` table directly, this allows using `rspamd_hostname` as a selector with `extra_columns`, such as:
```lua
extra_columns = {
RspamdServer = {
selector = "rspamd_hostname";
type = "String";
}
}
```
> [Minor] Add selector to get rspamd_hostname

- lualib/redis_scripts/bayes_cache_learn.lua
- lualib/redis_scripts/bayes_learn.lua
- src/libstat/learn_cache/redis_cache.cxx
Relearning a message should have the same result as learning a message the first time. #4928, #3600
The following should have the same result:
- learn as spam
- learn as ham, then relearn as spam
The same should be true for the opposite direction:
- learn as ham
- learn as spam, then relearn as ham
With these changes, we were able to successfully relearn a message in both ways. The score always shows the same result, regardless of whether it is a relearn or first learn.
> [Fix] Relearn messages in bayes filter

- src/libstat/stat_process.c
If we disable one symbol in statfiles, we need to explicitly disable all other symbols for that classifier.
Issue: #4900
> Fix statfile symbols disabling

- rules/headers_checks.lua
Fix errors like:
```lua
task; lua_metric_symbol_callback: call to (CHECK_REPLYTO) failed (2): /usr/share/rspamd/rules/headers_checks.lua:257: attempt to index local 'to' (a nil value); trace: [1]:{/usr/share/rspamd/rules/headers_checks.lua:257 - <unknown> [Lua]};
```
> Fix error in headers_checks.lua

- src/libserver/rspamd_control.c
- src/libutil/libev_helper.c
In fact, we cannot send multiple commands and read them through the pipe. It has caused multiple weird issues in the past but I can now see clearly how it should be done. We should send commands and serialize all requests pending to let them being sent one by one, after reply for the previous command has been received.
> Serialize control commands

- src/libutil/libev_helper.c
- src/libutil/libev_helper.h
- src/plugins/fuzzy_check.c
We don't want to retransmits requests immediately as if we have some networking issues it won't help anything and will likely make troubles even worse.
The logic is to apply linear backpressure on each retransmit from 100 to 500ms.
> Implement backpressure for fuzzy check

- conf/composites.conf
This pull request aims at separating the composite logic for a suspicious origin from the rule actually scoring in case a message also carries signs of abuse. The goal of this is to allow for machine learning to pick up such nuances better, and to make the latter rule more flexible, since it is not limited to threat hijacking.
IPFS gateway URLs and `HTML_SHORT_LINK_IMG_1` have been added, since these are currently commonly seen in spam messages disseminated via compromised accounts.
As a minor detail, some missing groups have been added to existing composite rules.
> Rework composites for spam injected into compromised accounts

- src/lua/lua_util.c
For example, a subject header field with following content is determined to be all uppercase.
```
ツイスター、世界王者がAIロボットに完敗　得意技「関節外し」も及ばず
```
Ideographs and letters in unicase scripts which have Unicode general category `Lo` should be considered being not uppercase.
> [Fix] SUBJ_ALL_CAPS is overkill with some unicase scripts

- contrib/kann/kautodiff.c
- src/libserver/dkim.c
We want to reject signatures that do not cover enough of the body and some absurd values as well.
> Verify `l=` tag in DKIM signatures

- lualib/lua_scanners/common.lua
When AV Scanning is active, and the following settings are applied in the antivirus.conf:
scan_mime_parts = true;
scan_text_mime = true;
text_part_min_words = 1;
the Antivirus scan fails in the lualib/lua_scanners/common.lua file, because the get_words_count is called in the mimepart object (which does not implement the method) instead of the textpart.
With this fix the get_words_count is called on the correct object
this should really close #3503
> [FIX] call get_words_count method on the textpart in AV Scan

- src/controller.c
The helper text for rspamd_ham_total had `spam` instead of `ham` in the Prometheus output
> [Minor] Fix typo in Prometheus helper message for rspamd_ham_total

- src/plugins/lua/mime_types.lua
Rationale: https://dshield.org/diary/Files%20with%20TXZ%20extension%20used%20as%20malspam%20attachments/30958
> [Minor] Treat *.txz attachments as archives and harmful

- lualib/lua_mime.lua
Allow the user to specify `remove = null` as the way to not remove headers.
Avoid changing protocol response.
> [Feature] milter_headers: support not removing headers

- src/plugins/lua/arc.lua
> [FIX] Arc regex to no longer match on dmarc=

- lualib/lua_redis.lua
Initially, there was no way to recover from Redis errors that are temporary
by nature (e.g. when Redis was busy with loading database).
This PR adds logic to check returned reply and adds more fine-grained
errors-per-server handling.
> [Fix] Fix Redis scripts uploading when Redis is not ready

- conf/modules.d/once_received.conf
- conf/scores.d/headers_group.conf
- conf/scores.d/hfilter_group.conf
- rules/misc.lua
- src/plugins/lua/once_received.lua
Historically, it was done in `once_received` module, however, that check must
be done early, even before settings (as they could rely on hostname).
Hence, it was discussed to move this code to a separate rule.
> [Rework] Resolve rdns in a separate function

- src/plugins/lua/history_redis.lua
If somebody using docker with random hostname generation (or k8s deployment which by default pseudo-random for each new pod) with current default settings each recreation of docker container will create new hostname which lead in new and new list of rs_history, I think putting `expire = 432000;` which is 5 days will not hurt anyone, but will protect from totally uncleanable keys in such cases.
Expire will touch only that keys that was not updated over 5 days, so it really safe.
Update to documentation: https://github.com/rspamd/rspamd.com/pull/778/files - and I removed `key_prefix` from doc as it was obsolite and false statement.
> Set expiration for history_redis to 5 days by default

- conf/scores.d/surbl_group.conf
The ``URIBL_RED`` is automated, informative list, the ``URIBL_GREY`` is declared as "possible false positives"
> Update URIBL_RED/GREY scores

- src/libmime/lang_detection.c
- src/libserver/symcache/symcache_runtime.cxx
- src/libserver/symcache/symcache_runtime.hxx
We now do not skip pre/post filters even if the task result has reached
threshold.
> [Rework] Change the logic of skipping symbols

- lualib/plugins/dmarc.lua
Issue: #4906
According to [RFC7489 section 6.3](https://www.rfc-editor.org/rfc/rfc7489#section-6.3) and [RFC6376 section 3.2](https://www.rfc-editor.org/rfc/rfc6376.html#section-3.2), white space around tags is allowed.
But in particular, any white space after the "=" and any white space before the terminating ";" is not part of the value.
However, white space inside the value is significant.
This PR fixes the DMARC grammar to parse the values correctly.
> [Fix] Rework DMARC grammar to correctly handle spaces in values

- src/plugins/lua/dmarc.lua
This setting was never implemented but it was documented.
Reported in #5141
> [Feature] DMARC: Implement reporting.only_domains setting

- contrib/libucl/lua_ucl.c
The keylen variable used in `lua_ucl_newindex` function should use `size_t` type instead of `lua_Integer`, because all functions that use `keylen` expect it to be of `size_t` type. This mismatch leads to incompatible pointer types, and modern versions of GCC fail to compile the code.
Fixes: 9e87597ceb05 ("[Project] Allow manipulations with opaque UCL objects")
Closes: #5163
> [Fix] Use correct type for keylen in lua_ucl_newindex

- src/rspamd_proxy.c
This fixes #5178 by ensuring that only the parts of the string preceding the first null-byte are included in the `Log-Tag` header value.
> [Fix] Avoid null-bytes in Log-Tag header value

- src/libserver/ssl_util.c
- **[Minor] Remove bogus DEBIAN_BUILD constant**
- **[Minor] Use OSSL_PROVIDER_load on RHEL based distros**
- **[Fix] Load "default" provider as well as "legacy"**
> Some more fixes

- src/libserver/protocol.c
- src/rspamd_proxy.c
We provide a `/metrics` endpoint for controller, proxy and worker in open metrics format.
Openmetrics format demands that the end is signalled by the following marker "# EOF".
However we only send this marker for the controller metrics endpoint.
Scraping worker /metrics endpoint results in the following error message "data does not end with # EOF" and scraping fails.
This PR adds EOF marker for proxy and worker endpoint.
I tested this and after this change prometheus can successfully scrape the endpoint.
```text
...
rspamd_actions_total{type="soft reject"} 0
rspamd_actions_total{type="rewrite subject"} 0
rspamd_actions_total{type="add header"} 0
rspamd_actions_total{type="greylist"} 0
rspamd_actions_total{type="no action"} 1
```
> add EOF to openmetrics response in proxy and server

- ChangeLog
This seems to have fallen behind and I _use_ it when building a .deb package for Debian Sid.
I guessed at the categories.
> [Project] Keep Changelog updated

- src/ragel/smtp_addr_parser.rl
- test/lua/unit/smtp_addr.lua
Ragel still produces a wrong state machine if `const char *` is used
for characters representation that are actually utf8.
This PR changes all types to `unsigned char *` for consistency.
> [Fix] Another story about char sign

- conf/composites.conf
This "Mail message body" Content-Description header appears to be a common quirk of advance fee fraud e-mails leveraging freemail services.
> [Minor] Improve FREEMAIL_AFF catch rate

- src/libserver/spf.c
- src/libserver/spf.h
Rspamd could incorrectly resolve some records where additional DNS checks are initiated, e.g. for `mx` elements.
For each `mx` name Rspamd emits 2 DNS requests: A for IPv4 and AAAA for IPv6. Previously, it was possible to have an error in the situation where one of these requests was successful and another one is not. There was some protection against it but it was not sufficient at all.
This PR introduces subrequests count and trigger errors merely if all subrequests have failed. Similarly, if MX returns multiple names, and only some of them are resolvable it is still a case where we could actually resolve SPF element.
At the same time, I have added tracking count of all subrequests to ensure that we don't emit more DNS requests than allowed.
> [Fix] Fix dealing with happy eyeballs in SPF

- src/plugins/lua/rbl.lua
Some mail server (MTA) add a Received header with their own IP address to the message. For example:
```
Received: from neovet-base.ru (neovet-base.ru [82.202.243.114])
by mail.example.com (Postfix) with ESMTPS id 466F14034A
for <user@example.com>; Sun, 24 Nov 2024 00:12:24 +0300 (MSK)
Received: from neovet-base.ru ([82.202.243.114])
by neovet-base.ru with esmtpa (Exim 4.97.1)
(envelope-from <robot@neovet-base.ru>)
id 1tExQP-00000008rN5-017q
for user@example.com;
Sun, 24 Nov 2024 00:12:17 +0300
```
In this case IP address can be checked in some RBL twice,  first as From and then as Received ( for RBL that use `checks = ['received', 'from']`)
If sender IP is blacklisted, this will give the extra scores to email message:
```
Symbol: RBL_SPAMHAUS_SBL (4.00)[82.202.243.114:from]
Symbol: …
```
> [Fix] Skip extra RBL checks when Received IP same as From IP

- lualib/lua_scanners/cloudmark.lua
This fixes an issue where the cloudmark module does not correctly add connIp to the request. This prevents cloudmark from using the remote ip for white and blacklist checks.
> [Fix] connIp is not correctly added to request

- lualib/lua_scanners/cloudmark.lua
This is a minor and slightly subjective patch. We do a lot of log entries per day for mail and it's impossible to link a cloudmark analysis string to a specific email without the queue id. Trivial patch but would allow for better debugging of cloudmark specific problems, especially FP/FN remediation. The analysis strings are used to report issues with CM.
> [minor] log queue id with cloudmark analysis string

- src/plugins/lua/gpt.lua
GPT4All API is openai compatible but does not support response_format. The API does respond back as a json object with out sending response_format in the API request. This changes allows the ability to add
include_response_format = false;
In gpt.conf to suppress sending response_format which resolves the error:
gpt.lua:365: got reply: {"error":{"code":null,"message":"'response_format' is not supported","param":null,"type":"invalid_request_error"}}
The change defaults to response_format being with no setting set.
> Add ability to not send response_format in gpt plugin in order to support gpt4all

- rules/regexp/headers.lua
This small change fixes Thunderbird for Android being marked as `FORGED_MUA_THUNDERBIRD_MSGID_UNKNOWN` due to uppercase UUID format for message IDs.
Alternative would be overcomplicating the regular expression with a special exemption for Thunderbird for Android that only applies then.
> Fix Thunderbird for Android marked with FORGED_MUA_THUNDERBIRD_MSGID_UNKNOWN

- rules/regexp/headers.lua
Expand subject detection for fake replies by adding abbreviations from multiple languages: Dutch/German (Antw), Latvian/Welsh (ATB), German (AW), Indonesian (BLS), Polish (ODP), Portuguese (RES), Italian (RIF), Danish/Icelandic/Norwegian/Swedish (SV), and Turkish (YNT).
> [Enhancement] Expand Detection of Fake Reply Subjects Across Multiple Languages

- src/plugins/lua/elastic.lua
`h.decoded:sub(1, headers_text_ignore_above)` was leading to potential broken utf8 string as it had chance to strip line in the middle of utf8 character leading to errors like:
```
error while pushing logs to elastic, status: 400, type: mapper_parsing_exception, reason: failed to parse field [rspamd_meta.header_to] of type [text] in document with id 'X'. Preview of field's value: ''
```
also I added task digest
> fix: use sub_utf8 to strip headers value to not break utf8 strings

- interface/js/app/libft.js
Ensure the action dropdown resets to its default value when clearing filters in the history table.
> [WebUI] Reset dropdown when clearing filters

- src/libutil/mem_pool.c
- src/libutil/mem_pool_internal.h
I don't want to debug that again!
> [Fix] Avoid collision hacks in mempool variables hash

- utils/rspamd_stats.pl
The `rspamd_stats.pl` script complains about duplicate specification for some options:
```
Duplicate specification "symbol-bidir|S=s@" for option "s"
Duplicate specification "exclude-logs|x=i" for option "x"
Duplicate specification "json|j" for option "j"
```
This fixes those errors by:
* configuring Getopt with `no_ignore_case` to distinguish `symbol|s` from `symbol-bidir|S` and `exclude|X` from `exclude-logs|x`
* removing the short form `j` of `json` and configuring Getopt with `no_auto_abbrev` to prevent abbreviation
It is no longer possible to use `-j` for `--json` but I don't think this is a big change since `junk-score|j` was probably taking precedence before.
> Prevent option duplicates in rspamd_stats.pl

- lualib/plugins/neural.lua
- lualib/redis_scripts/neural_save_unlock.lua
This PR should solve issue that ham and spam sets are persist in redis indefinitely as well as fix small typo
> [Fix] Add expiration for neural ham and spam sets

- lualib/lua_maps.lua
- src/plugins/lua/settings.lua
Fix several small issues plus code improvements:
* Support `map://` prefix based on original intention (the check never worked because it was shadowed by the preceeding `map:` check)
* Avoid misleading "cannot parse ip" logging by checking for `map:` prefix early
* Do not use tables for maps or IPs without mask (store as strings)
* Normalize IPs by applying mask during processing (for example specifying `ip = "192.168.0.123/24"` would now work when matching against `192.168.0.123`)
* Add error logging for wrong IP mask
* Simplify `check_ip_settings()` based on changes in `process_ip_condition()`
* Skip invalid IPs (with appropriate error logging)
(previously a bad IP would cause the subsequent IPs in a list to be ignored or make the whole IP condition to be ignored)
* Add validated …
> Better support for maps and IP-related fixes/improvements in settings

- src/plugins/lua/gpt.lua
similar to gpt.lua:704 for the chatgpt code path, the ollama code path needs to initialize the result table. Without, rspamd fails gpt requests with
> lua_http_finish_handler: callback call failed: /usr/share/rspamd/plugins/gpt.lua:740: attempt to index a nil value
> [Fix] initialize ollama result table

- conf/modules.d/phishing.conf
- src/plugins/lua/phishing.lua
Update default URL - since we won't follow the redirect.
It looks more like an advertisement than a useful service to me.
Fixes issue #5261
> [Fix] Update default URL for openphish

- interface/js/app/config.js
- Prevent WebUI crash on `jar.destroy` when map query fails
- Do not open the map editor when map query fails
- Ensure proper cleanup of the editor modal
> [WebUI] Fix map editor modal handling

- conf/modules.d/contextal.conf
- lualib/lua_scanners/cloudmark.lua
- lualib/lua_util.lua
- src/plugins/lua/contextal.lua
Integrate with [Contextal Platform](https://platform.contextal.com/).
Yield symbols for Contextal's 'actions' tagged with the 'scenario' names, allow those to be used with composites or `force_actions`.
Optionally use Redis for caching.
TODO:
> [Feature] Plugin to integrate with Contextal platform

- rules/regexp/headers.lua
This symbol will detect if header from contains any URLs and if yes - will add negative score to email. Usually such cases has place when bots spam "contact us" forms on websites and website use "From" as visible part of from in email. Rspamd do not verify URLs in From header, so we can restrict them via this rule as is.
Instead of https://github.com/rspamd/rspamd/pull/5405
> Add R_HTTP_URL_IN_FROM

- src/plugins/fuzzy_check.c
- test/functional/cases/120_fuzzy/lib.robot
- test/functional/cases/120_fuzzy/read-only.robot
- test/functional/cases/120_fuzzy/split-servers.robot
- test/functional/cases/120_fuzzy/write-only.robot
- test/functional/configs/fuzzy-split-servers.conf
- **[Feature] Add support for separate read and write servers in fuzzy check**
- **[Minor] Remove servers completely and use `read_servers` for all compat stuff**
- **test: add fuzzy tests for split, read-only, and write-only server modes**
- **[Test] Improve fuzzy split server test configuration and setup**
- **[Minor] Some fixes**
> Allow to use different servers for fuzzy operations

- contrib/librdns/dns_private.h
This change required to fix cases when Rspamd tries to query domain that exceed IDNA2008 limits of 255 chars, but practical limit is 253 due to last 2 chars is `.` and `null separator`.
Whenever Rspamd tries to query such DNS record it will always face `query timeout`, so there no reason to create such requests at all.
Mostly such cases could be seen in RBL where no hashing is applied on query selector like `{from}.{primary_rcpt}.{rbl}` or so on.
P.s. changes to the limit double checked with RFCs and `dig`
> Fix librdns maxname limit

- src/libmime/mime_string.hxx
Petr Vaněk pointed out a change in doctest 2.4.12 that broke the libmime test code:
https://github.com/doctest/doctest/commit/d7a5eeb820b61cc3af8a61b3117f76a403b7742a
CHECK is now treats LHS as const and the compiler won't find non-const operator== as a result. It's reasonable for comparators to be const, so make them const.
> [Fix] libmime: doctest 2.4.12 compatibilty

- src/plugins/lua/gpt.lua
Some models used by Ollama will include "thinking" before the actual response. We now remove this.
Also fixed error logging, which probably intended to also log "first_message".
> gpt.lua: Remove "thinking" and fix errorlog

- lualib/lua_redis.lua
I have found an issue in docs about `lua_redis.redis_make_request_taskless()` ([link for the docs](https://docs.rspamd.com/lua/lua_redis/#f262e2)).
For some reason it does not mention that `lua_redis.redis_make_request_taskless()` has parameters of `ev_base` and `config` not just `ev-base`. So, I decided to fix it a little bit
> [Minor] Fix for docs of lua_redis.redis_make_request_taskless

- conf/composites.conf
Common spam pattern, less evil then `FREEMAIL_REPLYTO_NEQ_FROM_DOM`, but seen much more.
Can be seen in legit emails - for example PayPal put Reply-To in their notifications and other senders can do it too, so not give it big score.
> Add FREEMAIL_REPLYTO_NEQ_FROM rule

- doc/rspamc.1
- doc/rspamc.1.md
In https://github.com/rspamd/rspamd/commit/8b18feb6bc086a9ae7f2eef31f78325221707476, the behaviour of the `-P` parameter has been modified to also pass the control password via file input.
This PR aims to adjust the documentation to reflect this behaviour.
Cheers
Thomas
> Modify documentation for rspamc "-P" parameter

- src/plugins/lua/multimap.lua
When a multimap rule is configured with an invalid type it fails but no explicit reason is given. Added a log line.
> [Minor] Print error on multimap invalid type

- src/fuzzy_storage.c
Arguments were appearing in the wrong places when `is_shingle` was false
> [Minor] Fix fuzzy lua callback when there are no shingles

- src/plugins/lua/gpt.lua
This adds the token usage for OpenAI compatible APIs when using `default_openai_plain_conversion`.
> [Minor] Log the token usage for OpenAI (compatible) plain conversion

- contrib/libucl/lua_ucl.c
- contrib/libucl/ucl.h
- contrib/libucl/ucl_parser.c
- contrib/libucl/ucl_util.c
- src/client/rspamdclient.c
- src/controller.c
- src/fuzzy_storage.c
- src/libmime/lang_detection.c
- src/libserver/cfg_rcl.cxx
- src/libserver/cfg_utils.cxx
- src/libserver/dynamic_cfg.c
- src/libserver/roll_history.c
- src/libserver/rspamd_control.c
- src/libserver/symcache/symcache_impl.cxx
- src/libserver/worker_util.c
- src/lua/lua_cryptobox.c
- src/rspamadm/control.c
- src/rspamadm/signtool.c
- src/rspamd_proxy.c
- **[CritFix] In lua-ucl disable macros and file variables by default**
- **[Fix] Backport some issues from libucl**
One of the major issues is that we should use safe parser flags for **all** inputs aside of the real configuration which we should really trust. It means that we need to disable macros, file variables and other UCL features when it is used to parse any potentially unsafe content. I do not treat it as a security vulnerability so far, as Rspamd operates with merely trusted content by HTTP by default, however, it is good to fix to avoid any potential future mususes or even exploits possibilities.
> Fix some issues with libucl

- src/plugins/lua/milter_headers.lua
- test/functional/cases/550_milter_headers.robot
- test/functional/configs/milter_headers.conf
- test/functional/lib/rspamd.robot
A mechanism that allows overriding the active [`milter_headers`](https://docs.rspamd.com/modules/milter_headers) routines via [`user settings`](https://docs.rspamd.com/configuration/settings) has been added in commit https://github.com/rspamd/rspamd/commit/c116e4e35c7caf9b9cd454d85ea088a2c960f62f.
However, due to a bug in the implementation no routines are running when this mechanism is used.
This PR fixes the logic error and adds a functional test that covers this scenario.
**Changes:**
- fix logic error in `skip_wanted()`
- add new functional test for this scenario
- add override settings in `milter_headers.conf` to support the testing
- add supporting functionality in `rspamd.robot`
> [Fix] Correct logic error in milter_headers.lua: skip_wanted()

- src/controller.c
This endpoint returns a JSON array of names of all configured Bayes classifiers in the same order as they are declared in the configuration.
> [Feature] Add /bayes/classifiers HTTP endpoint

- interface/js/app/symbols.js
Sort symbol groups in the Symbols table dropdown filter in a case-insensitive manner, ensuring alphabetical A–Z ordering regardless of capitalization.
> [WebUI] Sort symbol groups in filter dropdown

- eslint.config.mjs
- interface/css/rspamd.css
- interface/index.html
- interface/js/app/common.js
- interface/js/app/rspamd.js
- interface/js/app/upload.js
- rules/controller/fuzzy.lua
Allows retrieving the list of configured fuzzy storages via HTTP API, including associated flags, read_only status, and server addresses.
> [WebUI] Add fuzzy flag selectors to Scan/Learn tab

- src/plugins/lua/gpt.lua
This strips the `<think>`-response for the openai-provider, too (as it is already done for ollama), so reasoning models from LocalAI can be used, too.
> Cleanup GPT response for openai-provider, too (<think>)

- rules/bitcoin.lua
- src/libutil/expression.c
- src/plugins/regexp.c
This change restores arithmetic expression optimizations for N-ary operations (like `+`, `*`, `&`, `|`) that were previously removed. The optimization allows expressions to short-circuit evaluation when the result can be determined early, significantly improving performance for rules with multiple operands.
**Before:** Expressions like `A + B + C + D > 2` would evaluate all operands (A, B, C, D) regardless of intermediate results.
**After:** The same expression will stop evaluating once the sum exceeds the threshold. For example, if `A=1`, `B=1`, `C=1`, the expression stops at C since `1+1+1 > 2` is already true, and D is never evaluated.
Some existing rules were written with the assumption that **all** operands would be evaluated, even when the result could be determined earlier. These …
> [Rework] Return back N-ary optimizations for arithmetic-alike expressions

- lualib/lua_scanners/icap.lua
ipv6 addresses need to be changed to a pseudo hostname in GET request who is encapsulated in ICAP. A change to [::] did not work in SkyHigh Web Gateway (aka McAfee)
Didn't use Lua often maybe the code can be optimized.
> icap.lua: ipv6 pseudo hostname in GET request

- contrib/backward-cpp/CMakeLists.txt
- contrib/simdutf/cmake/simdutf-flags.cmake
This commit resolves an ODR violations when compiling with -flto and -Werror=odr [1]. The main project used a newer C++20 standard, while the backward-cpp and simdutf libraries used an older C++11 standard. This difference caused the linker to fail.
Setting C++20 standard in both libraries resolves the ODR issue.
Link: https://bugs.gentoo.org/962041 [1]
> [Fix] Use C++20 standard consistently to resolve ODR violations

- src/libserver/cfg_file.h
- src/libserver/fuzzy_backend/fuzzy_backend_redis.c
- src/libutil/upstream.c
Improve upstream resilience: add probe mode and remove force revival
- Problem: when all upstreams are marked down, Rspamd immediately revived all of them, causing tight retry loops (especially with 1–2 upstreams) and hammering bad endpoints.
- Solution: implement probe mode with half-open checks and exponential backoff with jitter; remove force-revive-on-empty behavior. When no upstreams are alive, a single probe is allowed once its `next_probe_at` is due; on success, the upstream is reactivated; on failure, backoff increases.
- `src/libutil/upstream.c`
- Add probe state per upstream: `next_probe_at`, `probe_backoff`, `half_open_inflight`.
- Change `rspamd_upstream_get_common` to select a single probe candidate when no alive upstreams; otherwise return NULL.
- Update …
> Improve upstream resilience: add probe mode and remove force-revive

- lualib/lua_util.lua
- lualib/plugins/dmarc.lua
- src/plugins/lua/arc.lua
- src/plugins/lua/bimi.lua
- src/plugins/lua/dmarc.lua
- src/plugins/lua/gpt.lua
- src/plugins/lua/milter_headers.lua
- Add `lua_util.fold_header_with_encoding(task, name, value[, opts])` to fold headers and optionally RFC 2047–encode values in one place.
- Encoding policy: `encode = 'auto'` (default, UTF-8 aware), `true`, or `false`.
- Supports `stop_chars` and `structured` (passed to `rspamd_util.mime_header_encode`).
- Refactor to use the new helper:
- milter_headers: all added headers now use the helper (`auto` policy).
- DMARC munging: `From` and `X-Original-From` folded/encoded with `structured = true`.
- ARC: `ARC-Message-Signature`, `ARC-Authentication-Results`, `ARC-Seal` folded with `structured = true`, `encode = false`.
- BIMI: `BIMI-Indicator` folded only (`encode = false`).
- GPT: reason header folded/encoded via the helper (`auto` policy).
- Results:
- Deduplicates logic and ensures …
> Unify folding for the headers

- src/lua/lua_common.c
- src/lua/lua_config.c
- src/lua/lua_logger.c
This PR introduces an __index metamethod for `rspamd_config` that returns a symbol proxy userdata, enabling safe, piecewise updates like `rspamd_config.SYM.condition = ...` or `rspamd_config.SYM.score = ...`. Previously, only `__newindex` existed, so `rspamd_config.SYM` could not be read or modified incrementally. As part of this change, I refactored `rules/headers_checks.lua` to avoid direct in-place modification of `rspamd_config` and instead build local tables first.
- Allow users and modules to override specific symbol fields (e.g. `condition`, `score`, `group`) without re-declaring the whole symbol.
- Preserve compatibility with existing table-based registration.
- Align Lua API ergonomics with typical Lua patterns for configuration objects.
- `rspamd_config.__index` now returns a …
> Lua: Add index to rspamd_config and symbol proxy to enable piecewise symbol updates

- lualib/lua_magic/heuristics.lua
- lualib/lua_magic/init.lua
- lualib/lua_magic/patterns.lua
- lualib/lua_magic/types.lua
- src/libmime/archives.c
- src/libmime/images.c
- src/libmime/message.c
- src/libmime/mime_parser.c
- src/libmime/mime_parser.h
- src/libserver/cfg_file.h
- src/libserver/cfg_utils.cxx
- src/lua/lua_task.c
- test/lua/unit/task.lua
- Introduced `rspamd_mime_parser_config` (renamed from lib ctx) to hold boundary matcher, siphash key, and preloaded `lua_magic.detect_mime_part` reference; initialized once per config.
- Renamed runtime struct to `rspamd_mime_parser_runtime`.
- MIME parser now calls Lua Magic once per part, fills `detected_ext/detected_ct/detected_type` and `NO_TEXT` flag, and promotes to nested `message` when `type == "message"` or `ext == "eml"`; embedded messages are parsed immediately.
- Removed duplicate Lua Magic invocation from `message.c` (kept `lua_content` processing).
- Added accessor to read Lua callback from the parser config and stopped direct field access.
- Cleanups: removed obsolete C-side `.eml` extension heuristic, restored `get_cte(...)` signature/logic, minor include fixes.
Result: …
> [Feature] Detect part types in mime parser

- src/libstat/backends/redis_backend.cxx
refer to https://bugs.gentoo.org/963055
I´ve been asked to pass this upstream
> [fix] build issues with lua version higher than 5.1

- src/libmime/mime_headers.c
- test/rspamd_cxx_unit_rfc2047.hxx
- Fix ASAN stack-buffer-overflow in RFC 2047 encoder by handling buffer-too-small returns and computing Q-encoding budget per char (alnum/space=1, others=3).
- Implement minimal, RFC-compliant span selection:
- For unstructured headers, encode only necessary non-ASCII runs; break on parentheses; selectively include bridging ASCII punctuation; don’t swallow ASCII suffixes.
- Preserve linear whitespace and tabs outside encoded-words; include visible whitespace inside encoded-words as “_” (space) or “=09” (tab) when appropriate.
- Enforce valid UTF-8 in decoded headers; replace invalid sequences with “?” to avoid leaking broken bytes.
- Rework tests:
- Add cases for the reported string (“¡Con estos precios, el norte es tuyo! 🏜️”), invalid UTF-8, mixed ASCII/UTF/punctuation/spacing/emoji, and …
> Fix mime encoding

- src/plugins/lua/rbl.lua
The `descriptions` array was missing some entries compared to the current `pipeline` .
Also included the `description` on the `pipeline returned false` message, to aid debugging.
> [Minor] Minor RBL pipeline fixes

- src/controller.c
- src/libstat/stat_process.c
- test/functional/cases/110_statistics/300-multiclass-redis.robot
- test/functional/cases/110_statistics/320-multiclass-peruser.robot
- Set `autolearn_class` during LEARN_PRE (multiclass and binary) so cache compares the intended class.
- Honor Redis callback flags (`ALREADY_LEARNED`/`UNLEARN`) in `rspamd_stat_cache_check` to avoid duplicate learns.
- File: `src/libstat/stat_process.c`
> [Fix] Learn cache fix

- lualib/rspamadm/fuzzy_ping.lua
- src/plugins/fuzzy_check.c
This PR adds support for using separate encryption keys for read and write operations in the fuzzy_check plugin.
- Added new fields to `fuzzy_rule` structure for separate read/write encryption keys
- Added configuration parameters: `read_encryption_key` and `write_encryption_key`
- Modified `fuzzy_encrypt_cmd()` to accept keys as parameters
- Updated all command generation functions to select appropriate keys based on operation type:
- **Read operations**: FUZZY_CHECK, FUZZY_STAT, FUZZY_PING
- **Write operations**: FUZZY_WRITE, FUZZY_DEL
- Updated `fuzzy_free_rule()` to properly free new key structures
- Added configuration documentation for new parameters
Fully backward compatible. If `read_encryption_key` or `write_encryption_key` are not specified, the common `encryption_key` parameter …
> [Feature] Add separate encryption keys for read/write operations in fuzzy_check

- interface/js/app/upload.js
- test/playwright/tests/scan.spec.mjs
after reconnect from read-only
Ensure classifiers are fetched when the dropdown is empty even if cache suggests skipping,
preventing an empty selector on Scan tab after RO → Disconnect → Enable.
> [Fix] WebUI: repopulate classifier dropdown

- src/lua/lua_logger.c
- test/lua/unit/logger.lua
Add support for format type specifiers in lua_logger:
- %d - signed integer (int64)
- %ud - unsigned integer (uint64)
- %f - floating point with smart formatting (no trailing zeros)
- %.Nf - floating point with N decimal places precision
- %% - escape literal percent sign
Type specifiers can be combined with positional (%1d) and
sequential (%d) argument references. String to number conversion
is supported. Added comprehensive unit tests.
> [Feature] Add type specifiers support to lua_logger
