- CMakeLists.txt
- centos/rspamd.spec
To be even more of a bad person I'd like to abuse this forum to mention that commit 74514d50dfb9f82ab285a2fb341225838dbd6f2a fixes #88
> Cosmetic changes

- conf/lua/regexp/headers.lua
- src/plugins/lua/once_received.lua
- src/plugins/lua/ratelimit.lua
1. headers.lua:235: attempt to concatenate local 'header_from' (a nil value)
2. once_received.lua:53: bad argument #3 to 'resolve_ptr' (string expected, got nil)
3. ratelimit.lua:188: attempt to index local 'from' (a nil value)
> Various LUA plugin issues

- src/plugins/lua/forged_recipients.lua
> forged_recipients.lua:41: attempt to index field '?' (a nil value)

- CMakeLists.txt
> Fix luajit detection.

- centos/rspamd.spec
- debian/changelog
Those are the only changes which were in rspamd-0.8, but not cherry-picked into master.
> Pull changelogs from rspamd-0.8

- CMakeLists.txt
> Fix luajit/lua headers confusion

- conf/worker-controller.inc
- src/controller.c
- src/libserver/cfg_rcl.c
> Add IPv6 loopback to secure_ip setting

- src/plugins/lua/rbl.lua
Conflicts:
src/plugins/lua/rbl.lua
> RBL: Change order of calls to avoid sending error messages to logs

- src/lua/lua_task.c
Conflicts:
src/libserver/spf.c
src/libstat/backends/mmaped_file.c
src/libutil/expression.c
> Fix warnings.

- src/lua/lua_url.c
Here is the basic implementation for this issue. I have created a new function `lua_url_all`. Please review if any changes. Thanks.
> extract all URLs from a text

- debian/changelog
- debian/copyright
- debian/postinst
- debian/postrm
Please update version in debian/changelog and tag 0.9.1
> Debian changes for 0.9.x

- doc/markdown/tutorials/writing_rules.md
Also try to tune wording a little
> Writing rules tutorial: Fix path to rspamd.local.lua

- conf/metrics.conf
- conf/modules.d/surbl.conf
http://www.surbl.org/news/internal/New-ABUSE-sublist-SC-AB-deprecated
http://www.surbl.org/news/internal/blocked-subcodes-added
> Drop deprecated SURBL bits; rename JP_SURBL_MULTI to ABUSE_SURBL; add SURBL_BLOCKED

- src/plugins/lua/settings.lua
Maybe there is a better way to do this...
> Settings: fix IP match

- src/plugins/spf.c
Shall we just unconditionally disable SPF for authenticated users?- I can't think of a reason someone would want it, so seems OK to me.
Fixes #443
> Unconditionally disable SPF for authenticated users

- src/plugins/surbl.c
Got out of bed wondering *how* could this be working properly: it did not.
> Oops: fix conditions in SURBL plugin

- conf/metrics.conf
- conf/modules.d/surbl.conf
- Query sbl.spamhaus.org instead of zen.spamhaus.org
- Change ZEN_URIBL to SBL_URIBL
- Add URIBL_SBL_CSS
> Add URIBL_SBL_CSS

- rules/misc.lua
- Add MISSING_FROM rule
- Update MULTIPLE_UNIQUE_HEADER to include RFC5322 header rules
- Raise MISSING_DATE on empty Date: header
> Rules updates

- doc/markdown/modules/replies.md
- src/plugins/lua/replies.lua
Bit limited vs rmilter but maybe this is ok, or good enough for a start anyway. ;)
> [Feature] Add replies plugin

- contrib/exim/shutdown.patch
> [Fix] Fix Exim shutdown patch

- contrib/exim/shutdown.patch
> [Rspamd 1.2] [Fix] Fix Exim shutdown patch

- src/rspamadm/configtest.c
- src/rspamadm/fuzzy_merge.c
- src/rspamadm/pw.c
This is a really small typo fix, but enough to make lintian complaining when building the package!
> [Typo] Correct suppress spelling

- doc/markdown/configuration/metrics.md
The paragraph for `unknown_weight`, and the paragraph following it, need to be reworded. Unfortunately I can't make out your meaning for these two paragraphs.
> [Doc] Correct configuration/metrics.md

- doc/markdown/modules/phishing.md
> [Doc] Relocate comment out of array

- rules/misc.lua
Resolves https://github.com/vstakhov/rspamd/issues/684
> [Feature] Add support for non-standard BATV signatures

- test/functional/cases/general.robot
- test/functional/cases/lua.robot
- test/functional/cases/statistics.robot
- test/functional/lib/rspamd.py
- test/functional/lib/rspamd.robot
Will follow this with some more tests soon. ;)
> Minor tweaks for test suite

- test/functional/cases/archives.robot
- test/functional/cases/statistics/lib.robot
- test/functional/configs/plugins.conf
- test/functional/lib/rspamd.robot
- test/functional/messages/rar4.eml
- test/functional/messages/zip-doublebad.eml
- test/functional/messages/zip.eml
- Also some new features for Check Rspamc function
- Run rspamd/rspamc with LD_LIBRARY_PATH
... I will continue work on this later ... ;)
> [Test] Some basic functional tests for mime_types module & archives

- rspamd.service
Pretty sure it does not belong there. ;)
> [Fix] Remove Type=forking from systemd unit file (#709)

- src/plugins/lua/spamassassin.lua
- Also some minor cleanup and fixing of logging
- Import fun.lua stuff into main namespace
> [Fix] Deal with certain nested dependencies in SpamAssassin module

- src/libstat/backends/mmaped_file.c
Please have a careful look to see that it is sane. ;)
> [Fix] Fix creation of mmapped statfiles

- test/functional/cases/statistics/compat-keyed.robot
- test/functional/cases/statistics/compat-plain.robot
- test/functional/configs/stats.conf
Between this and the other PR these tests should now pass.
> [Fix] Partial fix for mmap'd statistics tests

- circle.yml
- test/functional/cases/statistics/lib.robot
- test/functional/lib/rspamd.py
- test/functional/lib/rspamd.robot
This should be a step in the right direction at least though I fear we can expect ongoing trouble for now.
> Try harder to kill rspamd + child processes to avoid cascading failures

- test/functional/cases/102_maps.robot
- test/functional/cases/103_password.robot
- test/functional/lib/rspamd.robot
Still not happy with `Check Rspamc` but I suppose this is better.
Maps tests seem to be causing rspamd to drop cores. Maybe we should try adding binaries & coredumps to build artifacts. :)
> [Test] Some minor fixes & improvements for tests

- src/plugins/lua/dmarc.lua
- Also add DMARC_BAD_POLICY symbol when DMARC policy was invalid
> Allow for setting action based on DMARC disposition

- conf/mime_types.inc
> Add missed MIME types

- interface/js/rspamd.js
This could stand some further improvement. We can't really make assumptions about what actions are in metric. This fixes it in the case metric actions are the default set anyway.
> [WebUI] Fix saving actions from web interface (#769)

- circle.yml
- test/functional/lib/rspamd.py
This should be more robust I hope.
> [Test] Replace get_process_children with psutil function

- src/plugins/lua/mime_types.lua
> [Fix] Ignore content type/subtype case

- circle.yml
- test/functional/cases/121_json.robot
- test/functional/lib/rspamd.py
- test/functional/lua/preresult.lua
Unfortunately this means adding yet another library as JSON parser in Python standard library is just not strict enough- even in its 'strict' mode.
> [Test] Some basic tests for JSON sanity

- circle.yml
> [Minor] Small improvement for coverage flags

- conf/metrics.conf
The symbol is not used anymore.
> Remove symbol HFILTER_HELO_UNKNOWN from mertics.conf

- test/functional/lib/rspamd.robot
Ok, I guess it's fine to merge this so long.
> [Test] Remove nasty artifact from `Run Rspamd` function

- src/plugins/lua/rbl.lua
Yech. :/
This is mostly just whitespace changes...
> [Feature] Simple mechanism for disabling RBLs in local.d/rbl.conf

- utils/rspamd_stats.pl
rspamd_stats will read (and decompress) multiple log files in the specified directory.
> [Feature] rspamd_stats: support log directory reading

- test/functional/cases/102_multimap.robot
- test/functional/cases/121_json/100_preresult.robot
- test/functional/cases/121_json/101_simple.robot
- test/functional/cases/121_json/lib.robot
- test/functional/cases/135_spamassassin.robot
- test/functional/lib/rspamd.robot
- Removed horrible features from test library
- Negative cases for SpamAssassin WLBLEval
- Restructured JSON tests
> [Test] Some minor updates for tests

- test/functional/cases/102_multimap.robot
- test/functional/cases/140_proxy.robot
- test/functional/configs/multimap.conf
- Test unfiltered URL map
- Test SPAMC & RSPAMC protocols at proxy
> [Test] Additions for multimap & proxy tests

- src/rspamadm/stat_convert.lua
That was my fault obviously. ;)
> [Fix] rspamadm statconvert: Oops- fix variable clobbering

- circle.yml
- test/functional/lib/rspamd.py
- Also a loosely-related fix for test library
Doesn't seem to have done us much good unfortunately.
> [Test] Use out of tree build for tests/code coverage

- src/plugins/lua/ip_score.lua
- Also simplify some funny math
Avoided changing default behaviour.
> [Feature] Allow for more fine-grained scoring for ip_score

- rules/regexp/lotto.lua
> kam_lotto7 moved to r_lotto_subject

- rules/regexp/headers.lua
- src/plugins/lua/dmarc.lua
- Also clean up X_PHP_EVAL rule
> [Minor] Fix log message

- src/plugins/lua/replies.lua
Change prefilter priority for another plugins
> Change priority replies plugin

- src/plugins/lua/dmarc.lua
- Also allow forcing action on DMARC_NA; DMARC_DNSFAIL; DMARC_BAD_POLICY
> [Feature] Add DMARC_NA symbol

- src/plugins/lua/asn.lua
- src/plugins/lua/ip_score.lua
- src/plugins/lua/ratelimit.lua
- Also per-IP and per-ASN ratelimits
- Minor rework of some parts
Seems likely this could stand some improvement.
> [Feature] Adaptive ratelimits

- conf/surbl-whitelist.inc
msn.com, youtube.com, wordpress.com
> removed dupes

- src/plugins/lua/dmarc.lua
- Also make DMARC symbols configurable
- Register some additional symbols
> [Minor] Yield DMARC_NA when From header is missing

- interface/js/rspamd.js
- src/plugins/lua/antivirus.lua
- src/plugins/lua/asn.lua
- src/plugins/lua/dcc.lua
- src/plugins/lua/dmarc.lua
- src/plugins/lua/emails.lua
- src/plugins/lua/fann_scores.lua
- src/plugins/lua/forged_recipients.lua
- src/plugins/lua/greylist.lua
- src/plugins/lua/hfilter.lua
- src/plugins/lua/ip_score.lua
- src/plugins/lua/maillist.lua
- src/plugins/lua/mime_types.lua
- src/plugins/lua/multimap.lua
- src/plugins/lua/once_received.lua
- src/plugins/lua/phishing.lua
- src/plugins/lua/ratelimit.lua
- src/plugins/lua/rbl.lua
- src/plugins/lua/replies.lua
- src/plugins/lua/rspamd_update.lua
- src/plugins/lua/settings.lua
- src/plugins/lua/spamassassin.lua
- src/plugins/lua/trie.lua
- src/plugins/lua/whitelist.lua
> Revert useless commits

- src/plugins/lua/ratelimit.lua
> [Minor] Fix ratelimit rework: don't recycle stale value

- src/plugins/lua/ratelimit.lua
- Don't bother calling init() on builtin keywords
- Adjust adaptive ratelimits to better deal with new model
- Populate user_data from custom keyword file
> [Minor] Some small changes to ratelimit

- src/libserver/spf.c
- src/plugins/spf.c
- test/functional/cases/115_dmarc.robot
I'm still battling the remaining issues unfortunately. :/
> [Fix] Yield R_SPF_DNSFAIL if lookup of included record fails

- src/libserver/spf.c
- src/libserver/spf.h
- src/plugins/spf.c
- test/functional/cases/115_dmarc.robot
- Also yield R_SPF_DNSFAIL on bogus redirect
- Also grow SPF tests
> [Feature] Add R_SPF_PERMFAIL symbol

- circle.yml
- src/CMakeLists.txt
Coverage for this among other stuff is still broken but this seems to be a step in the right direction at least.
> [Test] Help lcov find ragel parts sans hacks

- conf/metrics.conf
- conf/modules.d/surbl.conf
WS is part of ABUSE now: http://www.surbl.org/lists
> [Minor] Retire old SURBL settings (Fixes #966)

- rules/misc.lua
Issue: #621
Reported by: @AdUser
> [Fix] Try avoid false-positives in HEADER_FORGED_MDN rule

- rules/misc.lua
- Narrow regex match
- Fix syntax error
- Fix comparison
- Reduce scoring: worried this matches something real, needs testing
> [Minor] Fix FORGED_X_PHP_SCRIPT1

- rules/misc.lua
I need to do some prep work before I could make such speculative rules. ;) I've not seen a non-forgery that matches this but I feel they're out there.
> [Minor] Retire FORGED_X_PHP_SCRIPT1 rule

- conf/statistic.conf
Perhaps I miss something about how this is supposed to work.
> [Fix] Fix bayes learn_condition

- rules/http_headers.lua
- Fix some inaccuracies
- Add new symbols
- Use symbols from configuration
> [Minor] Update http headers rules

- interface/js/rspamd.js
Resolves: #1027
Reported by: @fenice2
> [WebUI] Improve history table controls

- src/lua/lua_task.c
I suppose maybe there is some use-case for it. ;)
> [Feature] Support setting task message from Lua (Fixes #1046)

- src/plugins/lua/greylist.lua
- Implement whitelist domains
- Add action setting
- Fix ip variable name
- Fix read settings
> Rework greylist plugin

- src/lua/lua_common.c
Currently misses stats from statistics & fuzzy.
> [Feature] Allow for getting worker stats from Lua

- src/plugins/lua/mx_check.lua
> [Minor] Add expire setting for non valid mxes

- src/plugins/lua/mx_check.lua
Old version: FROM <one@test.vov.ru> realy check "vov.ru"
New version: FROM <one@test.vov.ru> realy check "test.vov.ru"
> Change logic for MX-check plugin

- src/plugins/lua/phishing.lua
- organize map checks into a function
- use as symbol option actually matched domain name part (eSLD or hostname)
> [Minor] phishing: rework map checks

- src/plugins/lua/metric_exporter.lua
- Also fix statefile-less configuration
> [Minor] Tidy graphite_config function in metric exporter

- src/rspamadm/CMakeLists.txt
- src/rspamadm/commands.c
- src/rspamadm/fuzzy_convert.c
- src/rspamadm/fuzzy_convert.lua
Should be good enough for a start I hope. ;) Some shortcomings:
* Doesn't get fuzzy expiry from config; need to investigate how to make that work or if it indeed does (`util.load_rspamd_config` crashes `rspamadm lua` which did not give me hope)
* Doesn't care about pre-existing data. Typically, we expect destination database to be empty so maybe this is fine, but the situation could anyway be improved.
* Considers all fuzzies as belonging to the 'local' storage
* Maybe more :)
Suggestions welcome.
> [Feature] Utility to convert fuzzy storage from sqlite to redis

- circle.yml
- test/functional/cases/120_fuzzy/lib.robot
- test/functional/cases/120_fuzzy/redis-general.robot
- test/functional/cases/120_fuzzy/xxhash-keyed.robot
- test/functional/cases/120_fuzzy/xxhash.robot
- test/functional/configs/fuzzy.conf
- test/functional/messages/spam_message.eml.fuzzy1
Turns out fuzzy fuzzy test was not actually working. It's fixed now/disabled in cases where it's not working correctly.
> [Test] Add tests for Redis fuzzy backend and fix fuzzy fuzzy test

- src/plugins/lua/dcc.lua
- src/plugins/lua/dynamic_conf.lua
- src/plugins/lua/fann_scores.lua
- src/plugins/lua/multimap.lua
- src/plugins/lua/mx_check.lua
- src/plugins/lua/rspamd_update.lua
- src/plugins/lua/settings.lua
- src/plugins/lua/spamassassin.lua
- src/plugins/lua/whitelist.lua
Missed a couple of these in SpamAssassin plugin. Also maybe importing `fun` into global namespace isn't the best idea after all, so stop doing this everywhere it's done.
> [Minor] Axe a few more globals

- src/plugins/lua/hfilter.lua
- src/plugins/lua/ratelimit.lua
- src/plugins/lua/trie.lua
Maybe that's ~all? Though we could take it further I suppose.
> [Minor] Remove handful more globals

- src/plugins/lua/metadata_exporter.lua
Maybe this is worth having around...
Possible use-cases include quarantines and feedback loops.
> [Feature] Module to push messages/metadata to redis pubsub

- rules/html.lua
- rules/http_headers.lua
- rules/misc.lua
- rules/regexp/headers.lua
- rules/rspamd.classifiers.lua
- rules/rspamd.lua
So I'd like to start using [luacheck](https://github.com/mpeterv/luacheck) in CI. Precursor to this will be silencing warnings in existing code.
> [Minor] Some linting for rules

- src/plugins/lua/greylist.lua
[Minor] Further simplify conditionals
> [Minor] Further simplify conditionals

- src/lua/global_functions.lua
- src/plugins/lua/antivirus.lua
- src/plugins/lua/asn.lua
- src/plugins/lua/fann_classifier.lua
- src/plugins/lua/greylist.lua
- src/plugins/lua/metadata_exporter.lua
- src/plugins/lua/mx_check.lua
- src/plugins/lua/ratelimit.lua
- Also pass upstream to callback
> [Minor] Move upstream handling into rspamd_redis_make_request

- src/plugins/lua/settings.lua
Resolves: #1136
Reported by: @gibzer
> [Minor] settings: make string matches case insensitive

- interface/css/rspamd.css
- interface/index.html
Resolves: #1191
Submitted by: @andryyy
> [WebUI] Update password prompt

- CMakeLists.txt
> cmake: Add missing luajit include dirs

- rules/html.lua
- rules/regexp/headers.lua
These rules cause me a bit of trouble: maybe it's OK to defang them a little.
> [Minor] Reduce scoring on some rules

- interface/js/rspamd.js
on reconnect / reload
Fixes: #1193
> [WebUI] Fix graph percentage mode resetting

- src/plugins/lua/spamassassin.lua
Conflicts:
src/plugins/lua/spamassassin.lua
> Backport SA module fix to 1.3

- interface/js/rspamd.js
> [WebUI] Set focus to password field (#1230)

- src/plugins/lua/rmilter_headers.lua
```
rmilter_headers {
use = "x-spamd-bar";
routines {
x-spamd-bar {
negsymbol = "";
}
}
}
```
> [Feature] Add rmilter_headers module (Fixes #1227)

- interface/js/rspamd.js
> [WebUI] fix uptime

- src/plugins/lua/rmilter_headers.lua
Doesn't implement the full RFC & maybe misses something important but seems good enough for a start.
> [Feature] rmilter_headers: authentication-results (#78)

- src/plugins/lua/dkim_signing.lua
How does this look to you? :) It's not entirely like rmilter but it's close. :)
> [Feature] Add preliminary version of DKIM signing module

- src/plugins/lua/dkim_signing.lua
- Support signing local networks
- Deal with missing usernames
- Normalise envelope/header from domain
> [Minor] DKIM signing module: Small improvements & fixes

- conf/composites.conf
- src/libserver/cfg_rcl.c
That's a breaking change for `local.d/composites.conf` and `override.d/composites.conf` (but it also makes these files useful).
> [Rework] Composite configuration (#1270)

- src/libserver/dkim.c
> [Fix] Avoid reusing g_error (Fixes #1262)

- interface/js/rspamd.js
stop refreshing widgets on hidden tabs,
make `refresh` button functional for some more tabs
> [WebUI] Use unified tab click event handler,

- interface/js/rspamd.js
do not destroy pie on data update
> [WebUI] Turn d3pie's stuff into a reusable function,

- interface/js/rspamd.js
> [WebUI] Add graph legend entries for new DSes

- src/libserver/cfg_file.h
- src/libserver/cfg_rcl.c
- src/libserver/protocol.c
> [Minor] Add `compat_messages` for compatibility with legacy protocol

- src/libserver/symbols_cache.c
- src/libserver/symbols_cache.h
- src/lua/lua_config.c
> Rspamd 1.4: backport missing API (#1325)

- interface/css/d3evolution.css
- interface/js/rspamd.js
on reconnect / reload
Reported by: @denhli
> [WebUI] Fix graph selectors state resetting

- src/plugins/lua/url_reputation.lua
Resolves points 2, 3, 5 & 7 at #1301. ;)
> [Feature] URL reputation plugin

- src/lua/lua_url.c
- src/plugins/lua/url_reputation.lua
- Fix plugin post changes
- Fix Lua API
- Limit redis queries
- Ignore messages with many TLDs in dynamic reputation
- Try find relevant domain in dynamic reputation
> [Minor] URL reputation plugin changes

- src/plugins/lua/rmilter_headers.lua
- Add spam-header (like Rmilter spam-header)
- Add x-virus (tells about virii found in message)
- Fix configuration; was not honoured
- Fix possible indexing of nil
> [Minor] Rmilter headers: new features & fixes

- src/plugins/lua/rmilter_headers.lua
Use closure instead of passing stuff around for internal functions. User-defined functions still work the same unfortunately.
> [Minor] Rework rmilter headers internal functions

- src/plugins/lua/greylist.lua
Inclination is really to remove code that set's `no action` as I suspect it's trouble & not useful.
> [Minor] Additional log message for greylist plugin

- src/plugins/lua/ratelimit.lua
> Rework ratelimit module changes

- interface/js/rspamd.js
Was constantly seeing `Cannot receive neighbours data` - this solved it.
> [WebUI] Be more generous with AJAX timeout

- src/plugins/lua/dkim_signing.lua
- Also yield symbol when key in Redis was used
> [Minor] Fix warnings

- contrib/rspamdgrep/rspamdgrep.lua
- contrib/rspamdgrep/rspamdgrep.sh
Let's call this a preliminary version. ;) Thoughts?
> [Feature] Implement rspamdgrep tool

- src/rspamadm/grep.c
- src/rspamadm/grep.lua
- Dump partial matches after processing each file
- Don't print orphans & partial matches by default
- Fix typo
> [Minor] Some more fixes/features for rspamadm grep

- src/plugins/lua/url_reputation.lua
- Also avoid work if there's only one TLD
> [Minor] URL reputation: fallback to tags to try gauge relevance

- src/plugins/lua/url_reputation.lua
- src/plugins/lua/url_tags.lua
- Also fix saving of tags
- Reload scripts in URL reputation plugin
> [Minor] Add URL tags plugin; drop functionality from URL reputation

- src/plugins/lua/multimap.lua
- Deal with gaps in Received headers indexes
- Deal with rspamd_ip values
- Fix min_pos/max_pos
> [Minor] Multimap Received headers: fixes

- conf/modules.d/greylist.conf
> [Minor] Fix time specification

- src/plugins/lua/metadata_exporter.lua
- Add stock formatters and selectors
- Add e-mail alert backend
- Support forcing `soft reject` on backend failure
- Support forcing custom action on successful processing
> [Feature] Various new features in metadata exporter module

- src/lua/lua_task.c
- src/plugins/lua/force_actions.lua
```
force_actions {
actions {
"rewrite subject" = [
["THING", null, "[THING] %s"]
];
}
}
```
> Support setting subject in force actions module

- rules/global_functions.lua
I suppose this fixes it anyway.
> [Minor] Fix rspamd_parse_redis_server

- src/plugins/lua/metadata_exporter.lua
- Without per backend callbacks it seems likely that this times out I'm afraid
- Also drop support for forcing action on success (difficult to deal with, probably not useful?)
> [Minor] Metadata exporter: use per-backend callback

- src/plugins/lua/metadata_exporter.lua
- Allow for multiple instances of a backend
- Real template for email alert
- Add JSON formatter
- Support for multiple custom select/push/format functions
- Some fixes for backward compatibility
```
metadata_exporter {
rules {
DERP {
backend = "http";
url = "http://127.0.0.1:13376/hello";
selector = "is_spam";
formatter = "json";
}
HERP {
backend = "http";
url = "http://127.0.0.1:13378/goodbye";
selector = "is_spam";
formatter = "json";
}
}
}
```
> [Minor] More new features/rework for metadata exporter

- rules/regexp/headers.lua
as header format has been changed by mail.ru
> [Minor]  Update mail.ru Received header regexp

- src/plugins/lua/antivirus.lua
> [Feature] Avira SAVAPI support

- src/plugins/lua/rmilter_headers.lua
> [Minor] Rmilter headers: deal with missing reasons in DMARC

- src/plugins/lua/antivirus.lua
Adding SAVAPI prefix for clean and infected messages
Added log_clean option to log clean messages
> [Minor] Add log_clean option for SAVAPI

- conf/redirectors.inc
> [Minor] Update redirectors list

- src/plugins/lua/url_tags.lua
I bloody hope. This was totally broken.
> [Minor] Finally fix saving of URL tags

- src/plugins/lua/antivirus.lua
> [Fix] Antivirus: use scanner-specific redis prefix

- conf/modules.d/antivirus.conf
- src/plugins/lua/antivirus.lua
- Also make log_clean work everywhere
> [Minor] Antivirus module: stricter checks for FProt and ClamAV

- src/rspamadm/grep.lua
> [Fix] Fix log line duplication in `rspamadm grep`

- src/plugins/lua/metadata_exporter.lua
> [Fix] Metadata exporter: use rule-specific settings for emails

- src/plugins/lua/settings.lua
> [Feature] Support using request headers in settings

- src/plugins/lua/dkim_signing.lua
> [Fix] DKIM signing: use domain-specific signing key (#1521)

- src/plugins/lua/dkim_signing.lua
> [Minor] DKIM signing: ensure variables in path are replaced

- src/plugins/lua/greylist.lua
> [Feature] Greylist: Support excluding low-scoring messages

- src/plugins/lua/dkim_signing.lua
Needs to happen ahead of comparisons.
> [Minor] Lower-case DKIM domain sooner

- src/plugins/lua/dkim_signing.lua
> [Minor] DKIM signing: lower-case both of envelope/header domains

- rules/misc.lua
This avoids some possible trouble with mailing lists.
> [Minor] Use SMTP recipients for SPOOF_REPLYTO rule

- conf/modules.d/once_received.conf
- rules/headers_checks.lua
- src/plugins/lua/once_received.lua
- Add DIRECT_TO_MX (e.g. ONCE_RECEIVED + User-Agent or X-Mailer headers), no score currently, needs testing
- Move comparisons to util.strequal_caseless
- Fix FROM_NO_DN and TO_DN_NONE as these weren't firing correctly
> Rule update

- src/plugins/lua/antivirus.lua
When scanning archives, savapi sometimes does not return '<<<' results.
> [Fix] Fix archive scans for savapi

- interface/js/app/history.js
> [WebUI] Disable phrase connectors replacement in history filtering

- src/plugins/lua/dmarc.lua
Also applied next policy by severity in case of sampled_out emails as per [RFC7489](https://tools.ietf.org/html/rfc7489#section-6.6.4).
> added sampled_out dmarc report

- src/plugins/lua/antivirus.lua
Parse full result of the SAVAPI scanner and build a unique virus name
> [Feature] Retrieve all virus names from SAVAPI

- interface/css/rspamd.css
- interface/index.html
- interface/js/app/rspamd.js
Now user have a chance to see all thrown alerts not just the latest one.
> [WebUI] Display multiple alerts at once

- test/lua/unit/html.lua
Added few test cases for HTML content extraction.
> HTML content extraction tests improvement

- interface/js/app/config.js
Variable elts was not updated and always returned the previously set values.
> Fixes saving action scores in WebUI

- interface/js/app/config.js
Default type is submit, which appends "?" to the URL and kicks us back to "Status".
> Fixes redirect to "/?" after submitting values

- src/plugins/lua/dkim_signing.lua
Don't know the actual impact...
> Is not write

- src/plugins/lua/dkim_signing.lua
Now deals with async Redis requests.
> Add ability to read selector from Redis

- src/plugins/lua/dmarc.lua
* Aggregation is being done in Lua; should happen in Redis rather
* Full DMARC report data for a given domain is in memory
* Whole base64-encoded report is in memory
* One report sent at a time
* Size limits not implemented
* Reporting address override not implemented
* Quite fragile: may skip reporting for a domain/orphan data or stop working completely in some cases
* Probably more issues
> [Feature] Preliminary DMARC reporting implementation

- src/plugins/lua/dmarc.lua
- Also fix deletion
- Support redirecting reports (useful for evaluation)
- Deal with possibly missing SPF results
> [Minor] DMARC reporting: rework backend

- rules/headers_checks.lua
Not sure if this breaks the intention of the rule.
> [Minor] Relax CTYPE_MISSING_DISPOSITION rule

- src/plugins/lua/milter_headers.lua
> Add ability to skip local and/or authenticated

- rules/misc.lua
> [Minor] SPOOF_REPLY_TO: mitigate some possible FPs on mailing list posts (#1673)

- src/plugins/lua/milter_headers.lua
Milter_headers module adds extended headers to messages if EVERY envelope recipient matches `extended_headers_rcpt` list.
```
extended_headers_rcpt = ["user1", "@example1.com", "user2@example2.com"];
```
> [Feature] milter_headers: add `extended_headers_rcpt` option

- contrib/mumhash/mum.h
> [Oops] Restore a proper name

- README.md
Mention OpenBSD along with the other BSDs
> In OpenBSD ports too

- rules/html.lua
Another small fix for WHITE_ON_WHITE ...
> [Minor] WHITE_ON_WHITE: Use per-part transparency length

- conf/metrics.conf
Fix some small indent issue in metrics.conf :)
> Fix indent in metrics.conf

- src/plugins/lua/maillist.lua
Some maillists were not detected correctly. Because by default all mails were checked for 'List-Unsubscribe' and 'List-Post' headers.
But those headers do not exist on all maillists.
For example majordomo detection was broken because of this.
> Fix maillist detection

- interface/js/app/history.js
We should not escape own HTML tags in cells.
> [WebUI] Fix history table

- src/plugins/lua/fann_redis.lua
> [Minor] Fann_redis: Fix iterator & some warnings

- utils/rspamd_stats.pl
and omitting date in time specification
> Rspamd stats: add support for syslog timestamps

- interface/js/app/history.js
Commit 75cfe801 broke the display of the symbols in the history.
> Fix symbol name in history

- src/plugins/lua/ratelimit.lua
- Drop support for legacy options
- Ensure incremental updates to counters
- Support multiple limits per bucket
- IP score: now resizes limits only (not periods)
> [Rework] Ratelimit module

- src/lua/lua_mimepart.c
We need this to fix R_BAD_CTE_7BIT
> Rspamd 1.6: backports

- src/plugins/lua/mime_types.lua
e.g. .scr.xz
This technique is commonly used by spammers as xz and bzip2 strip out extension on decompression.
Also it catches xz and bzip2 compressed files with faked extensions like .scr.gz .scr.lzh .scr.uue.
> [Feature] Catch next-to-last bad extension

- src/plugins/lua/reputation.lua
- And other small fixes for reputation module
> [Minor] Silence warnings

- src/lua/lua_config.c
> [Fix] Table parameter for rspamd_config:add_doc()

- interface/js/app/rspamd.js
> [WebUI] Stop using commas in pie chart tooltips

- interface/js/app/graph.js
> [WebUI] Fix Throughput graph and summary

- src/plugins/lua/fann_redis.lua
.. but there is no corresponding rule registered
> [Fix] Symbol 'FANNR_SPAM' has its score defined..

- contrib/exim/dlfunc-json/README
- contrib/exim/dlfunc-json/exim-example.txt
- contrib/exim/dlfunc-json/rspamd.c
With support http, json, checkv2
>  Dlfunc library for Exim

- lualib/lua_redis.lua
- Some functions did not work, fixed this
- Added new functions & variants (is there something else that's likely to be useful?)
- Moved table out of function
- I will add some applicable tests ...
> [Minor] Fix & extend redis key expansion library

- src/plugins/lua/mime_types.lua
- test/functional/cases/105_mimetypes.robot
- test/functional/messages/rar-date-bad-ext.eml
when next-to-last extension is a number or date, e.g. 06.12.2017.scr
> [Fix] Once more (#1879) fix bad extension check

- lualib/rspamadm/corpus_test.lua
- lualib/rspamadm/rescore.lua
- lualib/rspamadm/rescore_utility.lua
- src/rspamadm/CMakeLists.txt
- src/rspamadm/commands.c
- src/rspamadm/corpus_test.c
- src/rspamadm/rescore.c
added corpus_test and rescore commands to rspamadm
> [Feature] added corpus_test, rescore commands

- lualib/dkim_sign_tools.lua
- src/libserver/mempool_vars_internal.h
Hi,
I backported 3 commits which might be usefull to backport to current 1.6 stable :)
> Backport Rspamd-1.6 fixes

- rules/regexp/upstream_spam_filters.lua
> [Minor] Reduce score MICROSOFT_SPAM

- src/plugins/lua/rbl.lua
- Also filter artificial header always
> [Feature] RBL: received: filtering by position & flags

- src/plugins/lua/settings.lua
Support syntax like:
```
header = {"From" = "/bla/i"};
header = {"From" = "/ble/i"};
```
**OR**
```
header = {
"From" = "/bla/i";
"From" = "/ble/i";
}
```
> [Fix] Settings: header: deal with multiple settings (#1988)

- .luacheckrc
- circle.yml
- src/libserver/milter.c
- test/functional/cases/180_milter.robot
- test/functional/configs/milter.conf
- test/functional/lua/miltertest/mt1.lua
Plan is to grow that to cover stuff like checking action sanity & adding/removing headers.
> Beginnings of tests for milter

- rules/headers_checks.lua
Add REPLYTO_EQ_TO_ADDR rule to combat spam seen in the wild like this:
`````
Reply-To: <jrullo@gatewayk12.org>
Subject: =?UTF-8?B?Xw==?==?UTF-8?B?Xw==?==?UTF-8?B?Vw==?==?UTF-8?B?aA==?==?UTF-8?B?YQ==?==?UTF-8?B?dA==?==?UTF-8?B?IA==?==?UTF-8?B?R
Q==?==?UTF-8?B?RA==?==?UTF-8?B?IA==?==?UTF-8?B?UA==?==?UTF-8?B?aQ==?==?UTF-8?B?bA==?==?UTF-8?B?bA==?==?UTF-8?B?IA==?==?UTF-8?B?TQ==?
==?UTF-8?B?YQ==?==?UTF-8?B?aw==?==?UTF-8?B?ZQ==?==?UTF-8?B?cg==?==?UTF-8?B?cw==?==?UTF-8?B?IA==?==?UTF-8?B?ZA==?==?UTF-8?B?b24=?==?U
TF-8?B?4oCZ?==?UTF-8?B?dA==?==?UTF-8?B?IA==?==?UTF-8?B?dw==?==?UTF-8?B?YQ==?==?UTF-8?B?bg==?==?UTF-8?B?dA==?==?UTF-8?B?IA==?==?UTF-8
?B?eQ==?==?UTF-8?B?bw==?==?UTF-8?B?dQ==?==?UTF-8?B?IA==?==?UTF-8?B?dA==?==?UTF-8?B?bw==?==?UTF-8?B?IA==?==?UTF-8?B?cw==?==?UTF-8?B?Z …
```
> Add REPLYTO_EQ_TO_ADDR rule

- lualib/lua_redis.lua
- src/plugins/lua/dmarc.lua
- Also fix lua_redis.exec_script
> DMARC: apply lua_redis script functions

- interface/js/app/history.js
Fix filter reject on history-page #2010
> Fix filter reject on history-page #2010

- interface/js/app/history.js
@kakshay21 Sorry, I overlooked it.
> [Minor] Remove redundand condition (#2041)

- interface/js/app/config.js
Fixes the vanishing of greylist form when a negative value was entered. #1910
> Fixes greylist form vanish

- utils/rspamd_stats.pl
and only if it is connected to the terminal
>  [Feature] rspamd_stats: Output progress info on STDERR 

- interface/js/app/config.js
- src/controller.c
- Never hide actions (fixes #1910)
- Allow to disable actions from WebUI
- Add `rewrite subject` action to `configuration` tab
> [Fix] Never hide actions from WebUI `configuration` tab

- conf/modules.d/milter_headers.conf
- rules/regexp/upstream_spam_filters.lua
- src/plugins/lua/milter_headers.lua
> [Feature] Remove upstream `X-Spam: Yes` header by default

- src/lua/lua_util.c
I found that if I build rspamd on a system without luajit and lua 5.2 it fails with message like 
```
rspamd-1.7.1/src/lua/lua_util.c:2478:15: error: 'luaL_Buffer' has no member named 'buffer'
```
The problem is that lua_util.c has compatibility classes which match lua 5.1 while lua 5.2 has different fields in luaL_Buffer.
The code seems to be a copypaste from another project and the original author states he did no tests against lua 5.2.
This pull request adds some conditions to make the file compatible with lua 5.2.
After this patch the code compiles and runs successfully. But no functional tests performed
> allow rspamd to be built against lua 5.2 (no jit)

- interface/js/app/history.js
Also adds Tooltips to history of specific nodes.
> [WebUI] History: Fix Tooltips on paging, filtering and sorting

- interface/js/app/history.js
I just added "rewrite subject" to the history dropdown in the WebUI.
> [Fix] add 'rewrite subject' to History dropdown

- interface/js/app/config.js
Just some bandaid to fix the modals for maps that appear more than once. There may be better ways, i.e. to prevent maps from showing up multiple times.
> [WebUI] config.js: Fix modalBody for maps that appear more than once

- src/plugins/lua/bayes_expiry.lua
This change allows to set lower `expire` value in configuration.
TTLs greater than new `expire` will be reset during the expiry cycle.
In order to set `expire` value greater than current one, first make tokens persistent (set `expire = -1;`)
and set new `expire` value when at least one expiry cycle completed.
> [Feature] Allow to change `expire` of live statistics

- src/plugins/lua/mime_types.lua
- test/functional/cases/105_mimetypes.robot
- test/functional/messages/f.zip.001.eml
- test/functional/messages/f.zip.gz.eml
> [Minor] Check for archive cloaking

- interface/js/app/history.js
if it doesn't match From/To..Cc..Bcc
> [WebUI] Display smtp sender/recipient in history

- interface/js/app/history.js
The full list can be displayed in the expanded row along with symbols
> [WebUI] Limit recipients list in history column to 3

- .eslintrc.json
- interface/js/app/config.js
- interface/js/app/graph.js
- interface/js/app/history.js
- interface/js/app/rspamd.js
- interface/js/app/stats.js
- interface/js/app/symbols.js
- interface/js/app/upload.js
- interface/js/main.js
rename `interface` oblect as it is a reserved keyword,
declare $span and $tbody variables
> [WebUI] Enable strict mode,

- lualib/lua_stat.lua
I had an old statistics database with 11 million keys on a fairly old host.
`redis.call('HGETALL', k)` caused OOM condition on that host: redis would use more memory than it is allowed to use.
Current implementation is memory efficient, but less replication friendly: even though, replication is not broken, redis may suffer from high load for some time.
Conversion time is more or less same for the old and current approach (at leas, it takes seconds to convert my 11M keys DB)
> Implement memory efficient stat convert

- interface/js/app/history.js
compact symbols display,
sort symbols by name
Issue: #2348
> [WebUI] Fix symbols display in legacy history,

- src/plugins/lua/phishing.lua
Fixing test from CI [1].
[1] https://circleci.com/gh/vstakhov/rspamd/3588
> Fixing unused variable from CI #3588

- interface/js/app/symbols.js
from save buttons on the "Symbols" tab
> [WebUI] Remove previously-attached event handlers

- interface/js/app/rspamd.js
if all requests to neighbours failed
> [WebUI] Do not execute `on_success` callback

- interface/js/app/config.js
- interface/js/app/rspamd.js
- interface/js/app/stats.js
- interface/js/app/symbols.js
> [Minor] Allow to query specific host

- conf/modules.d/clickhouse.conf
- src/plugins/lua/clickhouse.lua
Added optional retention for ClickHouse tables
> Clickhouse retention

- src/libmime/message.c
- test/functional/cases/105_mimetypes.robot
- test/functional/messages/empty-plain-text.eml
> [Fix] Detect empty text part as text, not HTML

- interface/js/app/stats.js
> [WebUI] Fix "auth" request URL

- interface/js/app/history.js
> [WebUI] Fix symbols sorting by score

- conf/modules.d/phishing.conf
.. in favour of DNS based service
> [Minor] Remove phishtank map ..

- interface/js/app/graph.js
> [WebUI] Avoid throughput summary table reinitialization

- conf/modules.d/whitelist.conf
Reported by @bjo81 via Telegram group
> [Conf] Fix whitelist.conf

- test/functional/cases/160_antivirus.robot
- test/functional/lib/rspamd.py
- test/functional/util/dummy_clam.py
- test/functional/util/dummy_fprot.py
- test/functional/util/dummy_http.py
- test/functional/util/dummy_killer.py
Moved code for pid writing and terminating into a separated module.
Also added cleanup: in some cases, processes remained in the system after test is done. It should not happen anymore
> [Test] Small refactoring in dummy services test

- src/plugins/lua/forged_recipients.lua
allow alias expansion and forwarding (Postfix)
> [Feature] Relax FORGED_RECIPIENTS

- test/functional/cases/260_regex.robot
- test/functional/configs/regexp.conf
Added forgotten config for test and one more test case
> Sa body regex

- test/lua/unit/selectors.lua
Tests are gonna fail until this is merged with #2506
> [Test] Uncommented cases which are now working

- test/lua/unit/selectors.combined.lua
- test/lua/unit/selectors.lua
- test/lua/unit/selectors.negative.lua
Also added negative cases (i.e. it doesn't work when it shouldn't) and combinations of selectors
> [Test] More test cases for selectors

- interface/index.html
- interface/js/app/rspamd.js
> [WebUI] Do not display password form when secure_ip is set

- .eslintrc.json
- interface/js/app/history.js
> [WebUI] Add symbols sorting buttons

- .drone.yml
- test/functional/util/merge_coveralls.py
Use custom Docker images uploaded to [Docker Hub](https://hub.docker.com/u/rspamd/) to speedup building and testing in drone.io CI. While here apply other small fixes and improvements.
> Drone speedup

- .drone.yml
- test/functional/util/merge_coveralls.py
Fix gathering coverage data (mostly).
> Drone coverage fix

- test/functional/util/merge_coveralls.py
Add more info to coveralls reports.
> Add git repo info to coveralls payload

- .drone.yml
Based on analagous check added to CircleCI:
https://github.com/rspamd/rspamd/commit/9ace1e0519bda09def77746c22ce952824074980
> Add tidyall checks for perl code

- .drone.yml
- test/tools/http_put.py
* upload robot log instead sending by email.
* other small imporvements
> Drone improvements

- .drone.yml
- test/functional/cases/210_clickhouse/001_migration.robot
- test/functional/cases/210_clickhouse/clickhouse.py
- test/functional/configs/clickhouse-config.xml
- test/functional/lib/rspamd.py
Fix race condition causes test to fail with an exception:
`ConnectionError: HTTPConnectionPool(host='localhost', port=18123): Max retries exceeded with url: /?default_format=JSONEachRow (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f40ad96fdd0>: Failed to establish a new connection: [Errno 111] Connection refused',))`
> Fix test case: Cases.210 Clickhouse.001

- lualib/lua_selectors.lua
For things like:
```
HASH256 {
type = "selector";
selector = "attachments(hex,sha256)";
#map = "file://$LOCAL_CONFDIR/maps.d/hash256.map";
map = "redis://hash256_blacklist";
score = 0.1;
}
```
> [Minor] Selectors - add hash support to attachments selector

- rules/regexp/headers.lua
> [Minor] Add new Message-ID regexp for Seamonkey

- contrib/DEPENDENCY_INFO.md
> Use markdown table in contrib/DEPENDENCY_INFO.md

- interface/js/app/rspamd.js
- interface/js/app/upload.js
> [WebUI] Notify user if uploaded data was not learned

- conf/groups.conf
- conf/modules.d/external_services.conf
- lualib/lua_scanners/clamav.lua
- lualib/lua_scanners/common.lua
- lualib/lua_scanners/dcc.lua
- lualib/lua_scanners/fprot.lua
- lualib/lua_scanners/icap.lua
- lualib/lua_scanners/init.lua
- lualib/lua_scanners/kaspersky_av.lua
- lualib/lua_scanners/oletools.lua
- lualib/lua_scanners/savapi.lua
- lualib/lua_scanners/sophos.lua
- src/plugins/lua/antivirus.lua
- src/plugins/lua/external_services.lua
- Oletools support via Olefy https://github.com/HeinleinSupport/olefy
- ICAP protocol support (tested with Symantec, Sophos, Clamav (SquidClamav)
- improve dynamic weights
- filter mime_parts by extension or regex
- support for multiple rules of the same type (e.g. for icap)
> Oletools,ICAP support / lua_scanners enhancements

- src/plugins/lua/dmarc.lua
Sorry for missing this one I don't know how to trigger reporting manually. With this one report should be barelf free (I've already tested this in production).
> Another LF to CRLF transform in DMARC report

- lualib/lua_scanners/common.lua
- lualib/lua_scanners/icap.lua
- lualib/lua_scanners/oletools.lua
- icap improvement
- oletools extended mode update
- match detected type and files in archives
> Lua scanners

- src/plugins/lua/mime_types.lua
> [Minor] mime_types: Add "text/plain" CT for "csv" extension

- test/functional/messages/next2last-doublebad.eml
to cover rfc2047 decoding (7d8bdf6)
> [Test] Use non-ASCII file name

- src/plugins/lua/mime_types.lua
if extension of the file inside archive is not bad
> [Minor] mime_types: Skip extensions matching

- interface/css/rspamd.css
- interface/index.html
- interface/js/app/rspamd.js
- interface/js/app/upload.js
> [WebUI] Combine Scan and Learning into one tab

- src/plugins/fuzzy_check.c
It would be nice to be able to configure `max_errors` and `revive_time`
for fuzzy check module for low traffic systems.
When traffic volume is relatively low an error rate builds at very slow
rate and it would take a while to reach default 40% threshold. At the
same time waiting for 60s sometimes could be unreasonable for dynamic
environments to re-resolve rspamd fuzzy storage.
I just added some output as a debug example (not in this PR)
```
2019-04-17 04:52:12 #19091(normal) <f109ea>; task; fuzzy_check_timer_callback: got IO timeout with server rspamd-fuzzy-controller.service.consul(172.22.154.120:11335), after 1 retransmits
2019-04-17 04:52:12 #19091(normal) rspamd_upstream_fail: ==> Error rate: 0.5454412583142683
2019-04-17 04:52:12 #19091(normal) rspamd_upstream_fail: ==> Revive time: …
```
> [Minor] Fuzzy upstream error threshold config

- src/plugins/lua/mime_types.lua
> [Minor] Avoid comparing string with boolean

- lualib/lua_scanners/common.lua
This PR adds the missing function "check_metric_results" to common.lua.
> [Major] lua_scanners - fix dynamic scan

- interface/js/app/rspamd.js
> [WebUI] Fix AJAX request URL

- interface/index.html
- interface/js/app/rspamd.js
- interface/js/lib/jquery.stickytabs.min.js
- interface/js/main.js
for tab switching
- Show the correct tab when the page is loaded if there is a hash in the URL.
- Changing the hash in the URL when the tab is changed.
- Change the tab when the hash changes in the URL (back / forward buttons).
> [WebUI] Add URL fragments (#) support

- lualib/lua_scanners/oletools.lua
Fix for https://github.com/rspamd/rspamd/issues/2849
> [Minor] Fix oletools defaults

- interface/js/app/upload.js
(drag-and-drop and context menu cut, delete, paste)
> [WebUI] Scan/Learn: enable/disable buttons on mouse events

- test/functional/cases/104_get_from.robot
- test/functional/cases/120_fuzzy/lib.robot
- test/functional/lib/rspamd.robot
> [Minor] Update test to work with current robot version

- src/plugins/lua/bayes_expiry.lua
as it has no benefits over `lazy` mode
> [Rework] Bayes expiry: eliminate `default` expiration mode

- src/plugins/lua/elastic.lua
Add rspamd hostname field to be able to filter in ES for different rspamd servers
> Add rspamd hostname to ES fields

- interface/js/app/history.js
> [WebUI] Fix sorting errors by date

- src/plugins/lua/bayes_expiry.lua
> [Minor] Avoid using reserved word

- utils/asn.pl
> Small fixes for asn.pl

- test/tools/merge_coveralls.py
coveralls.io is down: https://status.coveralls.io/
> Ignore coveralls API errors

- lualib/lua_redis.lua
Fix for https://github.com/rspamd/rspamd/issues/3004
> wrap ipv6-adresses in brackets

- .eslintrc.json
- interface/js/main.js
between function call arguments
> [Test] ESLint: Do not enforce line breaks

- lualib/lua_redis.lua
> typo form -> for

- lualib/lua_redis.lua
> Actually set sentinel_masters_pattern.

- interface/index.html
- interface/js/app/rspamd.js
- src/controller.c
<hourly|daily|weekly|monthly> -> <by day|by week|by month|by year>
> [WebUI] Rename Throughput time intervals

- test/functional/cases/340_surbl.robot
- test/functional/configs/plugins.conf
- test/functional/configs/surbl.conf
- test/functional/messages/mailadr.eml
- test/functional/messages/mailadr2.eml
> [Test] Uribl in mail address

- interface/js/app/upload.js
> [Minor] WebUI: enable scan button on page load

- contrib/elastic/rspamd_template.json
Fix template for support elasticsearch v7 and fix index patterns from #3041
> Fix template for support elasticsearch v7 and fix index patterns from #3041

- conf/modules.d/arc.conf
> ARC signing instead of DKIM signing.

- test/functional/cases/340_surbl.robot
- test/functional/configs/plugins.conf
- test/functional/configs/surbl.conf
- test/functional/messages/emailbltext.eml
- test/functional/messages/replyto.eml
- test/functional/messages/replyto2.eml
Sometimes missing RSPAMD_EMAILBL_FULL
> [Test] EMAIL BL

- src/plugins/lua/dmarc.lua
Possible fix for #3054 .
I'm unable to trigger the bug so I can't really test this patch.
> rename report_domain -> reportING_domain

- .drone.yml
- test/tools/merge_coveralls.py
Drone 0.8 and Drone 1.x are not fully compatible.
> Update enviroment variable after Drone upgrade

- src/plugins/lua/maillist.lua
Debug message has List-Subscribe instead of List-Unsubscribe.
> List-Unsubscribe debug message typo fix.

- lualib/lua_scanners/init.lua
ups :(
fixes https://github.com/rspamd/rspamd/issues/3098
> [Minor] init razor plugin

- lualib/lua_scanners/razor.lua
> [Fix] lua_scanners - razor rename need_check function

- .drone.yml
Convert Drone pipeline to Drone 1.x syntax. This will allow to execute steps in parallel.
> Drone convert

- src/lua/lua_url.c
Fix doc comments for `rspamd_url` lua module.
> Fix docs for rspamd_url lua module

- src/plugins/lua/reputation.lua
I'm using the url_reputation rule in Rspamd 2.0 with the following configuration:
```
rules {
url_reputation = {
selector "url" {
}
backend "redis" {
}
}
}
```
When an email containing a URL is encountered, the following failure is logged:
> lua_redis_push_data: call to callback failed: /usr/share/rspamd/plugins/reputation.lua:302: attempt to index a nil value; trace:
> [1]:{/usr/share/rspamd/plugins/reputation.lua:302 - continuation_cb [Lua]};
> [2]:{/usr/share/rspamd/plugins/reputation.lua:910 - callback [Lua]};
> [3]:{/usr/share/rspamd/lualib/lua_redis.lua:1262 - callback [Lua]};
> [4]:{/usr/share/rspamd/lualib/lua_redis.lua:883 - <unknown> [Lua]};
The failure is caused by `url_reputation_filter` attempting to lookup the token key returned
in the `get_token` callback in an …
> Fix a failure when calcuating URL reputation

- conf/maps.d/mime_types.inc
- lualib/lua_mime.lua
"application/ics" is non-standard but used by some MUAs
> [Minor] Add non-standard MIME type for iMIP files

- src/libstat/backends/redis_backend.c
- src/libstat/learn_cache/redis_cache.c
- src/libstat/stat_process.c
Fix #3129, Things may need further work:
@vstakhov, please help to review the current implementation, thanks.
> Fixing multiple classifiers on redis

- src/plugins/lua/dmarc.lua
Add customization - message-id from domain name.
> Tune DMARC report - message-id from

- dist.sh
Instead of archiving files from the working tree, distribute files as
committed. Use the 'git archive' command to achieve this, it results in
a reproducible tarball with the same timestamp as the latest commit.
___
Open question:
- Previously hidden files and directories were ignored because tar could archive `.git/` or `.hg` otherwise. However with `git archive`, only committed files are archived. Should I remove the filter that ignores hidden files, and ship files such as .gitignore, .luacheckrc, etc.? If so, the archive will have the same file entries as the archive that you would obtain from using "Download ZIP" link on Github.
As a side benefit, with this change, one can also use `unxz < rspamd-xyz.tar.xz | git get-tar-commit-id` to obtain the commit for the tarball.
> [Minor] Simplify creation of dist tarball that is reproducible

- src/plugins/lua/spamtrap.lua
> [Minor] Fix spamtrap score

- src/plugins/lua/metadata_exporter.lua
Mail was not send to extra recipients due to wrong recipient table.
> [Minor] Fix metadata_exporter extra mail recipients

- interface/index.html
> [WebUI] Fix favicon path

- src/lua/lua_task.c
- src/lua/lua_util.c
- src/plugins/lua/spamassassin.lua
- utils/sa_trivial_convert.lua
These changes complete the missing parts of documentation and get rid of duplicate methods in the `rspamd_util` module.
> Improve lua api

- src/lua/lua_task.c
- src/lua/lua_util.c
add new value accessible by key 'raw' to the table returned by util:parse_mail_address and task:get_from
> [Feature] extend lua api

- lualib/lua_scanners/common.lua
- lualib/lua_scanners/oletools.lua
[Minor] lua_scanners - rework mime parts matching
- improve extension detection
- simplify mime part matching
[Minor] oletools - rework json parsing
- handle multiple VBA script results 
- summarize VBA script results
> lua_scanner - oletools / common rework

- package.json
> [Test] Downgrade stylelint

- src/plugins/lua/spamtrap.lua
String is not correctly interpolated. Shows %s in WebUI.
> [Minor] Fix spamtrap map description

- lualib/lua_scanners/common.lua
- fix regex matching on detected mime
- add extension matching on detected extensions
> [Minor] lua_scanners - fix detected parts_match

- src/plugins/lua/dmarc.lua
These issues were reported in #2872 which was closed by the stale bot.
This addresses the first two issues by getting rid of the string
"softfail" and by fixing the reason.
> Fix some DMARC issues

- interface/css/rspamd.css
- interface/index.html
- interface/js/app/stats.js
> [WebUI] Rework cluster members table

- interface/css/rspamd.css
> [WebUI] Improve glyphicons rasterization

- lualib/rspamadm/vault.lua
This patch address this bug: https://github.com/rspamd/rspamd/issues/3391
Please review
> [Minor] rspamadm roll -r must not generate new keys

- interface/css/rspamd.css
- interface/index.html
> [WebUI] Set test selectors card height dynamically

- interface/css/rspamd.css
- interface/index.html
- remove unused declarations
- use Bootstrap classes
> [Minor] CSS clean up

- src/plugins/lua/clickhouse.lua
Fix the query used to find old partitions.
> Clickhouse retention fix

- package.json
TypeError fixed in stylelint/stylelint#4793
> [Test] Unlock stylelint version

- interface/js/app/config.js
- interface/js/app/graph.js
- interface/js/app/stats.js
> [WebUI] Use /stat path to get stat

- src/plugins/lua/maillist.lua
Fix detection of messages send by:
* subscribe.ru
* Mailman 2 and 3
> MAILLIST rule fixes

- interface/index.html
- interface/js/app/rspamd.js
- Convert navbar buttons to <button> elements
- Do not disable Refresh button when auto-refresh is disabled
- Do not refresh current tab on auto-refresh interval change
> [WebUI] Rework navbar buttons

- interface/js/app/rspamd.js
in read-only mode
Reported by: @nwhisper via Telegram group
> [WebUI] Avoid error messages on connect

- interface/js/app/stats.js
> [WebUI] Fix Status tab display for scanned = 0

- rules/misc.lua
* Add `INVALID_DATE` symbol
* Minor adjustments for existing date check to reduce code duplication
> Date checks

- interface/js/app/config.js
- interface/js/app/rspamd.js
> [WebUI] Escape reserved HTML characters in editor

- src/plugins/lua/metadata_exporter.lua
Tested:
```
[X-Rspamd-From] => unknown"
[X-Rspamd-Ip] => unknown"
[X-Rspamd-Subject] => asdasd"
[X-Rspamd-Qid] => unknown"
[X-Rspamd-Rcpt] => unknown"
[X-Rspamd-Action] => reject"
[X-Rspamd-Score] => 29.15"
[User-Agent] => rspamd-2.6"
[X-Rspamd-Fuzzy] => ["c62020f5ba6f4e3e403b6c67abb860954452fa662bf8c38dae06c17c70cc0b79720cf762e45fbeeea7d2fb17f9cf4b28c851bb70f2526b000dba852899c7ce67"]"
[X-Rspamd-User] => unknown"
[X-Rspamd-Symbols] => [{"score":0,"group":"policies","name":"ARC_NA","groups":["policies","arc"]},{"options":["andre.peters@tinc.gmbh"],"score":0,"group":"headers","name":"HAS_REPLYTO","groups":["headers"]},{"options":["andre@develcow.de"],"score":0,"group":"multimap","name":"RCPT_WANTS_SUBJECT_TAG","groups":["multimap"]},{"score":0,"group":"headers","name":"REPLYTO_EQ_FROM","grou …
```
> Include fuzzy hashes in meta data, if any

- interface/index.html
- interface/js/app/graph.js
- interface/js/app/history.js
- interface/js/app/rspamd.js
- interface/js/app/stats.js
> [WebUI] Add History tab autorefreshing

- src/plugins/lua/neural.lua
- test/functional/lua/neural.lua
- Also deduplicate some duplicated stuff
> [Minor] neural: use prefix in pool variable names

- rules/regexp/headers.lua
Small updates to X-Mailer checks.
> X-Mailer header rules

- rules/forwarding.lua
- rules/headers_checks.lua
- rules/misc.lua
- src/plugins/lua/maillist.lua
- src/plugins/lua/spamassassin.lua
Use task:has_header() to check if header is exists.
> [Minor] Use task:has_header instead of task:get_header

- rules/regexp/headers.lua
> Fix some typos in code comments

- lualib/lua_scanners/spamassassin.lua
> [Minor] external_services - spamassassin - result matching

- contrib/publicsuffix/effective_tld_names.dat
Maybe it should be automated to take new https://publicsuffix.org/list/public_suffix_list.dat on every release. But now manual change. Please contact me if you have own idea, how to automate it.
> New list from https://publicsuffix.org/list/public_suffix_list.dat

- contrib/lua-lupa/lupa.lua
- Fixed bug where 'else' was not evaluated if 'elseif' is present.
> [Minor] Update lua-lupa

- interface/js/app/rspamd.js
> [Minor] Avoid browser console warning

- contrib/DEPENDENCY_INFO.md
still probably incomplete but at least some more info
> [Minor] Update dependency info

- lualib/rspamadm/clickhouse.lua
- Fix spelling of nostat(?)
- Sort table (for correct digest)
- Don't add non-existing symbols to profile
> [Minor] rspamadm clickhouse : small fixes

- test/functional/cases/220_http.robot
- test/functional/cases/230_tcp.robot
- test/functional/cases/231_tcp_down.robot
- test/functional/configs/merged-local.conf
- test/functional/configs/merged.conf
- test/functional/lib/rspamd.robot
- Fix worker count(!!! 🤦)
- Fix segfault check
- Unmerge some tests to dodge segfault
- Disable some uneeded modules in merged tests
> [Test] Fix Lua coverage etc

- cmake/FindRagel.cmake
As now causes warning and main CMakeLists.txt min version is greater
> [Minor] FindRagel.cmake - remove cmake min version

- src/plugins/lua/dmarc.lua
domain match should be case insensitive - see https://github.com/rspamd/rspamd/issues/3749#issuecomment-858013193
> domain match should be case insensitive: #3749

- interface/js/app/rspamd.js
that are too difficult to handle properly for dynamic HTML content.
> [WebUI] Disable bootstrap tooltips

- rules/bitcoin.lua
- test/functional/cases/001_merged/280_rules.robot
- test/functional/messages/btc4.eml
- when using PCRE
- and different address types are present
> [Fix] Fix an edge case in BITCOIN_ADDR rule

- CMakeLists.txt
> [Minor] CMakeLists.txt: add LUA_PATH for run-test

- src/libserver/cfg_rcl.c
- src/libstat/stat_config.c
- src/lua/lua_thread_pool.cxx
- src/plugins/fuzzy_check.c
- src/plugins/lua/hfilter.lua
- src/plugins/lua/milter_headers.lua
This PR fixes segfaults and script errors with lua-5.4.
> fix compatibility with lua-5.4

- src/lua/lua_config.c
- Put nested lists on the correct level
- Document more symbol type options
- Try be clearer about dependencies
> [Minor] Updates for API documentation

- src/libcryptobox/cryptobox.c
Compiles and passes tests on alpine Linux
> [Fix] Further fix for i386 compilation

- lualib/lua_scanners/cloudmark.lua
- lualib/lua_scanners/init.lua
in the external services plugin
> [Feature] Add support of Cloudmark

- rules/controller/maps.lua
The `query_specific` endpoint is a bit unwieldy; add an alternative API that accepts a JSON POST.
> [Feature] JSON endpoint for querying maps

- lualib/plugins/neural.lua
- test/functional/cases/330_neural/001_autotrain.robot
- test/functional/cases/330_neural/002_manualtrain.robot
- test/functional/lua/neural.lua
Had to fix a small bug in ROC feature in this PR because the tests will fail without it.
> [Test] Fix neural plugin tests

- lualib/lua_mime.lua
Store the information about task envelope on the structured task in an easily accessible object, envelope. The envelope consists of task's:
-  SMTP (Envelope) From
- SMTP (Envelope) Recipients
- Helo
- Hostname
- Client IP
- From IP
The envelope will be stored on the Task as task->envelope.
> [Minor] Store Envelope (SMTP) information on structured task.

- interface/index.html
> [WebUI] Fix saving credentials in password manager

- interface/index.html
- interface/js/app/upload.js
which allow to set HTTP headers for scan request
> [WebUI] Add scan options

- test/rspamd_test_suite.c
Fixes sporadic unit test failures (on Mac OS X).
> [Minor] Tune Lua GC for Lua unit tests

- lualib/lua_scanners/icap.lua
- some adjustments for McAfee Web Gateway 9
- check Checkpoint Sandblast compatibility
> Lua scanners/icap

- conf/statistic.conf
small typo in config documentation in statistic.conf
> [Minor] Fix typo in config documentation in statistic.conf

- .drone.yml
without failing the overall pipeline.
> [Test] Allow linters to fail

- interface/index.html
- interface/js/app/rspamd.js
> [WebUI] Add HTTP (Ajax) request timeout setting

- interface/index.html
- interface/js/app/rspamd.js
- interface/js/app/upload.js
> [WebUI] Learn a random server of "All SERVERS"

- src/plugins/lua/metadata_exporter.lua
Adds scan time and hostname as wished for in #4164 
The code is similar to the `elastic.lua` plugin
> [Minor] Add scan_time and hostname to metadata_exporter

- src/libserver/http/http_router.c
> [Fix] Fix favicon.ico Content-Type header

- src/libserver/http/http_router.c
> [Minor] Fix copy-paste error

- src/plugins/lua/metadata_exporter.lua
Add 201, 202 and 204 return codes as valid for http POST made by metadata_exporter
> metadata_exporter http pusher: Extend valid return codes

- utils/rspamd_stats.pl
> [Minor] Use a scalar variable as a dir handle

- interface/css/rspamd.css
of the Bayesian statistics table
> [Minor] Fix rows background coloring

- interface/index.html
- interface/js/app/upload.js
> [WebUI] Add ability to compute fuzzy hashes

- interface/css/rspamd.css
- interface/index.html
- interface/js/app/rspamd.js
instead of overlay alert messages
Issue: #4502
> [WebUI] Show validation feedback inside login modal

- conf/scores.d/rbl_group.conf
- conf/scores.d/surbl_group.conf
- rules/headers_checks.lua
- rules/html.lua
- rules/misc.lua
- rules/regexp/headers.lua
- rules/subject_checks.lua
This merge request improves and streamlines a variety of rule descriptions and comments. Similar to https://github.com/rspamd/rspamd/pull/4397, it does not introduce any functional changes.
> [Minor] Assorted cleanup and housekeeping of configuration files, take 2

- docker/Dockerfile
> Dockerfile: Switch to bookworm

- interface/css/rspamd.css
> [WebUI] Tweak bootstrap colors for accessibility

- src/plugins/lua/settings.lua
I expect it's unwanted anyway. I thought about setting a better descriptive text but nothing came to mind.
> [Minor] Remove unwanted debug logging

- src/lua/lua_ip.c
- Also clarify description
- Make sure example is appropriate
> [Minor] API docs: lua_ip: fix function name

- interface/js/app/rspamd.js
> [WebUI] Set locale on UI load

- conf/modules.d/know_senders.conf
- lualib/lua_redis.lua
- src/plugins/lua/greylist.lua
- src/plugins/lua/known_senders.lua
> Implement known senders plugin

- test/functional/cases/400_known_senders.robot
- test/functional/configs/known_senders-local.conf
- test/functional/configs/known_senders.conf
- test/functional/configs/maps/known_senders_domains.map
- test/functional/lib/vars.py
Suggestions about things to test and such welcome.
> [Test] Rudimentary tests for known_senders plugin

- test/functional/lib/rspamd.robot
So issues aren't impossible to discern
> [Test] Ignore encoding errors

- .drone.jsonnet
- .drone.yml
- test/tools/merge_coveralls.py
> Run CI on ARM

- .drone.jsonnet
- .drone.yml
- Try to close coveralls parallel builds when failed (to be kind to coveralls)
- Skip notification on pull requests (they won't work anyway)
> Minor improvements for CI

- test/functional/cases/001_merged/160_antivirus.robot
- test/functional/cases/110_statistics/lib.robot
- test/functional/cases/116_dkim.robot
- test/functional/cases/120_fuzzy/lib.robot
- test/functional/cases/200_luacheck.robot
- test/functional/cases/210_clickhouse/001_migration.robot
- test/functional/lib/rspamd.robot
> [Test] Use Robot Framework native IF

- lualib/plugins/dmarc.lua
When start to using rspam and the purpuse of munging I found some problems:
I guess the debugging function is changed in the last few updates, but not all the debug rows where changed completely.
And then the lua script ends without any error.
And a second fix to make sure if the name is not set for some reason the user is set instead of of nothing.
> Dzjaivnt patch 1

- .eslintrc.json
- interface/js/app/rspamd.js
to scan results and history tables
> [WebUI] Add control to invert action filter

- .eslintrc.json
- interface/js/app/rspamd.js
on repeated rows per page input
> [WebUI] Fix history table vanishing

- src/plugins/lua/mime_types.lua
Rationale: https://dshield.org/diary/Malware+Dropped+Through+a+ZPAQ+Archive/30366/
> [Minor] Treat *.zpaq attachments as archives and harmful

- src/plugins/lua/force_actions.lua
Helps #4684 
... Possibly we should add support for flags like `least` ...
> [Minor] force_actions: set a group for symbols

- src/plugins/lua/known_senders.lua
Reported by Bensch on Telegram
> [Fix] known_senders: fix config handling

- lualib/rspamadm/fuzzy_ping.lua
- src/fuzzy_storage.c
- src/libserver/async_session.c
- src/libserver/fuzzy_wire.h
- src/lua/lua_task.c
- src/plugins/fuzzy_check.c
- src/rspamadm/lua_repl.c
- src/rspamadm/rspamadm.c
> [Feature] Support ping command in fuzzy storage

- interface/js/app/config.js
- interface/js/app/graph.js
- interface/js/app/history.js
- interface/js/app/rspamd.js
- interface/js/app/stats.js
- interface/js/app/symbols.js
- interface/js/main.js
ES6 is required now for WebUI anyway.
> [Minor] Remove obsolete code

- cmake/FindArch.cmake
- contrib/backward-cpp/backward.hpp
- contrib/libev/ev.c
- src/rspamd.c
Solve the following problems
[detail eroor](https://buildd.debian.org/status/fetch.php?pkg=rspamd&arch=loong64&ver=3.7.3-1&stamp=1698450246&raw=0)
> Add support for loongarch

- src/controller.c
- src/fuzzy_storage.c
- src/libserver/fuzzy_wire.h
- src/libserver/mempool_vars_internal.h
- src/plugins/fuzzy_check.c
> Fix fuzzy stat

- src/libmime/mime_headers.c
- src/libmime/mime_headers.h
- src/lua/lua_task.c
- test/rspamd_cxx_unit_utils.hxx
> Fix issues with the raw header on header insertion/modification

- lualib/lua_dkim_tools.lua
- test/functional/messages/dmarc/fail_none.eml
Reported by @EurenikZ in https://github.com/rspamd/rspamd/discussions/4698
> [Fix] dkim_signing: siging_table: lowercase before lookup

- .eslintrc.json
- interface/js/app/symbols.js
- reduce the minimum number of digits to appear after the decimal from 3 to 2
- remove useless dynamic step
- remove useless dynamic min/max restrictions
> [WebUI] Refine symbols score input boxes

- src/libserver/logger/logger.c
- test/functional/cases/150_rspamadm.robot
- test/functional/lua/rspamadm/test_batch.lua
- test/functional/lua/rspamadm/test_verbose.lua
https://github.com/rspamd/rspamd/issues/4727
> Fix rspamadm lua logger in rspamd-3.7 (#/4727)

- test/functional/cases/410_systemd_logger.robot
- test/functional/configs/systemd-local.conf
- test/functional/configs/systemd.conf
Reproduces issue described in #4732 ; passes if something like that will be applied
> [Test] Test systemd logging

- lualib/lua_bayes_redis.lua
- Also try nested `redis` objects
- Check statfiles first
> [Minor] Have bayes use global redis settings

- lualib/plugins/rbl.lua
- No chance for IPv6 addresses here ...
- `[` anywhere is good enough
> [Minor] rbl: revisit previous change

- interface/index.html
- interface/js/app/symbols.js
> [WebUI] Symbols: replace individual save buttons

- src/plugins/lua/ratelimit.lua
> [Minor] Log a debug message when ratelimit skipped

- src/libserver/cfg_rcl.cxx
- src/libserver/cfg_utils.cxx
Reported to me by an irc friend.
You might want to ask for a CVE I think.
> Fix an overzealous s/NULL/nullptr/g

- test/functional/cases/150_rspamadm.robot
Re-enforces old default setting that's no longer default in RF7.
> [Test] Fix tests on Robot Framework 7.0

- src/rspamd_proxy.c
This PR will make Rspamd to follow other proxies' conventions about `Host` and `Connection` headers.
> Deal with `Connection` and `Host` headers on proxying

- src/libserver/logger/logger_syslog.c
It should work similarly to file and console in fact.
> [Feature] Support JSON logging when in syslog mode

- src/libserver/http/http_message.c
- src/libserver/http/http_message.h
- src/lua/lua_url.c
- test/rspamd_cxx_unit_utils.hxx
> Fix issues with URL fragment in HTTP requests

- src/plugins/lua/metadata_exporter.lua
> [Fix] Encode headers in metadata exporter

- lualib/lua_scanners/kaspersky_se.lua
Added the following features:
* Source IP pass
* Keep-alive support
> Improve Kaspersky AS integration

- src/fuzzy_storage.c
- src/libserver/maps/map.c
- src/libserver/maps/map_private.h
- test/functional/cases/120_fuzzy/encrypted-dyn1.robot
- test/functional/cases/120_fuzzy/encrypted-dyn2.robot
- test/functional/cases/120_fuzzy/encrypted.robot
- test/functional/cases/120_fuzzy/lib.robot
- test/functional/configs/fuzzy-encryption-key.conf
- test/functional/configs/fuzzy.conf
- test/functional/configs/maps/fuzzy_keymap.map
- test/functional/lib/rspamd.py
- test/functional/lib/vars.py
This PR implements support of dynamic fuzzy encryption keys loading via Rspamd maps.
> Allow dynamic keypairs loading in fuzzy storage

- conf/modules.d/history_redis.conf
- lualib/lua_util.lua
- src/plugins/lua/history_redis.lua
> Revert "[Fix] Fix history key, as we use `{=` and not `{{` in templates"

- lualib/lua_util.lua
- src/plugins/lua/history_redis.lua
Probably one of the most dirty hacks I've used in the Lua code in Rspamd...
> [Fix] Allow different template expansion parameters

- interface/js/app/history.js
- interface/js/app/libft.js
- interface/js/app/symbols.js
- interface/js/app/upload.js
> [WebUI] Disable buttons until tables are ready

- lualib/lua_util.lua
- lualib/rspamadm/dmarc_report.lua
> Rework `jinja_template` functions to avoid LUPA global state dependency

- test/functional/cases/001_merged/160_antivirus.robot
- test/functional/cases/001_merged/310_udp.robot
- test/functional/cases/001_merged/__init__.robot
- test/functional/cases/140_proxy.robot
- test/functional/cases/151_rspamadm_async.robot
- test/functional/configs/composites.conf
- test/functional/configs/redis-server.conf
- test/functional/lib/rspamd.py
- test/functional/lib/rspamd.robot
- Partially unbreak functional tests in Github Actions
> [Test] Use Robot-native process management

- contrib/publicsuffix/effective_tld_names.dat
We should think about some sort of automation for this I suppose
> Sync public suffix list

- src/lua/lua_common.c
We check userdata very frequently, so the idea here is the following:
- Store the address of classname (converted to int) in the metatable at index 1
- When we need to check some udata, we can just compare the static address with the integer stored in metatable
- This avoid quite an expensive `lua_rawequal` call for two tables as we know that our classes are quite static
> Further optimization to the hot path of lua userdata checks

- interface/css/rspamd.css
- interface/js/app/common.js
- interface/js/app/libft.js
- interface/js/app/symbols.js
> [WebUI] Add check/uncheck all checkboxes buttons

- lualib/lua_dkim_tools.lua
- src/plugins/lua/dkim_signing.lua
> Vault signing improvements

- interface/index.html
- interface/js/app/history.js
- interface/js/app/libft.js
- interface/js/app/upload.js
> [WebUI] Add column display mode settings

- src/libmime/mime_parser.c
We should do like MUAs do: imlicitly close incomplete mime parts and treat them as ususal. It is weird and utterly stupid but that's what MUA do.
Issue: #4740
Closes: #4740
> Fix inconsistent nesting in mime parts

- src/libserver/re_cache.c
- src/libutil/multipattern.c
- src/libutil/regexp.c
- src/lua/lua_regexp.c
- test/lua/unit/url.lua
Issue: https://github.com/rspamd/rspamd/issues/4885
Closes: https://github.com/rspamd/rspamd/issues/4885
> Protect regexp matcher from regexps with empty patterns

- src/plugins/lua/spf.lua
https://github.com/rspamd/rspamd.com/issues/736
> [Minor] Fix format of example setting (rspamd/rspamd.com#736)

- rules/headers_checks.lua
This was prompted by `Reply-To` quirks in phishing e-mails, such as:
```
Reply-To: support@victim.com
From: IT Support<something@phisher.com>
To: random.person@victim.com
Subject: Password Expiration Notification
Date: 21 Mar 2024 xx:xx:xx +0000
```
> [Enhancement] Add more symbols for Reply-To header characteristics

- src/libserver/milter.c
- src/libserver/milter.h
- src/rspamd_proxy.c
> Allow custom milter quarantine and tempfail messages

- src/lua/lua_task.c
- src/plugins/lua/greylist.lua
> Update greylisting threshold on each scan as it can be easily dynamic

- .github/workflows/ci_rspamd.yml
`Save workspace directory` step needs to run ...
> [Test] Fix uploading of test logs when tests are failed

- src/libmime/lang_detection.c
> Apply detection phase if fasttext could not detect language

- conf/modules.d/rbl.conf
Related to: https://github.com/rspamd/rspamd/pull/4888
> [Minor] Properly make use of selectors for checking MID RHSs against DNSBLs

- src/libserver/worker_util.c
> [Fix] Check nconns when firing the final termination event

- lualib/plugins/dmarc.lua
- lualib/rspamadm/dmarc_report.lua
- src/libserver/url.c
> Fix parsing of DMARC records with spaces

- test/functional/cases/001_merged/102_multimap.robot
- test/functional/configs/maps/words.list
- test/functional/configs/merged-override.conf
- test/functional/lib/rspamd.robot
- test/functional/messages/words.eml
> [Test] Test multimap regexp_multi map

- src/plugins/lua/known_senders.lua
> [Minor] Set negative default scores

- src/controller.c
- src/libserver/protocol.c
- src/libserver/protocol.h
- src/libserver/protocol_internal.h
- src/libserver/task.c
- src/libserver/task.h
- src/libserver/worker_util.c
- src/libserver/worker_util.h
- src/rspamd.c
- src/rspamd.h
- src/rspamd_proxy.c
- src/worker.c
- src/worker_private.h
https://github.com/rspamd/rspamd/discussions/3484
> [Rework] Allow metrics endpoint to be enabled for each scanner

- conf/composites.conf
- conf/scores.d/mime_types_group.conf
Resolve cases from https://github.com/rspamd/rspamd/discussions/4893
> Exclude MIME_BAD_UNICODE false positive

- src/libstat/stat_process.c
- src/plugins/lua/gpt.lua
* JSON output to avoid strange results from gpt3.5
* Added from
* Added some urls
* Some minor adjustments
> Trying to test various things with GPT

- rules/html.lua
https://github.com/rspamd/rspamd/issues/3867
> [Minor] Fix description (#3867)

- src/plugins/lua/metric_exporter.lua
https://github.com/rspamd/rspamd/issues/5027
> [Fix] metric_exporter: avoid sending `nil` in metric values (#5027)

- test/functional/cases/500_ratelimit.conf
- test/functional/configs/ratelimit.conf
That could be OK for a start but there are further cases to test ...
> [Test] Add tests for ratelimit module

- .github/workflows/ci_eslint.yml
- .gitignore
- package-lock.json
The `npm ci`sets up exact versions of Node.js packages listed in the package-lock.json file, which is ensuring consistency across different test runs and environments.
> [Test] Use actions/setup-node

- conf/scores.d/policies_group.conf
- src/libserver/spf.c
- src/libserver/spf.h
- src/lua/lua_spf.c
- src/plugins/lua/spf.lua
- test/functional/cases/001_merged/117_spf.robot
- test/functional/configs/merged-local.conf
> [Feature] Treat SPF +all in a special way

- conf/modules.d/gpt.conf
- src/plugins/lua/gpt.lua
- **[Minor] Remove top_p reduce temperature to 0**
- **[Minor] Set response_format**
- **[Minor] Ensure some safety when checking weights**
- **[Minor] Improve prompt and add some conversion heursitics**
- **[Minor] Use gpt-4o-mini by default**
> Some tunes and fixes for GPT

- test/functional/cases/550_milter_headers.robot
- test/functional/configs/milter_headers.conf
- test/functional/lib/rspamd.robot
Situation with header removal is a bit terrible.
We might think about reworking this module for 4.0, or at some point or other ...
> [Test] Add tests for milter_headers

- contrib/librdns/curve.c
- src/client/rspamdclient.c
- src/fuzzy_storage.c
- src/libcryptobox/cryptobox.c
- src/libcryptobox/cryptobox.h
- src/libcryptobox/keypair.c
- src/libcryptobox/keypair.h
- src/libcryptobox/keypair_private.h
- src/libcryptobox/keypairs_cache.c
- src/libserver/cfg_rcl.cxx
- src/libserver/cfg_rcl.h
- src/libserver/dkim.c
- src/libserver/http/http_connection.c
- src/libserver/http/http_context.c
- src/libserver/logger/logger.c
- src/libserver/maps/map.c
- src/lua/lua_cryptobox.c
- src/lua/lua_http.c
- src/lua/lua_map.c
- src/plugins/fuzzy_check.c
- src/rspamadm/signtool.c
- src/rspamd_proxy.c
- test/rspamd_cryptobox_test.c
- test/rspamd_cxx_unit_cryptobox.hxx
- **[Project] Remove NIST (OpenSSL) mode from cryptobox**
- **[Project] Remove NIST mode from everywhere**
> Remove NIST mode from cryptobox

- src/libcryptobox/keypair.c
- test/rspamd_cxx_unit_cryptobox.hxx
- **[Project] Remove NIST (OpenSSL) mode from cryptobox**
- **[Project] Remove NIST mode from everywhere**
- **[Minor] Oops, fix pubkey loading**
- **[Fix] Use proper keys when doing asymmetric encryption**
> Fix keypairs encryption/decryption

- src/lua/lua_config.c
I'm curious why this bug has been not mentioned for such a long time...
> [Fix] Unify lua symbols registration

- lualib/lua_maps.lua
- lualib/lua_scanners/icap.lua
- lualib/lua_util.lua
> [PATCH] ICAP: encode constructed  path to be URL safe.

- src/fuzzy_storage.c
- src/plugins/fuzzy_check.c
- **[Rework] Change fuzzy error symbols**
- **[Minor] s/BLOCKED/FORBIDDEN/**
> Rework fuzzy symbols

- lualib/lua_redis.lua
- src/plugins/lua/aws_s3.lua
- src/plugins/lua/bimi.lua
- src/plugins/lua/history_redis.lua
> [Fix] Another fix for Redis schema

- lualib/plugins/ratelimit.lua
- src/fuzzy_storage.c
- src/plugins/lua/ratelimit.lua
Allow the following features per fuzzy key:
* Individual ratelimit
* Expiration
> Implement individual limits for fuzzy keys

- package-lock.json
- package.json
- Upgraded `eslint` from 9.7.0 to 9.10.0
- Upgraded `@stylistic/eslint-plugin` from 2.3.0 to 2.8.0
- Upgraded `stylelint` from 16.7.0 to 16.9.0
>  [Test] Upgrade linters

- CMakeLists.txt
- config.h.in
- src/libcryptobox/cryptobox.c
- **[Minor] Detect __builtin_cpu_supports**
- **[Rework] Use __builtin_cpu_supports where possible**
> Detect CPU using __builtin_cpu_supports where it's possible

- .github/workflows/ci.yml
- .github/workflows/ci_rspamd_build.yml
> Add more build targets

- .github/workflows/ci_rspamd_build.yml
- src/lua/lua_cryptobox.c
- src/lua/lua_rsa.c
Maybe some day OpenSSL authors will learn how to write code...
OpenSSL uses 65537 by default, no need in explicit set.
> Fixes for OpenSSL

- src/fuzzy_storage.c
> [Fix] Iterate over dynamic keys in fuzzy storage

- src/libserver/protocol.c
- src/libserver/protocol_internal.h
- src/libserver/task.c
- src/libserver/task.h
It has been buggy and never really used by anyone I suppose.
> [Rework] Remove control block support

- lualib/lua_scanners/dcc.lua
> [Fix] Fix DCC `rep` handling

- contrib/DEPENDENCY_INFO.md
- contrib/hiredis/CMakeLists.txt
- contrib/hiredis/adapters/libev.h
- contrib/hiredis/alloc.c
- contrib/hiredis/alloc.h
- contrib/hiredis/async.c
- contrib/hiredis/async.h
- contrib/hiredis/async_private.h
- contrib/hiredis/dict.c
- contrib/hiredis/dict.h
- contrib/hiredis/fmacros.h
- contrib/hiredis/hiredis.c
- contrib/hiredis/hiredis.h
- contrib/hiredis/hiredis_ssl.h
- contrib/hiredis/net.c
- contrib/hiredis/read.c
- contrib/hiredis/read.h
- contrib/hiredis/sds.c
- contrib/hiredis/sds.h
- contrib/hiredis/sdsalloc.h
- contrib/hiredis/sockcompat.c
- contrib/hiredis/sockcompat.h
- contrib/hiredis/ssl.c
- contrib/hiredis/test.c
- contrib/hiredis/win32.h
- **[Rework] Update hiredis to 1.2.0**
- **[Minor] Update dependencies info**
> Update hiredis library removing all hacks

- contrib/publicsuffix/effective_tld_names.dat
Pulled from https://publicsuffix.org/list/public_suffix_list.dat
Opened this PR as there has recently been removal of quite a few old, expired domains.
> chore(publicsuffix): update effective_tld_names.dat

- src/libcryptobox/cryptobox.c
- src/libcryptobox/cryptobox.h
- src/libserver/dkim.c
> [Fix] Do not abort when OpenSSL is broken, report that to a user

- src/plugins/lua/mime_types.lua
Rationale: https://www.microsoft.com/en-us/security/blog/2024/10/29/midnight-blizzard-conducts-large-scale-spear-phishing-campaign-using-rdp-files/
> [Minor] Score *.rdp attachments as bad

- src/libmime/mime_headers.c
- src/libmime/mime_headers.h
- src/libserver/protocol.c
- src/libutil/fstring.c
- src/lua/lua_util.c
- test/rspamd_cxx_unit.cxx
- test/rspamd_cxx_unit_rfc2047.hxx
- **[Minor] Get rid of glib utf8 functions**
- **[Rework] Rewrite rfc2047 encoding as it was totally broken**
- **[Fix] Some more fixes**
> Fix RFC 2047 encoding

- lualib/lua_mime.lua
- lualib/rspamadm/mime.lua
- **[Project] Add routine to strip attachments**
- **[Project] Various fixes and `rspamadm mime strip` command**
> Allow to strip attachments

- src/libutil/upstream.c
We apply the following algorithm:
1) Get the current element and it's AF
2) If the next element has the same AF, then we just move to the next element
3) If the next element has different AF, then we should find the next element with the same AF
4) If we cannot find such element, then we return the next element (switching AF)
> [Feature] Improve address rotation algorithm

- interface/css/rspamd.css
- interface/js/app/libft.js
- Replaced 'abbr title' with dynamic description display on hover or focus
- Added tabindex for keyboard accessibility
- Improved symbol rendering using template literals for readability
> [WebUI] Rework symbol description display on hover

- src/lua/lua_util.c
- src/plugins/lua/antivirus.lua
- src/plugins/lua/arc.lua
- src/plugins/lua/clickhouse.lua
- src/plugins/lua/clustering.lua
- src/plugins/lua/elastic.lua
- src/plugins/lua/external_services.lua
- src/plugins/lua/neural.lua
- src/plugins/lua/p0f.lua
- src/plugins/lua/phishing.lua
- src/plugins/lua/reputation.lua
- src/plugins/lua/url_redirector.lua
- **[Fix] Remove USPOOF_SINGLE_SCRIPT_CONFUSABLE from the checks**
- **[Fix] Phishing: Fix many cases of FP for the same domains**
> Fix phishing symbol for the same domains

- lualib/lua_mime.lua
- lualib/rspamadm/mime.lua
- src/lua/lua_task.c
- **[Feature] Lua_task: Allow to load data into the existing task**
- **[Feature] Preliminary implementation of LLM based anonymizing**
- **[Minor] Oops, fix invocation**
- **[Minor] Fixes, fixes**
> Allow to use LLM for anonymize

- src/lua/lua_config.c
- src/lua/lua_http.c
> [Minor] Fix some broken links

- src/plugins/lua/rbl.lua
> [Minor] Respect ipv4 and ipv6 configurations for rbl resolve_ip

- conf/modules.d/rbl.conf
- conf/scores.d/rbl_group.conf
nixspam has shutdown their service on 2025.01.16
closes #5299
> remove nixspam

- lualib/plugins/rbl.lua
> [Minor] rbl check_types was missing images

- lualib/plugins/rbl.lua
- src/plugins/lua/rbl.lua
Set configured checks to true on rbl init.
> [Minor] Set RBL checks to bool true

- lualib/lua_maps_expressions.lua
- src/plugins/lua/multimap.lua
> [Minor] Pass both the multimap and the rules descriptions for combined multimap on create

- src/plugins/lua/gpt.lua
- **[Minor] GPT: Allow to trigger on specific symbols**
- **[Feature] Improve prompt and use plaintext instead of JSON**
- **[Feature] Cache LLM replies**
- **[Minor] Tune caching**
- **[Minor] Tune caching**
> More features to GPT plugin

- conf/modules.d/rbl.conf
- src/plugins/lua/rbl.lua
- **[Fix] Avoid collision hacks in mempool variables hash**
- **[Feature] Allow to disable rbls from map**
- **[Conf] Add map**
> Allow to disable RBLs via map

- src/lua/lua_task.c
- src/lua/lua_util.c
- **[Feature] Allow to add periodic functions in Lua API**
- **[Feature] Allow adding timers to task (respecting symbols)**
> Add ability to create timers from Lua

- lualib/lua_cache.lua
- src/plugins/lua/gpt.lua
- **[Feature] Use debug module name from caller in lua_cache**
- **[Rework] GPT: Use cache framework**
- **[Minor] Fix invocation**
> Use caching framework in gpt module

- .github/workflows/ci_eslint.yml
- package-lock.json
- package.json
- @stylistic/eslint-plugin 2.8.0 -> 4.2.0
- eslint 9.10.0 -> 9.21.0
- postcss-html 1.7.0 -> 1.8.0
- stylelint-config-standard 36.0.1 -> 37.0.0
- stylelint 16.9.0 -> 16.15.0
> [Test] Update JavaScript linters

- src/libserver/maps/map.c
> [Feature] Try to check maps earlier if their expires is too long

- src/lua/lua_logger.c
Fix and improve format string processing in lua_logger_log_format()
* Fix handling of %s after % with numeric argument (`num_arg` in the original code was not reset to `false`)
(this restores the functionality described in the [docs](https://rspamd.com/doc/lua/rspamd_logger.html))
* Fix argument number check
* Preserve unhandled % in the output
* Redesign to simplify the code
| Example (e.g. using `rspamd_logger.infox`) | Original code output | New code output |
|- | - | - |
|infox("Test: arg1=%1 arg2=%2 arg3=%s", "A", 123, "3rd") |`error` wrong argument number: 0 | Test: arg1=A arg2=123 arg3=3rd |
|infox("Test is %s% done", 50) |Test is 50 done | Test is 50% done |
|infox("Test: %s extra %s", "with") |Test: with extra no value | `error` wrong argument number: 2 |
See #5322 also.
> [Minor] Fix and improve format string processing in lua_logger_log_format()

- lualib/lua_maps.lua
- test/functional/cases/001_merged/102_multimap.robot
- test/functional/configs/merged-override.conf
- **[Feature] Allow CDB files as external maps**
- **[Test] Add tests for CDB maps**
> Allow CDB external maps

- src/plugins/lua/gpt.lua
One bugfix for reason_header (see #5382) and some improvements that I think will be useful for everyone.
- Gpt prompt - Only ask for red flag when it's spam
- Insert Reason to result to show gpt answer in history
> [Minor] gpt.lua improvements and one fix for reason_header

- lualib/lua_maps.lua
- src/controller.c
- src/libserver/maps/map.c
- src/libserver/maps/map_private.h
- src/lua/lua_config.c
- src/lua/lua_map.c
- src/plugins/lua/hfilter.lua
- **[Rework] Store shared maps data separately**
- **[Feature] Show all maps status**
> Improve maps status visibility

- lualib/lua_redis.lua
Some Redis versions introduce important changes to the commands, for
example `EVAL` vs `EVAL_RO`. Rspamd should be able to use these commands
where possible.
Issue: #5418
> [Feature] Allow to specify Redis version

- contrib/lua-bit/bit.c
- Add code to prevent stack buffer overflow.
- Closes #5421
> fix(lua_bit) : Prevent lua-bit stack buffer overflow

- src/plugins/lua/contextal.lua
- src/plugins/lua/ratelimit.lua
> [Minor] Use module name when calling `set_pre_result`

- conf/common.conf
- conf/metrics.conf
- conf/modules.conf
- conf/rspamd.conf
- conf/scores.d/content_group.conf
- conf/scores.d/fuzzy_group.conf
- conf/scores.d/headers_group.conf
- conf/scores.d/hfilter_group.conf
- conf/scores.d/mime_types_group.conf
- conf/scores.d/mua_group.conf
- conf/scores.d/phishing_group.conf
- conf/scores.d/policies_group.conf
- conf/scores.d/rbl_group.conf
- conf/scores.d/statistics_group.conf
- conf/scores.d/subject_group.conf
- conf/scores.d/surbl_group.conf
- conf/scores.d/whitelist_group.conf
``file.conf`` seems to be a copy paste error and doesn't acutally work.
> Correct "file.conf" from dist config files

- rpm/rspamd.spec
> [Minor] RPM: fix log directory attributes

- interface/index.html
- interface/js/app/upload.js
- Add `Delete hash` button
- Rename `Upload FUZZY` button to `Add hash`
> [WebUI] Add `Delete hash` button

- src/plugins/lua/reputation.lua
fixes [#5146](https://github.com/rspamd/rspamd/issues/5146)
Added exclusion lists to reputation plugin, which lets you skip scoring/updating specific IPs, domains, or SPF hashes using exclusion_map. Supports all selectors with debug logs.
> Added exclusion list for reputation

- src/lua/lua_http.c
> [Minor] Update API docs RE: multiple HTTP headers

- lualib/lua_redis.lua
This change modifies how Rspamd handles Redis script loading across multiple servers to improve resilience during server failures and restarts.
Previously, the system required ALL Redis servers to successfully load a script before considering it ready for use. This caused modules to get stuck in a waiting state when any Redis server was down, reporting errors like: "redis script is not ready, waiting it to be loaded" even when most servers were operational.
Key changes:
- Replace is_all_servers_ready() with is_any_server_ready() to allow operation when at least one server has successfully loaded the script
- Reset all servers to "unsent" status when NOSCRIPT errors are encountered to properly handle server restarts
- Ensure script loading is retried appropriately on reconnection
This fix …
> fix(lua_redis): Improve Redis script loading

- interface/css/rspamd.css
- interface/index.html
- interface/js/app/common.js
- interface/js/app/selectors.js
- interface/js/app/upload.js
This PR finalizes the file upload feature for `Test selectors` :
- Add **Browse & drag-and-drop** support to `Test selectors` (mirrors`Scan/Learn` behavior)
Co-authored-by: ShravanAYG <shravanay205@gmail.com>
Closes #5381
> [WebUI] Add file upload to `Test selectors`

- interface/css/rspamd.css
- interface/index.html
- interface/js/app/history.js
- interface/js/app/rspamd.js
- Add 'Offset' and 'Count' inputs to History tab for selecting the range of history rows to load
- Add corresponding default setting in Settings tab
> [WebUI] Add history load range controls

- lualib/rspamadm/dmarc_report.lua
Currently, the `rspamadm dmarc_report` command ignores the `write_servers` configured in `/etc/rspamd/local.d/redis.conf`. It uses the configured `read_servers` for all Redis requests. For write commands this leads to the error message `READONLY You can't write against a read only replica.` As a result, no DMARC reports are sent.
This patch resolves this issue by setting the `is_write = true` argument for all write requests in the Lua script `dmarc_report.lua`.
> Use Redis write servers for write commands while generating DMARC reports

- lualib/lua_dkim_tools.lua
- src/plugins/lua/arc.lua
> [Fix] Fix whitelist options in the arc module

- src/client/rspamdclient.c
- src/libserver/protocol.c
- src/rspamd_proxy.c
> [Fix] Fix end-to-end proxy compression

- .github/workflows/ci_webui_e2e_playwright.yml
- eslint.config.mjs
- test/playwright/tests/scan.spec.mjs
Covers reading counters before scanning, scanning two test messages,
verifying history, resetting history, and checking updated counters.
> [Test] Add WebUI E2E scan flow test

- conf/options.inc
- lualib/lua_clickhouse.lua
- lualib/plugins/neural/providers/llm.lua
- src/libserver/http/http_connection.c
- src/libserver/http/http_connection.h
- src/libserver/http/http_context.c
- src/libserver/http/http_context.h
- src/libserver/maps/map.c
- src/libserver/maps/map_private.h
- src/lua/lua_http.c
- src/plugins/lua/bimi.lua
- src/plugins/lua/contextal.lua
- src/plugins/lua/gpt.lua
- src/plugins/lua/metadata_exporter.lua
> [Project] Implement more flexible http timeouts

- conf/modules.d/gpt.conf
- src/plugins/lua/gpt.lua
- Model parameters now applied to all models for both AI types.
- Improved prompt to return only a category if exist in provided list. GPT should now not add additional text to this category line so it can be matched to the categories map.
- ollama functions updated to be in line with openai functions
- Update default gpt.conf to reflect the changes to the model_parameters
> GPT: Refactor model parameters and response handling. Improved prompt.

- lualib/lua_redis.lua
> [Fix] Propagate unused Redis Sentinel options
